### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ###
### ONLY SPECIFIC FILES ###
### https://dev.to/eunit/how-to-automatically-deploy-from-github-git-to-cpanel-d36 ###
### ALL FILES ###
### https://ridbay.medium.com/how-to-deploy-your-github-repositories-to-cpanel-the-easier-way-16ec6e6cc7ee ###
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/montgatp/public_html/
    - /bin/cp -R * $DEPLOYPATH
