<?php
session_start();  //start or resume an existing session
include_once 'header-top.inc';
echo "<title>2017 Paul O. </title>";
echo '<link rel="canonical" href= "https://monterey.bayarearoundup.org/con-2017-paul-o.php" />';
include_once 'header-bottom.inc'
?>

<main id="main-content">
    <!-- Hero Part -->
    <div class="container shadow-wrap">
        <div class="row justify-content-center py-6 mb-5 bg-body-tertiary bg-img-audio-trans" title="Retro microphone on a blue background banner">
            <div class="col-xl-7 col-lg-7 col-md-12 py-5">
                <div class="p-3 text-center text-bg-light hero-text-border" title="Audio Speaker Transcript">
                    <h2 class="display-6 fw-bold text-primary"><span class="text-dark px-3 px-md-0">Audio Transcript: Raw and Unedited</span></h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Part One -->
    <article aria-label="Paul-O-Transcript">
        <div class="container shadow-wrap">
            <div class="row justify-content-center mb-5">
                <div class="col-xl-10 col-lg-10 col-md-12 py-4">
                    <div class="p-3 text-bg-light hero-text-border">
                        <section aria-label="transcript">
                            <h3 class="text-center p-4">Below is a raw transcript from the audio recording by<br>Paul O. in 2017.<span class="sr-only">(Click to go back)</span>
                            </h3>
                            <p class="indent">Good evening. My name is Paul and I'm actually a very mild alcoholic. Things that Max said were grossly exaggerated. Truth is that at the time she was talking about I wasn't even an alcoholic. I didn't become an alcoholic until I'd been coming to these meetings for seven months. It wasn't funny. It was a change in my life dramatically.
                            </p>
                            <p class="indent">
                                I'm glad to be here. I've had a wonderful weekend already and it's just now getting started for the rest of you. Denny and Phyllis were our host and hostess and we've had a wonderful time and really enjoyed it.Everybody should have a chance to be hosted by them at least once in your life. I had a great meeting this morning at seven o'clock and I'm just delighted with that. Looking forward to a great weekend and particularly looking forward to Earl's talk tomorrow night. Stand up and wave to the people. I know you love that. Come on. Come on. Too bad you can't see the blush that I can see. I just made a terrible blunder. One of the things I've learned early in AA is that you never smart mouth anybody who is going to follow you to the podium.
                            </p>
                            <p class="indent">
                                Oh dear. It was interesting the way the Christian opened the meeting with the serenity prayer. It reminded me of the Colorado one time to talk. They were having a fundraiser and it was the second year they had had it. The first year it was on Saturday afternoon. They had a meal at noon and then followed by a speaker and other stuff. The first year they had 150 people and they were quite happy with it but wanted to have it again. They asked me to come and talk and then what happened was the fellow that was setting it up doing the work. He called a resentment. I don't know if you have those here in this area.But he quit and called it off. Well that made everybody in town have a resentment that he called it off. They decided he couldn't do that by God. They were going to set it up and do it themselves. Instead of having 150 they had to shoot for 300. Well they worked so hard that they had 500 come to the thing.
                            </p>
                            <p class="indent">
                                What that did was put a strain on the caterer. It was a caterer meal. Caterer said it was okay. He could do it. It was just to take him a little extra time to get it ready. The other problem was that the local minister was supposed to come and read the invocation and he hadn't shown up. That way they saw that was they went to one of the old timers and asked him if the minister doesn't show up. The old timer would give the invocation. The old timer said well yeah he would do that. He started thinking in terms of what he would say. Meanwhile caterers were going and getting things going and the alcoholics are getting hunger and hunger. The old timer is making notes on what he's going to write in his invocation. Finally the caterer says well the food is ready. We can serve now. The alcoholic saw one to go. No no. They said you can't eat. Now you have to have the invocation first. They called up the old timer to give the invocation before they could eat. He got up there and he started to read. The first word was the word God and they all recited the serenity prayer and ran for the food. I don't know what the moral of that story is. I guess if you're an old timer if they asked you to give an invocation don't bring God into it too soon.
                            </p>
                            <p class="indent">
                                Anyhow people asked if we drove up or flew and I said we flew up. If you fly someplace one of the first things people asked you is did you have a nice trip? You did a nice flight. What we had happened on this flight was there were two flight attendants, a man and woman, a boy and a girl. They were going down the aisle with the cart giving the drinks out. They were right by us and he served us and he turned to the man in the seat behind me and he said what would you like to drink sir? He gave him his peanuts and napkin. He said he would like some white wine and she went through her cart didn't find any white wine and she turned to the man attendant and said to him do we have any white wine. This is all happening right here beside us and the man said no we don't have any white wine but we have plenty of red wine. So the woman attendant turned to the man behind me and she said sir we don't have any white wine. Would you like red wine? And he had to think about it. He had to think about it. Until he thought to think about that I hadn't realized what the serious social blunder it would be to drink the wrong color wine with airline peanuts.
                            </p>
                            <p class="indent">
                                Which actually it brings me to a I think to ask you a favor of somebody. I've been looking for somebody who is planning a slip. What it is is that you know all the airlines have a magazine they put out and American airlines it's I think it's American way American way or something. And in this magazine I was reading through it one of the department thinks this gal writes the thing every issue on the best buys and she'll talk about the best audio and the best video and the best play in the best movie in the best book and the best this and the best that. And under the best drinks she has the thing under the best wines. And what she said was that the 1992 Napa Valley Chardonnays have a crisp pear apple flavor with a touch of clove at the end. Now what I'm looking for is somebody somebody was planning on going out there anyway.
                            </p>
                            <p class="indent">
                                I really it's it's and remember it's the 1992 Napa Valley Chardonnays. I don't really care too much about the crisp pear apple flavor. But I really would like to know does it really leave you with a touch of clove at the end. Thunderbird never left me with a touch of clove. Thunderbird was my favorite white wine and ripple was my favorite red wine. And if you're out there we did check it's not worth me going out to check it out. No worth me going out. In fact in fact I have net a drink the last day of last month was my birthday. It was my 30th birthday. You know you're nowhere near as impressed as I am.
                            </p>
                            <p class="indent">
                                30 years is the longest I have ever gone without a drink. 30 years is a long time between drinks for me. You know the part about it too is 30 years without a drink and I'm not even thirsty. You know when I was drinking I was always thirsty. It seems like nothing makes me thirstier than having a drink. Alcoholism is a self perpetuating thirst and the best way to not be thirsty is to not drink. It took me a long time to figure that one out. It doesn't make sense. Actually one thing I noticed we didn't ask for newcomers. Can we see the hands of the people with less than in their first year of sobriety?
                            </p>
                            <p class="indent">
                                Everybody with oh my goodness. Oh my goodness. Wonderful. That's wonderful. That's wonderful. That's one of the places crawling with them. We love that. We love that. We love to have newcomers. I mean chuk chuk chuk.
                            </p>
                            <p class="indent">
                                His name was Bill. Bill W. One of the two. They haven't been around long. You know people are always changing their name. Every time I learn what's their name is they change it. Bill W. One of the two founders of Alcoholism anonymous said some place that was written that he had said that carrying the message of Alcoholism anonymous, carrying the message that Alcoholism is a disease and that AA is a spiritual answer to that disease. Carrying the message of Alcoholism anonymous he said is our primary aim and the chief reason for our existence. God those are pretty strong words.
                            </p>
                            <p class="indent">
                                Our primary aim and the chief reason for our existence. And then I got the word R. But as he talked about us as individuals or us as groups or both. But apparently carrying the message is the most important thing we do. And one of the main ways and most common ways of carrying the message is by filling a seat in an AA meeting and participating being part of it and carrying the message to newcomers especially into each other even. And particularly fun to carry the message to newcomers. I keep coming back to AA even if it wasn't keep me sober just to see what happens to the newcomers. It's exciting to see the thing that changed. It takes place in the people when they get sober and when the Alonons sober up. So we're all the newcomers here.
                            </p>
                            <p class="indent">
                                They say you're the lifeblood of the party and you're the most important in the people in the room and all that crap actually. I know it's important. So we're really glad you're here. In fact we're so glad you're here that we don't care whether you're glad you're here. As a matter of fact if you're really new here tonight and you're just really happy happy happy happy to be here we may not be able to help you. At least not until you get off of whatever you're on. That's why they say keep coming back. And so Andy how we're glad you're here and I'm glad to be here. I'm talking about me being the most important person in the room. You thought I was kidding but I'm not.
                            </p>
                            <p class="indent">
                                We have one of our new meetings there. We had started a topic discussion meeting and the format is for the leader. We pick a leader for each week and the leader comes in with a topic and then we talk on that topic for an hour and this gal came in and she announced that her topic was going to be bondage of self. And I thought that's a dumb topic. She won't get anybody to participate with that. Well she did and I thought of a lot of good things and they didn't even call on me. But that bondage of self I hadn't paid much attention to that until she said that and I got to think about it. And that bondage of self I came to realize that I am basically the most interesting person I know. I really find me fascinating. I love to think about me.
                            </p>
                            <p class="indent">
                                And somebody asked me the night and said well if you figured out what you're going to talk about tomorrow night I said yeah me. I love to think about where I've been and where I wish I'd been and where I wish I hadn't been. Things I've done. Things I wish I hadn't done. Things I maybe do. Things that might happen. Things I might not happen. Things I worry about. I love to think about me. You are interesting but you're nothing compared to me.
                            </p>
                            <p class="indent">
                                Believe me as bondage of self. I mean I hope he doesn't take that too seriously. What would you think about it if you're. Anyhow. In fact somebody said to me do you still get nervous when you're going to talk. And I said well I don't think of it as nervousness. I'd rather think of it as anticipatory anxiety. Sounds a little more scientific. And besides what I do is I love the third step prayer. And I tell God in third step prayer it's God I offer myself to the to build with me and do with me as I will.
                            </p>
                            <p class="indent">
                                Believe me of the bondage of self that I may better do that I will. And I modify that when I'm going to in fact the first thing in the morning before I really get out of bed. I say this is a serenity prayer. Third step prayer and a sub-step prayer. And then the breakfast max and I say those three prayers and we do read some stuff that we read and we have a period of meditation. And then during the day frequently if I have something I'm going to do or something that's a little bit scary or whatever I'll say the third step prayer. And sometimes when I got nothing nothing to do. I'll say that in the sweet prayer. But like when you come and talk I say God I offer myself and this situation to you to do with as you wish. Now I would like it to turn out to be phenomenally successful.
                            </p>
                            <p class="indent">
                                I'd like to say things that will ring in their hearts forever. But if you have it in your mind that this is the night for me to make a complete fool of myself well at least one of us will have a good time. And sometimes he really has a lot of fun. Yeah. We first do it as having somebody do with humility. And I don't enjoy that. So anyway I leave it up to him. And speaking of humility I think I'm really impressed with my humility. She bumped me. I'm proud of my humility.
                            </p>
                            <p class="indent">
                                I think I handled things very well. Anyhow I guess that's enough for the introduction. I should get into my story. I was born November 3rd 1918. It was a cold and blustery night. I remember thinking to myself. I wasn't talking very much then. I remember thinking to myself what am I doing here? Why wasn't I consulted on this? And I think I carried that thought the rest of my life.
                            </p>
                            <p class="indent">
                                I used to drink social drinking. I didn't have a drinking problem. I was neurotic. In fact I remember this should be added to the things we have tried in chapter 3. I was reading a medical journal and it talked about how carbon dioxide inhalations were a good treatment for psychonerosis. And I always thought that I was neurotic and I came from a very neurotic family. I used to endear myself to my family by telling them how neurotic I thought we all were. Not alcoholics but neurotics. I thought this is carbon oxide inhalation should be good for me. What it is is carbon dioxide is the thing that makes you breathe.
                            </p>
                            <p class="indent">
                                It's the thing that keeps you from holding your breath longer than you can hold it. It doesn't lack of oxygen. It's the fact that your body builds up carbon dioxide and makes you breathe. And if you hyperventilate your over breathing, you're blowing off the carbon dioxide and you feel breathless but you need to hold your breath or breathe in the plastic bag and accumulate the carbon dioxide. I'm going to send you all a bill on this. You don't get all this physiological instructions for nothing. But anyhow when you're breathing carbon dioxide and you keep breathing too much of it, you breathe faster and faster and faster and faster and deeper and deeper. And the lights flash in the bells ring and you go blind and it just goes, it just goes, it thinks you have to go louder and louder and louder and all of a sudden your brain explodes and you pass out. I thought, boy, that ought to cure something. I will try that.
                            </p>
                            <p class="indent">
                                But I couldn't see my way to going to any doctor and saying, I'm neurotic and I want some carbon dioxide inhalation. Here's a written in this medical journal. And besides, I'm the best doctor I knew. And so I just called up the gas company and not your gas company but the gas company sells tanks of gas in order to tank of carbon dioxide gas and the guy delivers it in the big truck with these big tanks. This tank about so big and so big around. Must weigh about 250 pounds, get it on a dolly, runs it up to the front door and says, where do you want this? I said, well, in the master bedroom, naturally, you know, where would you think I would want it, you know, with a hose and a mask and a valve you can turn it on. So it didn't take any medical degrees, I know you should lie down to do this and you put the mask on and you turn the gas on but you didn't have to be a genius to know you needed somebody to turn it off. So I go into the living room and I max this watching TV and I said I'm gonna take this treatment and I'm gonna breathe faster and faster and finally my brain's gonna explode and I'm gonna pass out and when I pass out will you come in and take the mask off and turn the gas off. And she said, I suppose, anyway, it didn't work.
                            </p>
                            <p class="indent">
                                Didn't take care of my drinking problem. I didn't have a drinking problem, I had a sleeping problem. I had a lot of marital problems. She said, Max, as she said, she, he drove me to drink for 28 years. In fact, as we were growing up, we've done each other since we were four years old and the Gansline boys, her uncles and that were alcoholics and they were always getting put their name in the Atlanta Review and putting jail for a common drunken. As we were growing up, my parents were not at least a bit happy for me all the time playing with the Gansline girl. They were afraid that wouldn't be grew up, but we might get married and I might turn out to be an alcoholic. And by God, they were right. It's not really funny. Most people don't know how they got to be an alcoholic.
                            </p>
                            <p class="indent">
                                I do. I'm an alcoholic by marriage. Anyhow, yeah, we had our problem here and there and it caused me to have trouble sleeping. I used to, I found out that I could, when I went to pharmacy school, I found out that night I'd go to school all day, working in the drug store all evening and then study it all through the evening and then jump in bed and everything I'd been studied, been running through my brain and in the morning I'd be both tired and stupid. And I found that I could drink a couple of beers, jump in bed, sleep real fast and wake up smart. And that's how I got through pharmacy school, drinking more and more. And as the time went by, I found it took more and more to get me to sleep and it kept me asleep for a shorter and shorter period of time so that I had to repeat whatever I had taken to get to sleep. And then I, that increased to the point where it was harder and harder to get up in the morning and then finally I started taking amphetamines to get going in the morning. I shouldn't mention drugs, this is negating, but I feel I do owe them at least an honorable mention. I don't know that I could have had the stamina to have completed my pre-A training period if it hadn't been.
                            </p>
                            <p class="indent">
                                I did, they did tend to affect my voice and that I sometimes couldn't, I, affected my hearing and that I couldn't listen fast enough to hear what I was saying. And they might go, what are you saying that again for you? Well, already said it again, I don't know, it just sounds so good. I think I'll say it again. And finally, the ultimate of trying to, working on a sleeping problem, that's a really good, that's an oxymoron if I ever heard one, working on a sleeping problem. If you're working on your sleeping problem and you find something that works, you've got to think, only what was that and I've got to remember what that was so I can do it again. And you're constantly alert to see whether or not you're sleeping. The epitome of that was that I finally was shooting amatol at night in order to get to sleep at night. I would go through the day taking pills and then evening drinking and then it was time to go to Betty Bye and I would go to keep the amatol, the penithol or anything at all. I'd keep it in my bag and the bag in the car and the car in a garage, in the garage, thank God it was attached to the house.
                            </p>
                            <p class="indent">
                                And I'd go out and I'd try to mix up the stuff and get it in the syringe and then I'd try to figure out how much of I had to take out the uppers and how much of the downers and how much I can squirt it and take it out, take it out, throw it in the bag and throw it in the bag and car slam the car door and run down the hall so I could jump in bed. And it was very tricky to judge it. It took a lot of experience. It wasn't entirely practical. Because at least a little bit too much and I just zing right under the car. That wasn't too bad. The worst part was at least a little bit, not enough. And I'd squirt it in, take it out, throw it in the bag, throw it in the bag, throw it in the car, slam the car door, run down the hall and jump in bed. Nothing would happen. Half measure has got me nowhere at all.
                            </p>
                            <p class="indent">
                                And even when it did work, when it did get just the right dose, you take the needle out, you're supposed to put a band-aid on and keep it antiseptic. And all that said, I didn't have time for that. I didn't have time to put band-aid on, so I would put my arm up like this and hope that the gravity would take care of it. And I'd do all this one hand and throw it in the car and run down the hall. And I'd go with one arm up the air. And I'd run into Max and try to act casual. It's actually hard to be casual when you're in a hurry. And anyhow, I ended up in the Nutword. That's what I did. They remember sitting there in the Nutword.
                            </p>
                            <p class="indent">
                                They wanted me to make leather belts. In fact, at that particular hospital, there were fanatics on leather belts. You can't graduate. I'll bet if they had a Senate investigation, they'd find their people have been there for years. And they won't let them out until they make something useful. They wanted me to make leather belts. And they tried to convince me that the quality of my life would improve if I learned how to make leather belts. I told them, I said, I have a whole wall. I have a wall full of licenses and certificates and diplomas and papers to prove that I've been educated way beyond my level of intelligence. And I don't see how making leather belts would improve my life in any way.
                            </p>
                            <p class="indent">
                                I didn't understand the philosophy. And besides, I didn't understand the instructions. Which is not my fault. That's all that dumb occupational therapist. Because I've always known, if you don't understand anything well enough, you can explain it to me. So I understand it, and you don't understand as well as you're supposed to. And she'd explain it to me three times. And I wasn't going to embarrass her by asking her fourth time. So I was sitting there in the net ward, commiserating with myself. What's a nice guy like me doing in a place like this?
                            </p>
                            <p class="indent">
                                And this dumb psychiatrist who couldn't see that my problems were strictly marital, walked up behind me and wanted to know, would I be willing to talk to a man from alkaloxanonymous? And I thought, my God, don't I have enough problems on my own without trying to help some drunk from AA? I could tell by looking in his face that he thought it was a good idea. And I decided right there that happiness on the net ward is having a happy psychiatrist. And I said, yes, and in no time at all this clown comes galloping into the room. Yelling at the top of his boys, my name is Frank and I'm an alcoholic. I was embarrassed for him. Leading a perfect stranger, and the only thing you could think about to talk about himself was he was an alcoholic. I got sick. In fact, everything he said, he said in a loud voice, such drunks and us alcoholics and alkaloxanonymous.
                            </p>
                            <p class="indent">
                                I thought, my God, man, why don't you lower your voice? These people all think I'm a nut, why don't we leave it at that? Another thing I didn't like about the nut ward is they wouldn't let you stay in bed in the morning. You had to get out of bed, and if you wouldn't go and make moccasins and you had leather belts, you had to go and sit in the day room. And the day room is a big room, and as a one-hole wall was glass. And on the other side of the glass was the sidewalk to the main entrance of the hospital, which was right there. And I could just see my patients walking by, looking in. Oh, hello, Dr. Paul, how are things in the nut ward? Anyhow, this rank told this loud-mouthed story.
                            </p>
                            <p class="indent">
                                I don't remember, long and non-very interminable story. And I don't remember anything he said, but I know it ended by him saying, well, that's my story. I'm going to a meeting tonight, which I'd like to go along. And I said, hell no, I won't like it. But I'll go. And we went, and I have no idea what meeting we were at. In fact, I don't know how many meetings we went to before. I knew what meeting we were at. But I knew that meeting had a profound effect. It had a profound effect on the psychiatrist.
                            </p>
                            <p class="indent">
                                Now he was suspiciously very interested. One know what's this about a book, what's this about meetings, how often they have meetings, what's this about steps? What other kinds of meetings do they have? When you go into another meeting, and I thought, my God, I've got me an alcoholic psychiatrist. He's ashamed to go, so he's sending me. So I wanted to go to every meeting I could, so I could get enough brownie points to get out of that dump. And I told Frank, I wanted to go every night. Frank was good about that, except for one Friday night. He didn't know that he would be going. He thought maybe on Friday night he might have a date with Carolyn.
                            </p>
                            <p class="indent">
                                And I thought, well, that's a hell of a way to run an organization. And I reported him to the psychiatrist who got somebody else to take me on Friday night. And I finally got enough brownie points and I got discharged from the hospital and I had no intention going back. Why would I go back? It wasn't an alcoholic. The only problem was that Max liked the meetings. And of course once I found that out, the threatened her, she didn't shape up. I wouldn't go to A. A. anymore.
                            </p>
                            <p class="indent">
                                I said that once too often. And she did what she couldn't do. She drove down to Laguna Beach from Anaheim and went by herself, went to meet by herself. She couldn't drive the freeway. She didn't know how to get that far, but she did it anyway. She went off, went to the A. A. meet for herself. Have you ever tried that? You ever tried sitting at home on a Saturday night drinking while your non-alcoholic spouse is off laughing it up in an A.
                            </p>
                            <p class="indent">
                                A. meeting? Mm-hmm. Mm-hmm. I found it boring. I think it back to me to find out what they were laughing about. I found out that the alcoholics laugh at anything. Laugh at nothing. Laugh just to be laughing then. I sat there trying to figure it out, seven months.
                            </p>
                            <p class="indent">
                                And I ended up going to one meeting too many. And one night I laughed with him. Having that a drink since. I said. I had a laugh after his very spiritual to me. In fact, I'm convinced that my higher power laughs. My higher power laughs. Every time he hears alcoholics and now he's on his laugh. Even if he doesn't understand a joke. Just enjoys the laughter.
                            </p>
                            <p class="indent">
                                So I've been coming back ever since. And when I first became an alcoholic, I was just very, very mild alcoholic. Very mild. Just almost a non-alcoholic. Laugh. But I had to keep coming to meetings in order to drink. In fact, I decided that I came into this thing embarrassed to be here. I thought my condom at the bottom of the social barrel and had this overwhelming sense of failure in all areas of my life. And I turned into an alcoholic and I found out I had to become an alcoholic in order to quit drinking. And then I thought, you know, if I'm going to be in AA, if I failed then everything else ought to at least succeed in this, for God's sake.
                            </p>
                            <p class="indent">
                                If you can't get any lower than this, you've got to at least succeed here. And I decided I wanted to be a successful member of AA. Simple request, it seemed to me. And I didn't make it packed with anybody else, just with myself. I decided I'm going to be a successful member of AA. In fact, I even went so far that that time it talked about stick with the winners. Stick with the winners. Stick with the winners, they said. I thought, well, if I'm going to stick with the winners, I'll find out what a winner is. So I asked Chuck C.
                            </p>
                            <p class="indent">
                                He'd been sober a hundred years or so. And he knew everything. I said, I said, what's a winner? And I was surprised when he had to think about it. And he said, well, I guess you have to die sober. And I thought, die sober. God, that reminded me of how I used to plan on being one of the saints. How, how yourself. I was really going to do it. I went and got the book, Life of the Saints.
                            </p>
                            <p class="indent">
                                Big, sick book. I was reading up. I decided which one was going to be my role model. I was going to be a saint. Trying to pick my role model. Until I found out that the final thing about being a saint, you can't be a declared a saint until you've been dead 300 years. And I thought, well, screw that. I've never been happy about anything you have to die to get the accolades for. I lost my sainthood. And I thought, well, if I have to die to be a winner, I'll just be a successful member of AA.
                            </p>
                            <p class="indent">
                                And over the years I've changed my little bit what my criteria is to be a successful member of AA. But I don't know any successful members of AA who drink. And then I found out that if I want to keep from drinking, I've got to keep going to meetings. It takes a lot of meetings to keep from drinking. But the more I went to meetings, the more I realized that if I want to stay sober, I've got to work the steps to stay sober. And then once I worked the steps, I kept going to meetings and working the steps and seeing what was going on around me. And I found there are a lot of people, seems to me a lot, who go to meetings long enough to stay sober to find out they have to work the steps. And then find out they don't need the meetings anymore and end up getting drunk after 15, 20, 30, 40 years. So I thought I've got to do both. I need to keep on with the meetings and keep on with the steps in order to stay sober.
                            </p>
                            <p class="indent">
                                And I've been doing that long and it's been working real well for me. And I'm trying to keep that up. I'm trying to keep on doing what I'm doing. And I was going to say I enjoy working the steps. And I stumble over that. Well, only in the sense that it's not working the steps. It isn't always fun, fun, fun. But I enjoy the life that I get from living, from doing the steps. And I have gotten involved in the pamphlet on how to study the first time I've had a six, four pages of the book and how to do the steps when you come to it. It's not a step study, it's a step do it.
                            </p>
                            <p class="indent">
                                And being involved with that, as a part of that, I have redone the steps. It turns out about every five years. And what my experience is that every time I've done that, I've moved to a new plateau in my sobriety. I'm not saying yes, but anybody else should do. A lot of people say you do the steps once, and that's all, and you're the maintenance steps. And then there are other people say you do the steps every year. I don't care what you do, I'm just saying what I do and what this works for me. And I like it that way. And I enjoy the steps. I touched on the third step before, and I really enjoy the third step, turning my will in my life over the care of God.
                            </p>
                            <p class="indent">
                                And I tell him, God, you take my life and do what you want with it. And I'll pedal, and you steer, and for God's sake, watch where you're going. I'm sick of some of the places we've been. In fact, I have at my office at home, I have a plaque-like thing. It's a photocopy of the one page of the magazine or the book section of the LA Times. And it's a picture of the author and the name of the book, and it's a quote from the book. And I have to really have it up there because I like the quote from the book. And the quote says, I suppose if I'd got the job I wanted at Montgomery Ward, I never would have left Illinois. Simple enough statement. I suppose if I'd have gotten the job I wanted at Montgomery Ward, I would never have left Illinois.
                            </p>
                            <p class="indent">
                                The author didn't get the job at Montgomery Ward, he didn't leave Illinois. And he became a sports and radio sports announcer, a movie actor, a union president, a governor of California, and president of the United States. And it's so much like what we hear, we don't get what we want, but we get what's according to God's plan. And I need to remember things like that. It's often best when I don't get my way. And I am, this business of enjoying working the steps, more I think of that, the more I think of it. Like the, it's such a profound difference, the sixth and seventh step. So profoundly different than what I feel I was taught all my life. I was always taught, as I understand, that I could have done better if I'd have tried harder. All I had to do was try harder.
                            </p>
                            <p class="indent">
                                And today I look back at, and I was trying as hard as I could all the time. I really think I have been doing my best at every moment of my life, up to and including this moment. And so is everybody else. If we could have tried harder, we would have tried harder. But the thing that I always thought, it was up to me to correct my defects of character, that I should work on them. And that I should ask God to help me get rid of my defective character. And anything I wanted to do, I need to ask God to help me do what I wanted to do. That was an epitome of that, was asking him to help me with my drinking problem. Help me, help me for God's sake, help me. And I thought he was saying, screw you, Paul.
                            </p>
                            <p class="indent">
                                But he wasn't. What I found is that God won't help me. God won't help me do His will. My will, He won't help me do my will. But He's perfectly willing for me to help Him do His will. He's talking to Him into helping me do what I want. And it's the same way with my defects of character. I have to become friendly with them. I have to become friendly with my defects. I used to fight them, and they love that.
                            </p>
                            <p class="indent">
                                They're really energized by that. I have to become friendly with them and hope to have them removed whenever he removes them. I'm having a little difficulty finding the words to what I want to say now. It's not that having difficulty knowing what I want to say because the people in my head are arguing about what I ought to be talking about. You're sitting there very quietly and very attentive, and I appreciate that. People in my head are chattering away like, man, one of them says something I ought to talk about, and before I say anything about another one over here says, no, no, don't talk about that. Talk about this before I can do anything about that. A third of them say, no, no, no, talk about this thing. And they get the finding back and forth among themselves, and it's really very distracting. And I think, well, shut up up there, you know?
                            </p>
                            <p class="indent">
                                And they shut up, and I can't think of anything to say. In fact, that's one of the biggest things about doing the steps of living this program. I've gotten a lot more comfortable with them up there. I don't fight them anymore. There's just no fighting them. I don't do everything they suggest. I mean, I'm so glad you can't hear the stuff I have to live into. A lot of this stuff is illegal. And even more of it is lewd. But I don't fight them.
                            </p>
                            <p class="indent">
                                And the things they suggest are out, because I don't fight them anymore. Thank you for participating. I listen to everybody, and I decide what I'm going to do and how it's going to be from there. Anyhow, I really enjoy living this program. And I enjoy being married with Max. Max mentioned at the end of this year we will have been married 58 years. We've known each other for over 70 years. Last December 2nd was our 57th wedding anniversary. And I told her that my gift to her, our wedding anniversary, was that I was going to do everything that I could think of. Everything I could think of, not everything she could think of, to make our 58th year the best year of our marriage.
                            </p>
                            <p class="indent">
                                And every day since that time I've reminded her of how lucky she is. She mentioned about communication, learning to communicate. I have come to the conclusion, I don't know if it's true or not, but I do think it's true. And I know it's good for me to believe that it's true and live my life as if it were true. That people treat me the way I have taught them to treat me. That if I don't like the way somebody is treating me, it's up to me to change my behavior rather than to try to get them to change theirs. Remember one time I said a thing on communication by Sister B, you got to get her up here if you haven't had her. Wonderful gown and here talk. She was talking about communication and she got to a question and answer period. And somebody asked the question, what is communication?
                            </p>
                            <p class="indent">
                                And I thought, well, that's a stupid question. But then I was surprised when Sister B couldn't answer it. And I was not only surprised, I was disappointed when she says, Paul, how would you answer that? And I couldn't think of a good definition for interpersonal communication, but I did remember having read some place that a measure, a measure of communication is the result that produces. If you don't like the results you're getting, don't blame the other person, blame yourself. If you've taught them to treat you the way they're treating you, you can teach them differently. Different, whatever the right word is. Teach them to do it differently. But anyway, I find that a real challenge. I have become very conscious of the max of my communications and communications generally.
                            </p>
                            <p class="indent">
                                Life is basically a communication problem. I have relationships with people, places, things and situations, and communications about those relationships. And I really think that an interpersonal marriage and partnership, it really is an ongoing test of one's communication skills. That is enough of that for God's sake. Let me say this. I was thinking somebody showed me a computer program that makes charts. You use this program in a computer, you put in data and it will make a pie chart and cut it up in pieces and color it all and stuff like that. Or make a bar graph and all that fancy stuff. And I thought, well, if I had a giant computer and put all the facts of my life into a computer with that program, what would a graph of my life look like? And I came to conclusion that it would be like that the Jellinck chart, that it would be a giant D.
                            </p>
                            <p class="indent">
                                That my life started way, way over there. And it's going to end way, way, way over there. And it's a D. And when I was born in 1918 until July 31, 1967, it was on a downhill course. Now it wasn't the straight line down, it was up and down. Just enough up to keep me confused. And when it went down, it went down, or the inferno went down the last time. And it ended up in the network of the hospital that's on the staff. And that wasn't bad enough. I had to go to AAA.
                            </p>
                            <p class="indent">
                                And I went to AAA for seven months and one extra meeting, too many. And finally, I accepted the fact that I, of all people, strangers at my team, and even though I had no choice in the matter, I was a mild alcoholic. And from that point on, my life's been getting better and better and better and better. And today it's far better than it's ever been. And as far as I can tell, the only limit to how high it can go is how long I stay around doing the things I'm doing and it's keeping it going up. And with what intensity I keep doing this program, and again, it's not a straight line up, it's up and down, up and down. But even when it goes down, I know a lot of things to do to go back up, go to more meetings, read the book, talk to a new programmer, call people on the program, start a new meeting. I can't think of anything else to do, I go start another meeting, anything, doing service, doing part of the AAA, reaching out to others, or doing nothing. I know that when it goes down, it's going to go back up. That's when they say, sit still and hurt.
                            </p>
                            <p class="indent">
                                Or as Winnie Eddie used to say, the Eleanor speaker, that was the only Bible quote she ever used. She said, the Bible says, and it came to pass. This is the Bible did not say, and it came to stay. It's always going to get better. I want all I can get out of this program. I know nobody can live long enough to get everything in this program has to offer, but I want all I can get. All I can get. And it all started, the thing that fascinates me is the point of the V. One act of acceptance of one reality changed the course of my life. And I thought, would that be something if I would just automatically accept every reality in my life as it comes without even evaluating it?
                            </p>
                            <p class="indent">
                                Because my tendency is to decide whether or not I like it. And approval, as Max said, is going to say approval has nothing to do with acceptance. It does have a lot to do with acceptance. It's an impediment to acceptance. The answer to the question why is an impediment to acceptance? Because the answer to the question why or why me is why not? Why not you? It was Robert Schuller's use to say, when people ask God why they don't want an explanation, they want an argument. But the thing that bothers me, when I think about the change in the direction of my life, as smart as I am, and it's good looking, why did it take me that long to realize that I was an alcoholic? And the only thing I can see is, it has to do with that approval thing.
                            </p>
                            <p class="indent">
                                I didn't approve of me being an alcoholic. And I thought, if you accept something, that a priori means you approve of it. I mean, if you buy merchandise and obviously you must approve of it, you wouldn't have bought it. Or you get it home and you find out it's not what you thought it was, you don't approve of it. You don't keep it, you take it back for God's sake. And that's the way it is out there in that world. But in God's world and the world of reality, approval is, I can't think of a single significant thing in reality of my life, where anything was changed just because I didn't approve of it. In fact, when I picture God up there creating reality, working day and night, holidays included, working like a fiend, creating reality, I just visualize one of his specialions, coming up and saying, oh my God, God, we got a problem. Paul doesn't like today, we sent him. I can just see God saying, well, you can tell him where to go.
                            </p>
                            <p class="indent">
                                And I think that's basically what it's all about. Our job is to accept life, whether we like it or not. And I love that line in the middle of page 132 that says, we absolutely insist on enjoying life. Absolutely insist on, I've read many textbooks, studied many textbooks, never before, ever saw a textbook on how to recover from a seemingly hopeless state of mind and body, a serious medical illness where part of the recovery was, is you absolutely had to insist on enjoying your recovery. And yet, I find if I'm not enjoying my relationship with Max, I'm not doing it right. If I'm not enjoying my program, I'm not enjoying it right. I'm not saying we have to be happy, happy, happy. But in AA, we can enjoy AA funerals. See, somebody dines over. I mean, all kinds of things, we get joy, even in the mystery that we're going through.
                            </p>
                            <p class="indent">
                                The people in my head are arguing. Half of them keep telling me, your time is up, shut up. And the other half are saying, no, this is fun, let's sit in here and talk somewhere. And one of them keeps telling me, tell them you love them and sit down. But I hesitate to say, I love you all because when I was due, I'd hear people say that and say, and I love you all. And I think, oh, crap. You don't even know me. And if you did, you wouldn't like me. But anyway, I love you all whether you like it or not. Thank you very much.
                            </p>
                            <p class="indent">
                                Thank you very much. Thank you very much. Thank you. Thank you. Thank you.
                            </p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <?php include_once 'footer.inc' ?>
    </body>

    </html>