<?php
session_start();  //start or resume an existing session
include_once 'header-top.inc';
echo "<title>2022 A.A. Chris T.</title>";
echo '<link rel="canonical" href= "https://montereybayarearoundup.org/con-2022-chris.php" >';
include_once 'header-bottom.inc'
?>

<main id="main-content">
    <!-- Hero Part -->
    <div class="container shadow-wrap">
        <div class="row justify-content-center py-6 mb-5 bg-body-tertiary bg-img-audio-trans" title="Retro microphone on a blue background banner">
            <div class="col-xl-7 col-lg-7 col-md-12 py-5">
                <div class="p-3 text-center text-bg-light hero-text-border" title="Audio Speaker Transcript">
                    <h2 class="display-6 fw-bold text-primary"><span class="text-dark px-3 px-md-0">Audio Transcript: Raw and Unedited</span></h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Part One -->
    <article aria-label="Transcript-Three">
        <div class="container shadow-wrap">
            <div class="row justify-content-center mb-5">
                <div class="col-xl-10 col-lg-10 col-md-12 py-4">
                    <div class="p-3 text-bg-light hero-text-border">
                        <section aria-label="transcript">
                            <h3 class="text-center p-4">Below is a raw transcript from the audio recording by<br>Chris T. in 2022.<span class="sr-only">(Click to go back)</span>
                            </h3>
                            <p>I'm going to move this out of the way. Hi everybody, my name is Chris and I'm an alcoholic. I want to thank the Embark Committee and volunteers and everyone that helped put on this weekend. It's been a lot of fun. A lot of memories have been made. My fellowship is grown from all the people I've got to meet.
                            </p>
                            <p>And it's been great to be a part of this. I'm going to read something to start out with. It's something that's read in a meeting that I regularly attend. But I always like to read something just to get out of my head and to let it flow of what I'm supposed to be talking about. I was really nervous about two things today on speaking. One, that I'm going to make sense and two, that I'm going to have to go to the bathroom when I'm up here.
                            </p>
                            <p>She can't stop once you're up here. But anyway, it's on page 85 of the big book. It is easy to let up on the spiritual program of action and rest on our laurels. We are headed for trouble if we do, for alcohol as a subtle foe. We are not cured about alcoholism. What we really have is a daily reprieve contingent on our maintenance of our spiritual condition.
                            </p>
                            <p>Every day is a day we must carry the vision of God's will into our activities. How can I best serve thee, thy will not mine be done? At some point, working the steps with my sponsor and reading the big book, on the bottom of my book I have reprieve. Embrary relief, contingent, dependent for existence, maintenance, upkeep, spiritual process of transformation, condition, existing state. And so, here's what I know. So, what it was like, what happened and what it's like now.
                            </p>
                            <p>Growing up, I was alcoholic before I had my first drink. And by that, I can see where there was an obsession. There was this weird thoughts, these weird feelings that I had, just things that didn't put me in a position to where I could feel I could relate to others. There were things that had happened in my life. There were things that I was brought into in my life and those were not the things that had me feeling uncomfortable. As an alcoholic, I know it is how I process things.
                            </p>
                            <p>So, some of the things that I can recall as being an alcoholic before ever having a drink is, I could calculate and I know the amount of alcohol that my parents drank and I never had a drink. I knew that at one point it was really hot where I grew up and my mom wanted to go to the grocery store and we went to the grocery store and she bought a six pack of near beer. She drank one can of that near beer and it stayed in this white storage cabinet that we had in our pantry. And I remember that. I know that my dad didn't really drink. He never really talked about his growing up.
                            </p>
                            <p>But I knew that every Christmas season he would get some E&J brandy and he would make himself an eggnog and he would put some brandy in that and that brandy would sit on the counter of his wet bar that he had in our house for like the rest of the year. You know, on occasion he would like go to the grocery store and he would get this green jug of wine and he would like have a cup and it would just sit there. And you know, not until after I was a sober member of Alcoholics Anonymous, could I recall or understand like none of my other friends calculated or monitored how their parents drank like I did. And that was before I drank. My mom was a diabetic. She was in the Nada hospital.
                            </p>
                            <p>She was sick and she passed away before I had even graduated from high school. And you know, I could take that experience and where I hated the fact that people that I grew up with knew that I had a sick parent, I worked that for sympathy when I finally started drinking. Like I think one person made mention like, oh, like she might drink a lot because of like, you know, she had a sick mom, you know, and I was like, yeah, that's it, you know. And it wasn't like the reality of it is when I drink something happens inside of me. And for me, I lose all control and I lose the choice. My very first drink, I had a bet.
                            </p>
                            <p>I was like with my friend at his house and I had eyeballed his mom's liquor cabinet just like I calculated and monitored the way my parents drank. And his mom had a liquor cabinet and one day we were hanging out at his house and I was just like, let's play a game. And he was like, all right, what? And he was like, we're going to get, I'm all, we're going to get a glass. We're going to put it on this lazy Susan. We're going to fill it up halfway.
                            </p>
                            <p>We're going to spin it around and whoever lands in front of that, who's going to drink it. And I had to drink and I was like, I made up this game and a drinking game without ever drinking before. And it landed in front of him and he didn't want to drink it and I was like, all drink it, which is what I wanted to do anyway to begin with, but we made up a game about it. And I downed it and it burnt when it was going down and I knew I was going to throw up and I didn't want to throw up at his house so I walked home. I cannot tell you what happened when I got home. I did throw up on the way home and when I woke up, I was on my bed and I came to.
                            </p>
                            <p>So my very first drink was exactly like my last drink. And a way more alcohol than my body could consume a blackout and coming to. And that is how I drank every single time after that. I was raised in a household with morals and standards and consideration of others and I was told to practice that when I went to go visit my friends and hang out with them. And I can tell you when I started drinking those things, I started exchanging. I went from having a group of friends that I grew up with that I love to do things with that to starting to my friends started changing.
                            </p>
                            <p>I went from playing three sports in a school year to slowly dwindling down to playing no sports come my high school year. And I took my first drink maybe when I was 13 or 14, not quite sure, but my drinking progressed after that. It went from that one drink to maybe just drinking on winter breaks to then lingering into drinking on weekends. To by the time I graduated and my friends were pursuing college and I knew I didn't want to give effort to something other than drinking. I didn't know that that's what it was. But I knew that things that required my focus effort and attention, I didn't want to give that.
                            </p>
                            <p>My effort and attention went to how I was going to get that next drink so I opted to stay home, do junior college, get a job and figure out how to pay for my own drinking. And then it escalated after that until I was 21 and I could by the time I was 21 I was drinking on a daily basis. And geographics would happen. Friend groups would change. What I know is while I am actively drinking, I become unreliable. I cause worry in others.
                            </p>
                            <p>I lie. I lead a double life. There are things that happen that end up becoming uncomfortable and that's what causes me to change my assortment of friends. I did geographics before I knew they were geographics and everything becomes unmanageable. Where I crave connection and community, I feel uncomfortable in my own skin. And even if I have that connection or a sense of community with you, if I drink something uncomfortable and embarrassing is going to happen and it's going to be fleeting.
                            </p>
                            <p>I realize these things are very possible for me to still have character defects that I talked about being untreated. And I was introduced to alcoholics and honest at a very young age and every single time I just had that fight or that reason that I wasn't an alcoholic. It was the other things. It was the people around me. It was the job. It was the boss.
                            </p>
                            <p>It was the girlfriend. It was where I lived. It was my age. It was what I drank. Chapter three. 100% all the way.
                            </p>
                            <p>What I didn't calculate and what I couldn't see as being problematic was the consequences that would start happening around now. Eventually what I ended up coming to Alcoholics Anonymous with was two DUIs, three treatment programs, two last jobs. Everybody in my friendship circle being absolutely frustrated with me where they didn't want to talk to me anymore because all it was was a sense of drama and depression and lies. And my employer who had already put me through one rehab was now putting me through a second and it was very strongly suggested that I went and seek treatment because otherwise if I didn't, my job would be at stake. So alcoholism, I avail responsibility and dependability. So when it came time to decide what it was that I was going to do, I either could pay rent or I could pay a down payment for a treatment program.
                            </p>
                            <p>And I had to weigh the options. And it seemed like maybe a treatment program might be a great idea. I still try to think up some other ideas. My boss quickly shot them down. And so I went ahead and went with the treatment program. The alcohol and alcoholism leveled a bunch of things for me.
                            </p>
                            <p>Coming into a treatment program and not being able to pay rent, I immediately had to take into account the material things that I had, what was a necessity and what was something frivolous. I gave away everything that I had except for some luggage and some personal belongings that needed to fit into a friend's garage. And when I went to a treatment program, which was here locally, I had way more luggage than I needed to have. I let them know, hey, these are my belongings. This is what I need. They said if you can fit it in your room, we're going to let it pass.
                            </p>
                            <p>And that's what I did. And it was the first geographic that I was making actually without like a plant or an outcome. But I knew through having exposure to Alcoholics Anonymous that doing things my way or doing things partially wasn't going to work and I needed to get here and I needed to do it. You know, cutting corners and finding an easy way out has been something that I've always tried to do as a kid. You know, I was fine being a C student. I was fine not going away to school.
                            </p>
                            <p>I was fine being second string on teams. Like I didn't want to put in any extra effort to be successful at anything that I did. And what I found out over time after being exposed to Alcoholics Anonymous is this isn't a program that you can be successful at by doing things halfway. I might be able to get separated from alcohol, but if I don't change my behaviors, I will have problems pile up on me. They will eventually lead me to they will lead to unmanageable situations. I will feel very uncomfortable inside and taking a drink will be my best out.
                            </p>
                            <p>And so when I got here, that just wasn't an option. Not only was it something that I was coming in with the second DUI, like I said, no money. I also hadn't filed taxes in eight years. So the government was really wanting that money as well. And they send you several letters before they decide to go aggressive with you. You should probably open them if that's the case.
                            </p>
                            <p>But I was not doing that. And so I immediately had like legal financial emotional like all this wreckage just piled upon me. And I didn't know where I was going to go or what I was going to do. But I had this time at this treatment program. So I finally just decided to do what was suggested. I got here and I immediately got a temporary sponsor and started working the steps.
                            </p>
                            <p>That temporary sponsor turned into my permanent sponsor. And there just been a lot of loss. I came here without having any of my immediate family members left. And there were these weird things floating around in my head thinking that certain things happened, I would drink. And I ended up branching out of that treatment center, renting a room, starting to get involved in the fellowship like immediately. Sometimes I would feel so uncomfortable that I would attend like four meetings a day just because I had the time on my hands and what else was I going to do.
                            </p>
                            <p>I was connected with a 645 in the morning meeting because I made mention to somebody at the treatment program that I was at that I wasn't sleeping very well. And they said, well, if you can't sleep very well, instead of laying in bed and trying to figure out your problems, like maybe why don't you just get up and go to a 645 meeting. I gave that my suggestion to my sponsor hoping that she might let me sleep in a little bit. And she said, that sounds like a great idea. And when you get up, make your bed and fold up your clothes and pick out your clothes that you're going to wear when you get back to your room. So when you walk into your room, it is not chaotic and you have a plan for the day.
                            </p>
                            <p>When you take off the clothes after you take a shower from getting back from that meeting, put them in the dirty clothes. Don't let them pile up. And I was like, all right. And so I did that. And that's exactly what would happen. I would come home with a plan and I would have a free and clear mind.
                            </p>
                            <p>And I wouldn't look around my room and see these things piling up on me like was that it happened with the things that I was trying to clear up in working the steps and working with her. As part of the fellowship, you get new, you start meeting people, you get introduced to different meetings. Immediately people in the fellowship started passing along service commitments to me. Shortly after I got sober, there was a brand new meeting on Wednesday nights that required a greeter and me and a friend were the greeters for this meeting. It was a brand new meeting. And immediately that group got us to be a part of business meetings.
                            </p>
                            <p>I had no idea what a business meeting was. And in my mind, at the first business meeting, people were fighting. But what happened is, as soon as it was done, people were laughing and we were there like, let's go get Baskin Robbins ice cream. And I was like, what the hell just happened? But they weren't fighting. It was just people giving opinions and talking about things.
                            </p>
                            <p>And it's because people love AA and they want the input and they were talking about these things called traditions. And the traditions are what keeps groups alive. Keep groups alive and healthy. And traditions typically fall in line when it's more than one alcoholic meeting with each other and have something vital to help others. And the steps were what I was working on with my sponsor on getting me cleaned up to have appropriate reactions and responses to things that were happening in my life and meeting this higher power that I was going to be needing to be dependent upon to help me through those things. So, here I am with service positions on my plate, a bunch of things that I don't want to face and a bunch of meetings to go to in between.
                            </p>
                            <p>And the suggestion for my sponsor was when you're uncomfortable, because I was talking about being uncomfortable to pray. I was like, well, what does that mean? And immediately I thought prayers were supposed to be these prayers that I was going to sit down and ask for an outcome on how I wanted it to turn out. And I was told, no, your prayer just needs to be to take away a feeling. No, your prayer just needs to be to show you the next right thing to do. No, your prayer just needs to be to give you the strength.
                            </p>
                            <p>No, your prayer just needs to be to distract you to something that's helpful to somebody else, not the outcome. So I was like, this sounds really backwards. But all things were pointing to all these things that were problematic and traumatic and hard or whatever it was that was my word that I was learning to figure out to explain things and it required work and effort. So if it required work and effort and I didn't know how to do it, I guess I needed to ask for the strength or I guess I needed to ask for the next right thing to do, or I guess I needed to ask for that distraction to go ahead and pull me away and keep me busy. And when you know it, weird things would happen. And I would go to work and I would think I'd be doing a pretty good job, but because I was talking to people at meetings about going to work after taking some time off, like people in AA would pop up in front of me while I was at work.
                            </p>
                            <p>And as soon as somebody from Alcoholics Anonymous would stand in front of me, I would realize a couple things. My fists were clenched that my jaw was tight, that my shoulders were tight, and that I was, even though acting as if I was completing the next right thing, there was something going on inside of me. And so I would come face to face with a member of Alcoholics Anonymous and something would happen. I would take a deep breath and I would sigh and I would loosen up and immediately completing the next thing in front of me just seemed to be an easier thing to do. But what that showed me is that I wasn't drinking anymore. I was surrounded around you guys.
                            </p>
                            <p>I was attending meetings regularly, but what I really needed to pay attention to was my conduct when I'm not in a meeting with you guys, because those are the vital things that tend to happen. Those are the things that require my response and my reaction to what is happening that I 100% have no control over, walking through life. So a handful of things started happening. You know, when I got sober, it was a regular thing for my cousins and my aunt to do this, like, now you see me, now you don't type behavior. And I would, I would pop up and I would be the fun person or I would cross a line when I was drinking and I would blackout and then drop off. I remember one time my aunt sitting me down and she wanted to get my new address and phone number and she had like three or four pages of addresses and phone numbers that she had.
                            </p>
                            <p>And she was like going through them and finally I was just like, none of those are right. Let me just give you my most recent address and my phone number. And after getting sober, I realized after talking with the sponsor and after coming clean and letting them know and be really being honest with them about my alcoholism. That addiction and alcoholism runs in my family. It's just that thing that people don't talk about. And what I got to find out was that we knew that my uncle was an alcoholic or a heavy drinker or whatever it was when people don't talk about it, like you just assumed that there's a problem.
                            </p>
                            <p>However, what I didn't know is that my aunt was an Allen on warrior, you know, and that all these times that these crazy outbursts would happen during the family, like get togethers or the lessening of people showing up for holiday dinners happened over the years. And us wondering like, God, why does she not react? How is this that she hasn't left him? Why is this that she doesn't like curse him? Why doesn't she ever like throw coffee in his face when he's being a jerk? Like it was because she went to Allen on and she was practicing these things and she was just going on like living her life.
                            </p>
                            <p>And she had a higher power. Like I knew that she was a devout Catholic and all this stuff, but not until I was sober, which were her and I able to talk about her Allen on program and her friends and her Allen on program and how one of her friends didn't understand a higher power so she would call him George. And then she kind of started being able to talk to me about things that like her son and daughter and their children were going through in their addiction with the kids. And we got to kind of talk about how to be a support, but not being involved. And my cousins two kids, like I was able to be an ear more than a relative to them when they had their own turning points and talk to me about their addiction and alcoholism and where it was taking them. Now, although their trajectory didn't lead either of them to long term recovery, the ability to have that connection with them far outweighs any of the cool memories that we had growing up or being like the older cool cousin, the ability to speak with them as an alcoholic heart to heart far outweighs any emotion that I ever had with them leading up until do that.
                            </p>
                            <p>I'm happy to say that dates have been very significant in my recovery and they weren't these calculated things, but they were just things that I knew and things that I used to play upon when I was drinking that like, you know, when my dad's birthday rolls around, you know, it's going to be really hard and that's going to be something to drink over. And I would share these things and it come to find out February 2nd, somebody very incremental in my recovery. She was like, that's my birthday. I was like, huh? So the things are supposed to be really hard. I also get to celebrate somebody else that I really love and that is putting their hand out to me.
                            </p>
                            <p>So that's going to be interesting. It'll be different. And it was, it was different. So then the next birthday, I'm like, oh, no. March 11th, that's my sister's birthday. It's going to be really hard.
                            </p>
                            <p>And so I'm at my sponsor's house and I'm talking with her about it and she was just like, hmm, March 11th and I was like, yeah, she's all back to my birthday. I was like, all right. Well, I guess March 11th scratched off because again, here's somebody I really love and care about. And now they just told me that it's their birthday. And dates have popped up to be very significant, even to this day. My sobriety date is August 30th, 2012.
                            </p>
                            <p>I, you guys were just able to celebrate 10 years and that's phenomenal. My wife's sobriety date, which I, who I met in the rooms of Alcoholics Anonymous, is today. You know? She's that nine years. Then I get to play around with dates and we were married on September 4th, six years ago. And then I'm asked, you know, to speak at Enbore on September 4th and that's pretty cool.
                            </p>
                            <p>You know, there is something else that kind of has happened on my sobriety dates and then this just kind of shows me that my higher power has a twisted sense of humor. And I wouldn't say a sense of humor, but I would say a reminder that like my basis of recovery helps me process and deal with different things because I've been fortunate enough to have the experience of being sober. And that was on my, I want to say my seventh sobriety birthday, maybe my sixth. You know, I get a phone call from my cousin and I'm like, yeah, like they, they remembered my birthday. How nice of them. And it was my cousin, Vicky, and she was just like, I wanted to let you know.
                            </p>
                            <p>Last night my mom passed away. I was like, okay. But the cool thing with that is I 100% know when my dad, my mom, my sister passed away. I was ill equipped to show up and be helpful and not make it about me. I was very much in my disease during those passings and very much because I don't know how to process those emotions. I don't have those coping skills.
                            </p>
                            <p>At that point in time, alcohol probably floated me until, you know, to my bottom when it should have happened because I very much used alcohol as my solution around those things. But this time around, I called my sponsor, then I called my wife and I called my friends and I called my boss. And I was able to take the time off and be available and just say to them, my two cousins, like, let me know what you need my help with in getting the services prepared and anything that you need. And me and my wife were able to go there and be helpful and show up and bring coffee, make decorations, like do whatever, but just show up and be of service. About a year and a half later, I'm at work and I get a phone call from this like random number and phones like pass along to me. And it is a coroner's office from Solano County.
                            </p>
                            <p>And they're like, we're looking for, and they say my cousin's name and I'm like, well, we can't get a hold of her. Do you know where she is? I said, yes, she's in Spain. And they said, well, are you the next relative or you next of kin? And I was like, yes. And I said, we wanted to let you know that her son has died in a car accident and the driver was drinking.
                            </p>
                            <p>It was under the influence. She is arrested at the current moment, but we need to get a hold of her. And I said, okay. And same things. I called my sponsor. I called my wife.
                            </p>
                            <p>I called my boss. And I was like, I need to be able to make this phone call. And the miraculous thing with this is, you know, yes, I delivered very unfortunate news and nothing that anybody wants to hear. But in the passing of my aunt and the passing of my cousin, what I got to witness is other people's higher powers showing up in their life to fill a void or to show them a sense of peace in moments of tragedy. And I also got to understand and relate to the driver that was driving in that car when my cousin passed away. And during the whole proceedings, the court processes and stuff, I know to the court, despite the fact that this tragic event happened, should that driver ever decide that they want to come to the rooms about the Hall of Things and allowing people to have their space to process their loss or grief or whatever is not something that I know how to do on my own accord.
                            </p>
                            <p>It is not something that I know how to allow to happen. Like, I play the director. Like, I want to have these outcomes. I get these great ideas and I feel that I need to be whatever it is. And through Alcoholics and Alamus, those things have shown me that I just need to be able to be helpful. And so that's what I got to extend to my cousin, you know, for her court dates that she needed to make for these weird random things that needed to happen.
                            </p>
                            <p>Either my wife or myself got to show up and drive her to places or to stay the night there or, you know, help clean up and set up tables. And, you know, I had friends too, step up and like so things for like the services. And at one point, this son who she lost, you know, called me up and was just like, you know, I don't know if I want to do this. You know, he played a part in that too. And like she got to make the realation of that on her own, the realisation of that on her own. Like, there was not just one person drinking in that vehicle.
                            </p>
                            <p>They were both drinking in that vehicle. But this was not some off the wall type thing. Like, this is his behaviour and this is who he hung with. But at one point, you know, when things were bad and things were grey and things were dark, he asked to come over to our house and we did that and we took them to a meeting. And there was like, you know, a moment of clarity where like the meeting touched his heart and there were tears and we got to talk openly and honestly that evening. And again, like those are the things that I know make all of this stuff that we do worth something.
                            </p>
                            <p>Her brother, my other cousin, you know, most recently lost their son to the disease of alcohol or to the disease, a disease, you know. He was involved in alcoholics, anonymous, and what I got to see also through the family is that, you know, again, it was something that we didn't talk about, you know. There was shame and guilt in losing this son to his addiction. I had the privilege, and my wife had the privilege of going to visit him in his sober living home. We got to go to a meeting of the Pacific group with him. We got to see who he was hanging with.
                            </p>
                            <p>I just know from my own disease and what I got to see in his is like, things don't change if I don't change the behaviors, you know. Things don't change if I am not ready to work all of the steps. And you know, for me, the honesty and ability to work the steps and to work them thoroughly and to do it all the way through. Like, I only had the capacity to complete what I had when I had it, you know. Like this. .
                            </p>
                            <p>. The ability to have willingness can be fleeting, right? Like, I can be really, really, really willing to have sobriety and then things get better and my life got better and I got things back. And then it was really easy for me before in the past to be like, I'm fixed. I don't have to do anymore, you know. And it was at like one, two, three shuffle.
                            </p>
                            <p>One, two, three shuffle. And I see it now in sobriety. And I don't condemn it. I don't curse it. I can't understand it. It is just certain people's journey to do that.
                            </p>
                            <p>And I'm grateful that I got over that weird hump of whatever it was. And I was willing to go in and do that. And so the loss of my cousin was big. And going to his services and knowing that there was shame and guilt. His parents really not wanting to talk about it when they asked me to speak about it or to speak of him and to pay tribute to him. I was at a crossroads on like what I talked about.
                            </p>
                            <p>What do I talk about? Do I talk about my experience and recovery with him? But yet nobody's really talking about the fact that he had an addiction. Do I just talk about when he was a kid? Am I being dishonest if I choose to just talk about when he was a kid and not the stuff that like really touched my heart about him? And I prayed about it and I talked to my sponsor about it.
                            </p>
                            <p>And the bottom line is like going to this service and paying tribute wasn't necessarily about him. It was about the respect of his parents. They're the ones that just lost their son. And so I talked about when he was a kid and the things that we shared and the sparkle in his eye and the things that I loved. And I honored that and I sat down. What I didn't know is that his parents were going to speak immediately after me.
                            </p>
                            <p>And my wife was able to be there. And which I love because it's just like another person that shows that I'm not lying about this stuff. That like this weird magical stuff really happens. And when we were sitting there, his parents got up. And they said, we prepared this speech last night because we really didn't know what we were going to say, but we wanted to let you guys know. Two days ago on Zoom, Alex's home group, the Pacific group, did a tribute to him on Zoom.
                            </p>
                            <p>And what we got to experience was a meeting in honor of him. And that meeting, we were able to acknowledge that although he was an addict and although that he had a decision, issues, he really wanted to be sober and he was just unable to be willing to do that. And what we were able to witness in that Zoom meeting was that he had a sense of community and he was not alone. And that was our biggest fear as far as his addiction. We did not understand that we could not be his higher power. We did not understand this sense of a higher power, but the fact that he was part of a community and that he had a sponsor and that he sponsored others brings us peace and console that you will never understand.
                            </p>
                            <p>However, sitting in that service, there were at least two people that understood it. And I knew that was myself and my wife. And I didn't have to mention anything about my experience with Alcoholics Anonymous or my experience with meetings. Like this was something that his higher power planted and their higher power planted to be able to speak for us. And that is the miracle. That is where I get to see that I'm a part of something that is way bigger than anything that I could have ever imagined.
                            </p>
                            <p>And it's not just me that self-shily gets to be a part of recovery. It is a lot of other people. However, the only thing that I have the power and my responsibility to perform as a sober member of Alcoholics Anonymous is what you guys ask of me. So in the big book, it asks for me if I want to have one term sobriety, I have to give this away to others. You know, I not only have to have a sponsor on my own because it says in the promises, I cannot transmit something I haven't got. And what I know from time and time and time and time again is I can believe my own BS.
                            </p>
                            <p>Like I will want to come across and tell you my idea of like what you should be doing, but that is not helpful to another alcoholic. My responsibility is to show another alcoholic how to depend upon their relationship with their higher power and the results of their own inventory on how to make decisions to not repeat the past. Not influence them to make decisions on what I think they should do on something that I have no idea is what it's going to turn out like a few weeks from now. But it is my responsibility to pass this on to others. It is also my responsibility to be a part of this fellowship. Being a part of this fellowship does not just mean hanging out with people after a meeting.
                            </p>
                            <p>You know, does not just mean having friends that at one point we might have gone to a treatment program with. And at one point we used to go to meetings, but we don't do it anymore and so now we're friends. Like my part in having a fellowship is to have a home group, to be of service to that group and to reach my hand out to any new members of Alcoholics Anonymous that might come into that meeting. I attend several meetings because I'm just that crazy. I was a 24 hour drinker. So I try and counteract that with the spiritual work that has been put in front of me.
                            </p>
                            <p>The other thing is that when I attend meetings where I participate in activities that should be tradition based. You know, that those groups should be following traditions that we should have business meetings that are in conjunction with traditions and that things get talked about as far as a group conscience and that that is what is decided upon and that the most important voice is the dissenting voice. You know, because that is where people get to open up their mindsets and have a new exposure to something that we may not have thought about, have a discussion about it and come to a conclusion that best serves in Alcoholics still suffering. So I do that. And in that and sponsoring others. I ask them to do the same.
                            </p>
                            <p>They are to have sponsors, you know, they are to pass along what has been freely given to them. They are to have a home group. They are to be in service meetings or activities that we have within the area conferences, whatever it may be. And that, you know, we get to talk about traditions and steps and be able to figure out like how to show up as best versions of ourselves and. And not. Not be who we were while we were drinking, you know, the ability to do this is and stick with it.
                            </p>
                            <p>It has been easy for me, I guess, at this point in time. It's a lot of work, but the alternate because of how low it was when I got here has been something that hasn't crossed my mind that I don't need to be doing. It is not effortless, you know, sometimes like I've thought over time, like I really don't want to stay after the meeting to be a part of that business meeting. You know, I'd rather go home and get some extra sleep. I've thought at times like, man, meeting with the sponsor is pretty inconvenient. You know, I'd rather be doing blah, blah, blah.
                            </p>
                            <p>But if I commit a time and we plan it out, like I have to make room for my recovery. There have been some crazy things that continue to happen on certain dates, you know, most recently today. I was part of a meeting that I normally attend, like the day before my 10th birthday. I got to hear a newcomer talk about like having like, you know, a day of recovery and talking about exactly how I felt the day before I got sober. Like she conveyed in those words exactly how I was feeling the day before I got sober. And I would have missed that had I not been a part.
                            </p>
                            <p>On my 10th birthday, I woke up and I was like, hey, God, like show me what you want me to do, like in my 11th year, you know, almost in a cocky fashion and a little bit when I think of it. And by four o'clock in the afternoon, I got a call from my boss and he was like, hey, I just wanted to let you know we're closing your store. I was like, okay. And, you know what? This news is not traumatic. It is not devastating.
                            </p>
                            <p>It is not anything like I worked for a corporation. Like this isn't anything of my doing like who I am as an employee is nothing like how I was drinking. I can tell you guys, I'm a hard worker. I have integrity. I like am willing to learn things. I execute.
                            </p>
                            <p>I know I can hold my staff accountable. Like none of this stuff has anything to do with me. Like this is completely what has just been put in front of me and what I need to react and respond to you in a professional way in a way that's aligned with my higher power. And so a new career opportunity, whatever it may be, that's cool, but it doesn't happen without work. You know, so I got a refresher resume. So I'm going to have to go on interview.
                            </p>
                            <p>So I'm going to have to apply for jobs because last time I checked, last time I went to a meeting, nobody talked about somebody knocking on their door saying that they wanted to give them employment. Like that is not how it works. Like it is going to require me to do some footwork to see what God has in store for me. And that is fine. I know that in having service positions in different meetings and functions of alcoholics and honors that I've been able to serve in, I've always walked away with the skill set. The ability to work with others and ability to better communicate and ability to better organize and ability to have a collective consideration on how things will be executed.
                            </p>
                            <p>And the ability to show empathy. And those are things that I do not have or am able to tap into on my own. I believe I've had them. I just cannot channel them or exert them on my own. I get the ability to do so by being a member of Alcoholics Anonymous and doing what you guys say and enjoying the experience around that. Today, with my wife having nine years of recovery, in our family, we have 70 years of sobriety.
                            </p>
                            <p>I have a father-in-law who's got 33 years. I have a sister-in-law who has 18 years. My wife Jessica has nine years and I have 10 years. It is 70 years of recovery. And despite all the hardships or losses or heartbreak around the inability for those that I've loved to get sobriety, I know that I have it. And it is my responsibility to give it away and to you to learn from you.
                            </p>
                            <p>So with that, I will close. Thank you very much.
                            </p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <?php include_once 'footer.inc' ?>
    </body>

    </html>