<!-- start

<div class="row box">
    <div class="col-lg-12 col-sm-12 col-12 box-1">
        <div class="row box border border-warning bg-light">
            <h3>FRIDAY NIGHT, September 2</h3><br>
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-sm">
                    <tbody>
                        <tr>
                            <th scope="row">8:00 P.M. (PDT)</th>
                            <td colspan="2"><em class="fa fa-video-camera float-left"> </em>AA ZOOM MEETING</td>
                            <th><strong>Reggie W., Los Angeles, CA</strong></th>
                        <tr>
                            <th scope="row"></th>
                            <td colspan="2"></td>
                            <th></th>

                        </tr>
                        </tr>
                        <tr>
                            <th scope="row">50/50 Raffle</th>
                            <td colspan="2"><strong>Zoom Meeting ID</strong>: 851-8969-3046</td>
                            <th><strong><strong>Zoom Meeting Password</strong>: 338999</strong></th>

                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-sm-12 col-12 box-1">
        <div class="row box border border-success bg-light">
            <h3>Saturday, September 3</h3>
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-sm">
                    <tbody>
                        <tr>
                            <th scope="row">8:00 AM.</th>
                            <td colspan="2">Registration Opens</td>
                            <th></th>
                        </tr>
                        <tr>
                            <th scope="row">9:00 AM.</th>
                            <td colspan="2">Al-Anon Marathon Meetings (English/Spanish)</td>
                            <th></th>
                        </tr>
                        <tr class="table-success">
                            <th scope="row">10:00 AM.</th>
                            <td colspan="2">Kick-Off AA Meeting </td>
                            <td>Speaker:<b> Arthur T., Carmel, CA</b><br>
                                <audio controls>
                                    <source src="conference_2o22/audio2022/Arthur_T-From-Carmel/ArthurTFromCarmelCA-MBAR2022-09-03-22_01.ogg" type="audio/ogg">
                                    <source src="conference_2o22/audio2022/Arthur_T-From-Carmel/ArthurTFromCarmelCA-MBAR2022-09-03-22_01.wav" type="audio/wav">
                                    <source src="conference_2o22/audio2022/Arthur_T-From-Carmel/ArthurTFromCarmelCA-MBAR2022-09-03-22.mp3" type="audio/mpeg">
                                    Your browser does not support the audio element.
                                </audio>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">10:00 AM.</th>
                            <td colspan="2"> AA Meeting Spanish Speaking</td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">11:00 AM</th>
                            <td colspan="2">AA Marathon Meetings Begin</td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">11:30 AM.</th>
                            <td colspan="2">AA Old Timers' Panel</td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row"></th>
                            <td colspan="2"></td>
                            <td></td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row">2:00 PM.</th>
                            <td colspan="2">AA/Al-Anon Speaker Meeting</td>
                            <td><b>Al-Anon Speaker: Mary N., Orange, CA <br> AA Speaker: Guillermo N., Orange, CA</b>

                                <audio controls>
                                    <source src="conference_2o22/audio2022/Mary-N_(Al-Anon)_Guillermo-N/Mary-N_(Al-Anon)_Guillermo-N.ogg" type="audio/ogg">
                                    <source src="conference_2o22/audio2022/Mary-N_(Al-Anon)_Guillermo-N/Mary-N_(Al-Anon)_Guillermo-N.mp3" type="audio/mpeg">
                                    <source src="conference_2o22/audio2022/Mary-N_(Al-Anon)_Guillermo-N/Mary-N_(Al-Anon)_Guillermo-N.wav" type="audio/wav">
                                    Your browser does not support the audio element.
                                </audio>
                                <br>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">5:00 PM.</th>
                            <td colspan="2">Meet the Speakers Dinner</td>
                            <td>(! @ Bethlehem Lutheran Church) ∆</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row">7:30 PM. </th>
                            <td colspan="2">AA Speaker Meeting </td>
                            <td>Speaker: <b>Rocky S., Phoenix, AZ</b><br>
                                <audio controls>
                                    <source src="conference_2o22/audio2022/Rocky-S_From Phoenix/Rocky S_From_PhoenixAZ-MBAR 2022.ogg" type="audio/ogg">
                                    <source src="conference_2o22/audio2022/Rocky-S_From Phoenix/Rocky S_From_PhoenixAZ-MBAR 2022.mp3" type="audio/mpeg">
                                    <source src="conference_2o22/audio2022/Rocky-S_From Phoenix/Rocky S_From_PhoenixAZ-MBAR 2022.mp3" type="audio/mpeg">
                                    Your browser does not support the audio element.
                                </audio>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">8:30 PM. </th>
                            <td colspan="2">Prize Raffle and 50/50 drawing</td>
                            <td>(immediately following speaker meeting)</td>
                        </tr>
                        <tr>
                            <th scope="row">9:30 PM. </th>
                            <td colspan="2">Dance </td>
                            <td>(immediately following raffle)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-sm-12 col-12 box-1">
        <div class="row box border border-primary bg-light">
            <h3>Sunday, September 4</h3>
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-sm">
                    <tbody>
                        <tr>
                            <th scope="row">8:00 AM.</th>
                            <td colspan="2">Continental Round-Up Breakfast</td>
                            <th>(! Bethlehem Lutheran Church) ∆</th>

                        </tr>
                        <tr>
                            <th scope="row">8:00 AM.</th>
                            <td colspan="2">AA Marathon Meetings Begin</td>
                            <th></th>
                        </tr>
                        <tr>
                            <th scope="row">9:00 AM.</th>
                            <td colspan="2">Al-Anon Marathon Meetings (English/Spanish)</td>
                            <th></th>
                        </tr>
                        <tr>
                            <th scope="row">10:00 AM.</th>
                            <td colspan="2">AA Spanish Speaking Meeting </td>
                            <td><b> </b></td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row">11:00 AM.</th>
                            <td colspan="2">Al-Anon Speaker Meeting </td>
                            <td><strong>Al-Anon Speaker: Robin K. Marina, CA <br>Al-Anon Speaker: Terril K. Marina, CA</strong>
                                <audio controls>
                                    <source src="conference_2o22/audio2022/Al-Anon_Speaker_Meeting-Robin K_Terrill-K/Al-Anon-Speaker-Meeting_Robin-K_Terrill-K_01.ogg" type="audio/ogg">
                                    <source src="conference_2o22/audio2022/Al-Anon_Speaker_Meeting-Robin K_Terrill-K/Al-Anon-Speaker-Meeting_Robin-K_Terrill-K.mp3" type="audio/mpeg">
                                    <source src="conference_2o22/audio2022/Al-Anon_Speaker_Meeting-Robin K_Terrill-K/Al-Anon-Speaker-Meeting_Robin-K_Terrill-K_01.wav" type="audio/wav">
                                    Your browser does not support the audio element.
                                </audio>
                            </td>
                        </tr>
                        <td><br></td>
                        <tr class="table-success border border-dark">
                            <th scope="row">1:30 AM.</th>
                            <td colspan="2">Al-Anon Family Panel</td>
                            <td><b>Al Anon Family Panel: Michele M / Pete-C Dawn-C / Joe-P</b><br>
                                <audio controls>
                                    <source src="conference_2o22/audio2022/Al-Anon_Family_Panel-Michele-M_Pete-C_Dawn-C_Joe-P/Al-Anon_Family_Panel-Michele-M_Pete-C_Dawn-C_Joe-P_01.ogg" type="audio/ogg">
                                    <source src="conference_2o22/audio2022/Al-Anon_Family_Panel-Michele-M_Pete-C_Dawn-C_Joe-P/Al-Anon_Family_Panel-Michele-M_Pete-C_Dawn-C_Joe-P.mp3" type="audio/mpeg">
                                    <source src="conference_2o22/audio2022/Al-Anon_Family_Panel-Michele-M_Pete-C_Dawn-C_Joe-P/Al-Anon_Family_Panel-Michele-M_Pete-C_Dawn-C_Joe-P_01.wav" type="audio/wav">
                                    Your browser does not support the audio element.
                                </audio>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">3:00 PM</th>
                            <td colspan="2">Ice Cream Social</td>
                            <td><strong>(2nd Floor Terrace)</strong></td>
                        </tr>
                        <tr class="table-success border border-dark">
                            <th scope="row">5:00 PM.</th>
                            <td colspan="2">AA Speaker Meeting Speaker</td>
                            <td><b>Chris T., Del Rey Oaks, CA</b><br>
                                <audio controls>
                                    <source src="conference_2o22/audio2022/Chris-T_From-Del-Rey-Oaks/Chris-T_From-Del-Rey-Oaks_01.ogg" type="audio/ogg">
                                    <source src="conference_2o22/audio2022/Chris-T_From-Del-Rey-Oaks/Chris-T_From-Del-Rey-Oaks.mp3" type="audio/mpeg">
                                    <source src="conference_2o22/audio2022/Chris-T_From-Del-Rey-Oaks/Chris-T_From-Del-Rey-Oaks_01.wav" type="audio/wav">
                                    Your browser does not support the audio element.
                                </audio>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">6:30 PM.</th>
                            <td colspan="2">Raffle drawing</td>
                            <td>(immediately following speaker meeting)</td>
                        </tr>

                        <tr>
                            <th scope="row">8:00 PM. </th>
                            <td colspan="2">Fellowship and Music</td>
                            <td>(immediately following raffle)</td>
                        </tr>
                        <tr>
                            <th scope="row">9:00 PM. </th>
                            <td colspan="2">Conference Ends</td>
                            <td></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-12 col-xl-12">
        <a href="registration.php" class="btn btn-light btn-lg active" role="button" aria-pressed="true"><img src="photo-logo/ButtonReg.png" width="300" alt="" /></a>
        <br><br>
        <hr />
        <p>CHECK IN AT REGISTRATION DESK TO OBTAIN YOUR REGISTRATION PACKET CONTAINING YOUR NAME BADGE,
            PROGRAM, LIST OF ALL MARATHON MEETING TIMES, AND ANY TICKETS FOR MEALS OR EVENTS YOU MAY HAVE PURCHASED.
            <br><br>
            FOR MORE INFORMATION WHILE AT THE EVENT,
            QUESTIONS CONCERNING THE EVENT, OR LOST AND FOUND ITEMS,
            PLEASE GO TO THE REGISTRATION DESK.
            <br><br>
            Δ Location of Event is different than conference site<br><br>
            <b>HOST OF MBAR 2022:</b> May H. MBAR STEERING COMMITTEE<br>
            <b>Chairperson:</b> Cindy A. <b>Co-Chair:</b> Phil C.<br>
            <b>Treasurer:</b> Daylene A. <b>Co-Treasurer:</b> Mona S.
        </p>
        <hr>
        <p>See our local AA Central Office website
            <a href="" onclick="window.open('https://www.aamonterey.org/', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;"> www.aamonterey.org</a> for a current listing of meetings in the area.
        </p>
    </div>
</div>
<div class="row box">
    <br>
    <div class="col-sm-11 col-12">
        <h3><a href="services.php">Conference info: KEEP IT SIMPLE</a></h3>
    </div>
    <br>
    <p><strong>Check in at the registration table</strong> to obtain your registration packets containing your name badges, programs and any tickets for meals or the dance which you may have purchased.
    </p>

    <p><strong>Shuttle service will be available</strong> to drive from the conference center to the Bethlehem Lutheran church for the Saturday morning breakfast and the Saturday evening meet the speakers dinner. go to registration desk for more information about this complimentary service.
    </p>
    <p>Frequent contact with newcomers and with each other is the bright spot of our lives. Big Book Pg. 89.<br>
        <br>
        It is a fellowship in Alcoholics Anonymous. There you will find release from care, boredom and worry. Your imagination will be fired. Life will mean something at last. The most satisfactory years of your existence lie ahead. Thus we find the fellowship, and so will you. Big Book Pg. 152
    </p>
</div>
</div>
    end -->