<footer class='container'>
    <div class="row justify-content-md-center">
        <div class='col-sm-auto banner'>
            <img src="../images/mbar_logo.png" class="img-fluid rounded-top" alt="Monterey Bay Are Roundup 2024 logo with a breeched whale tail and the slogan: Keep it simple" />
        </div>
        <div class='col-sm-auto'>
            <p id='statement'>
                    Our Statement of Responsibility:<br><br>
                    I am responsible.<br>
                    When anyone, anywhere, reaches out for help, I want the hand of A.A. always to be there.<br>
                    And for that I am responsible.
            </p>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-sm shadow text-center">
            <hr><hr>
            <h3 class="text-center"><strong>Join <a href="https://www.facebook.com/groups/MBAR2021/">
            <img src="../images/facebook_logo.png" width="40" alt="Facebook logo for private AA members."></a> Private Group</strong></h3>
            <hr><hr>
        </div>
    </div>
</footer>