<!-- Part Registration -->
<article aria-label="registration info and link">
    <div class="container shadow-wrap">
        <div class="row justify-content-center mb-5">
            <div class="col-xl-8 col-lg-8 col-md-12 py-4">
                <div class="p-3 text-center text-bg-light hero-text-border" title="Join us in 2026!">
                    <h3 class="fw-bold px-3 px-md-0">MBAR 2026 on Labor Day weekend!</h3>
                    <p class="h3 text-dark">Virtual Kick-Off Zoom Meeting</p>
                    <p class="text-dark">August 28th at 8:00pm PDT
                        <br>
                        This meeting is open to everyone, and we encourage you to join!
                    </p>
                    <p class="h3 text-dark">In-Person Meetings</p>
                    <p class="text-dark">August 29th and August 30th at the Monterey Conference Center
                        <br>
                        Please note that registration is required for the in-person event.
                    </p>
                    <p class="text-dark mb-6">We look forward to seeing you then!</p>
                </div>
            </div>
        </div>
    </div>
</article>

<a href="#toTop" class="btn btn-primary back-to-top" id="back-to-top-link" title="Back to Top" aria-label="Back to Top"><i class="bi bi-arrow-up" aria-hidden="true"></i></a>

</main>

<div class='container top-footer'>
    <aside aria-label="responsibility statement">
        <div class="row justify-content-md-center">
            <div class='col-sm-4 banner'>
                <img src="../images/mbar_logo.png" class="img-fluid rounded-top" alt="Monterey Bay Area Roundup 2024 logo with a breeched whale tail and the slogan: Keep it simple">
            </div>
            <div class='col-sm-8 col-md-6 p-4'>
                <h4>Our Statement of Responsibility:</h4>
                <p class="h4">I am responsible.<br>
                    When anyone, anywhere, reaches out for help, I want the hand of A.A. always to be there.<br>
                    And for that I am responsible.
                </p>
            </div>
        </div>
    </aside>

    <aside aria-label="private facebook group">
        <div class="row justify-content-md-center">
            <div class="col-sm-12 col-md-10 shadow text-center">
                <hr>
                <h4 class="text-center"><strong>Join <a href="https://www.facebook.com/groups/MBAR2021/" target="_blank" rel="noopener noreferrer nofollow">
                            <img src="../images/facebook_logo.png" width="40" alt="Facebook logo for private group of AA members."><span class="sr-only">(Opens a new window)</span></a> Private Group</strong></h4>
                <hr>
            </div>
        </div>
    </aside>
</div>

<footer>
    <div class='container'>
        <div class="row justify-content-md-center">
            <div class="col-sm-12" id="footer-image" role=img aria-label="A road through rolling hills, covered with flowers, with a sunset backdrop.">
                <p>Copyright © <?php echo date('Y'); ?> Monterey Bay Area Roundup. All Rights Reserved.
                </p>
            </div>
            <nav class="navbar navbar-expand-sm bg-dark border-bottom border-body" data-bs-theme="dark" aria-label="footer menu">
                <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link nav-link-size" href="accessibility.php">Site Accessibility</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-size" href="privacy-policy.php">Privacy Policy</a>
                    </li>
                    <li class="nav-item" style="border-right: none;">
                        <a class="nav-link nav-link-size" href="sitemap.php">Site Map</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</footer>

<!-- Bootstrap JavaScript Libraries -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

<script src="../js/backToTop.js"></script>