<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-CF8R56VR9S"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-CF8R56VR9S');
    </script>

    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Monterey Bay Area Roundup 2024</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">

    <!-- Bootstrap CSS v5.3.2 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">

    <link rel="stylesheet" type="text/css" href='./css/styles.css'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <!-- reCAPTCHA widget -->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>


    <!-- https://datatables.net/ -->
    <link href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet">

</head>

<body id="toTop">
    <a href="#main-content" class="btn btn-primary btn-skip" aria-label="Go To Main Content">Go To Main Content</a>
    <header class='container' role="banner">
        <div class="row justify-content-md-center pt-5 pb-3">
            <div class='col-sm-4 banner'>
                <h1 class="text-uppercase">Monterey Bay Area Roundup</h1>
                <p>P.O. Box 1462<br>Monterey, CA 93942</p>
                <p class="font-italic">To watch people recover, to see them help others, to watch loneliness vanish, to see a fellowship grow up about you, to have a host of friends — this is an experience you must not miss.</p>
            </div>
            <div class='col-sm-auto banner'>
                <img src="../images/mbar_logo.png" class="img-fluid shadow-wrap" alt="Monterey Bay Area Roundup 2024 logo with a breeched whale tail and the slogan: Keep It Simple." title="Monterey Bay Area Roundup 2024 logo with a breeched whale tail and the slogan: Keep It Simple.">
            </div>
        </div>
    </header>