<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Monterey Bay Area Roundup 2024</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">

    <!-- Bootstrap CSS v5.3.2 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">

    <link rel="stylesheet" type="text/css" href='./css/styles.css' />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <!-- reCAPTCHA widget --->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>


    <!-- https://datatables.net/ -->
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>

</head>

<body>
    <header class='container'>
        <div class="row justify-content-md-center pt-5 pb-3">
            <div class='col-sm-4 banner'>
                <h1>MONTEREY BAY AREA ROUNDUP</h1>
                <p>P.O. Box 1462<br>Monterey, CA 93942</p>
                <p class="font-italic">To watch people recover, to see them help others, to watch loneliness vanish, to see a fellowship grow up about you, to have a host of friends — this is an experience you must not miss.</p>
            </div>
            <div class='col-sm-auto banner'>
                <img src="../images/mbar_logo.png" class="img-fluid shadow-wrap" alt="Monterey Bay Area Roundup 2024 logo with a breeched whale tail and the slogan: Keep It Simple" title="Great drawing by Micha C." />

            </div>
        </div>
    </header>