<div id="april2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            MBAR 2024 Committee Notes
            <br>Zoom ID 831 4306 2293 Password 2024
            <br>Saturday April 13, 2024 at 10am
            <br><a href='/' class="bb-link">montereybayarearoundup.org</a>
        </p>

        

        <p> Attendees: </p>

    </div>
</div>