<div id="february2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            MBAR 2024 Committee Notes
            <br>Zoom ID 831 4306 2293 Password 2024
            <br>Saturday February 10, 2024 at 10am
            <br><a href='/' class="bb-link">montereybayarearoundup.org</a>
        </p>

        <dl>
            <dt>1. Chairperson's Call to Order: 10am;</dt>

            <dt>2. Reading of the 12 Traditions: Jean;</dt>

            <dt>3. New attendees, put your phone numbers and email addresses in the chat: Joanie: Al-Anon;</dt>

            <dt>4. Are there any A.A. or Al-Anon anniversaries since our last meeting? None;</dt>

            <dt>5. Approve/Amend Minutes from the last meeting: Approved;</dt>

            <dt>6. Chairperson's Report - Chris T.: Thank you all so much for your attendance service and support of the January Bingo event, it was a <span class="text-uppercase">huge</span> success and made an impression on so many in our Fellowship that attended their very 1st Sober event. It was so much <span class="text-uppercase">fun</span> and I could not be more grateful to all those that I get to be in service and work with.
                <br><br>
                We have T-Shirts to decide upon in this meeting. Phillip has created a Zoom poll that we will use to aid us in this important decision.
                <br><br>We also have a consideration for coffee to be available at the conference and we have provided a rough estimate of cost should this be something we may decide as a committee to offer.
                <br><br>
                Our conference is a little less than seven months away so the focus and attention to these items within this meeting is very much appreciated.
                <br><br>
                We are needing the following chairs filled: Events, Outreach - Conor and Rick, and Marathon Meetings - possibly Mark.
            </dt>

            <dt>7. Treasurer's Report - Carolyn, Jean T: Current balance $22,154.25 includes registrations, bingo, etc.; Carolyn/Phillip discussed domain renewal; </dt>

            <dt>8. Seventh Tradition: You can make a 7th Tradition contribution - PayPal at mbartreasurer@gmail.com or by sending a check to - MBAR, PO Box 1462, Monterey, CA 93942; Or Venmo: @MBARoundup24 (<em>Note:</em> Venmo and check go 100% to Treasury, PayPal collects a fee.)</dt>

            <dt>9. Committee Chairs/Steering Committee Reports</dt>

            <dd>a. Media - Gina: St. Patrick's and Bingo fliers distributed on Facebook and printed copies were distributed;</dd>

            <dd>b. Registration - Naomi: Ten registrations received; Working on online registration process;</dd>

            <dd>c. Spanish - Robert: Meet last Wednesday of the month (potluck); Need Spanish translation of registration form - Rene to get translation made; 28 Spanish Groups; Working on speakers from Texas and Mexico;</dd>

            <dd>d. Al-Anon - Dawn: Start meetings next month; Committees assembled;</dd>

            <dd>e. T-Shirt - Kevin: See polling below; Recommended committee t-shirts be a different color; Consider travel mugs, water bottles, ball caps, etc.;</dd>

            <dd>f. I.G.R. / G.S.R. - Cole: Announcing MBAR at committee meetings;</dd>

            <dd>g. Facilities - Sally: No report;</dd>

            <dd>h. Website - Phillip: New website is accessible (ADA); Working on registration - Money to treasurer and Registration form to registration chair; Resolve process for marking registrations as paid – coordinate with Carolyn and Naomi; Address domain renewal; Robert check Spanish page on website; Rene coordinate Spanish translation; Needs digital copies of Spanish translation;</dd>

            <dd>i. Raffle - Katherine: Chris needs volunteers to help with raffle at St. Patrick's Day; Add committee for St Patrick's day - Collect money for meals: Joanie and Chris;</dd>

            <dt>10. Old Business:</dt>
            <dt>Fundraising Ideas</dt>

            <dd>a. Recap January "B-I-N-G-O": Moose Lodge Friday 1/26/24, 6 to 9pm; 50/50 Raffle and donated raffle prizes; Speaker: Elena B; Bingo Game Master; Photo Boot was a success; Volunteers: Volunteers: Food (3) Entry (3) Raffle (2) 7th tradition (2 to 3); Food - contributed - receipts saved; Total income $3,199.25 - Carolyn provide details in March; Make provisions to take 50/50 contributions by Venmo;</dd>

            <dd>b. Saint Patty Day, Sun 3/17 - not discussed; Site - Moose Lodge or Phil's Pool House; Phil see if house is available; Time 4pm to 7pm; Speaker; Food - Chris reach out to potential cooks; Raffle;</dd>

            <dt>T-shirt poll about the style and color of the MBAR t-shirts</dt>

            <dd>a. Style: Short sleeve, Long sleeve, Baseball style; Color Options: Teal, Royal Blue, Navy Blue, White and Black; Final results: General MBAR T-shirts winner - Short Sleeve, $15, and Navy Blue; Committee T-shirts - Jersey, white and blue; Kevin bring samples in March; New poll next month to finalize t-shirt design; Jean bring sample t-shirts from past MBARs;</dd>

            <dt>11. New Business:</dt>
            <dt>Coffee Provided at MBAR 2024: </dt>
            <dd>a. Monterey Conference Center coffee service - One Gallon of coffee or tea service (16 cups at 8oz.) equals $80; With Tax and Gratuity - $108.75; 100 people - AM coffee: 5 to 6 gallons regular coffee and 2 gallons tea; PM coffee: four gallons (coffee and tea); Total: approx. 12 gallons for the day; (This is estimating that almost everyone would at least have one cup, and little less than half of the people would have two cups for the entire day.); Coffee at 50 gallons per day would be $5,437.50 per day; 500 people would be 60 gallons per day; Total: $6,525.00 per day; For two days, approx. $10,000 for coffee; When we reach that amount, we remove the coffee; That would be approx. 92 gallons for the two days;</dd>

            <dt>12. Next Steering Committee meeting is Tuesday 2/27/2024 at 6pm via Zoom;</dt>

            <dt>13. Next Committee meeting is Saturday 3/9/2024 at 10am;</dt>

            <dt>14. Meeting adjourned at 11:15am with the Serenity Prayer;</dt>
        </dl>

        <p> Attendees: Carolyn, Chris, Cole, Dawn, Gina, Jane;g. Janet, Jean, Joanie, Kathleen, Kevin, Mary Grace, Naomi, Phil, Phillip, Renee, Robert, and Roger;</p>

    </div>
</div>