<div class="accordion-item">
    <h4 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
            <i class="bi bi-book me-2" style="font-size: 1.5rem; color: var(--color-8);" aria-hidden="true"></i><strong>2022</strong>
        </button>
    </h4>
    <div id="flush-collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body d-grid gap-3">

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/12-10-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 12/10/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/11-12-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 11/12/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/10-8-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 10/08/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/9-24-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 09/24/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/8-27-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 08/27/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/8-20-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 08/20/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/8-13-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 08/13/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/8-6-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 08/06/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/7-9-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 07/09/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/6-11-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 06/11/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/5-14-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 05/14/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/4-9-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 04/09/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/3-12-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 03/12/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/2-12-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 02/12/2022</button>

            <button type="button" class="btn btn-outline-primary btn-sm" onclick="window.open('../pdf/2022/1-8-22.pdf', 'Sage200Demo', 'width=900,height=768,status=0,resizable=0');return false;">Opens a PDF: 01/08/2022</button>
        </div>
    </div>
</div>