<div id="june2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            MBAR 2024 Committee Notes
            <br>Zoom ID 831 4306 2293 Password 2024
            <br>Saturday June 8, 2024 at 10am
            <br><a href='/' class="bb-link">montereybayarearoundup.org</a>
        </p>

        <dl>
            <dt>1. Chairperson's Call to Order: 10am;</dt>

            <dt>2. Reading of the 12 Traditions: Jean;</dt>

            <dt>3. New attendees, put your phone numbers and email addresses in the chat: None;</dt>

            <dt>4. Are there any A.A. or Al-Anon anniversaries since our last meeting? Katherine 14 years, Carolyn 25 years, Mary Grace 45 years, Cole 37 years, and Robert 16 years;</dt>

            <dt>5. Approve/Amend Minutes from the last meeting: Approved with revisions;</dt>

            <dt>6. Chairperson's Report - Chris T.: Thank you all for your continued support and attendance for our planning meeting!! I am so looking forward to the committee reports and the re-cap of what the sub-committee was able to secure for T-shirts, as well as a few items needing attention and support from the entire committee in the next few months as MBAR 2024 is quickly approaching.
                <br><br>
                As discussed and voted upon last meeting this meeting will be 1.5 hours and as we embark upon several tasks at hand as committee chairs will be needing to come together and ensure that we have the support of the committee to ensure these tasks can be executed to the best of our ability,
                <br><br>
                Please be mindful of items the committee has already voted upon and the work of subcommittees to keep within our allotted time and allow for all committee chairs to give their reports that may outline where we need to direct our focus and attention.
                <br><br>
                All Committee Chairs in the Spirit of Rotation please be looking to have your predecessor found and join us in our meetings so they have some MBAR experience! MBAR Chair Positions are to be Rotated and fulfilled by members to increase their ability to practice and uphold Traditions and increase their Spiritual Experience by working and playing with members New and Old.
                <br><br>
                We are needing the following chairs filled: Facilities Chair; Shuttle - Per Cindy A; MBAR 2022 Trevor F.; MBAR 2019 (and helped in 2022) Shuttle Service Chair Chuck N.; Please see attached Committee Chair List
            </dt>

            <dt>7. Treasurer's Report - Carolyn H.: See attached budget spreadsheet; 65 registrations received; Insurance paid; 15 Conference T-shirts; 20 Committee T-shirts; Bank Balance $27,726; Registered - Missing payments saying they'd pay with PayPal: , Molly M., Kerry M., Chris L., Tom L., Sherri M., Brenda S., and Earl W.
            </dt>

            <dt>8. Seventh Tradition: You can make a 7th Tradition contribution - PayPal at mbartreasurer@gmail.com or by sending a check to - MBAR, PO Box 1462, Monterey, CA 93942; Or Venmo: @MBARoundup24 (<em>Note:</em> Venmo and check go 100% to Treasury, PayPal collects a fee.)</dt>

            <dt>9. Committee Chairs/Steering Committee Reports</dt>

            <dd>a. Media - Gina, Sean: Apology did not send out text reminder for the meeting - she will do it next month;</dd>

            <dd>b. Registration - Naomi: 71 total registrations received - 41 online 21 paper, 9 not paid, 40 AA / 12 Al-Anon / 12 Others, No Spanish registrations, 62 'Bundles'; Logistics for T-shirts - Naomi issue a ticket, Kevin hand out t-shirts; Cindy provide a report next month - count of pre-registrations received in previous years; Arthur pointed out some issues with online registration form - Jean contact Phillip; Chris / Renee / Jean working on Program - forward their work to Naomi;</dd>

            <dd>c. Spanish - Robert: Meeting regularly - Sundays and last Wednesday of the month; Vote on speakers tomorrow;</dd>

            <dd>d. Al-Anon - Jane: Speakers selected coordinating with Kathleen; Filling-up marathon meetings; Jane email committee list and agenda for the program;</dd>

            <dd>e. T-Shirt - Kevin: Shared invoice for 240 T-shirts - The basis for pricing T-shirts at $15; Extensive discussion about the logistics of purchasing T-shirts; Must pre-order by 7/30/2024;
                <br><br>
                Motions Proposed and Passed - Finalize price for all attendee t-shirts at $15; Don't purchase any attendee t-shirts until the full committee approves the purchase; Use fund raising income for costs related to budgeted items where needed; Create agenda item to discuss fund raising surplus and how to use it; Committee chairs present revised budget by 7/1/2024 requesting any changes to funding by 7/1/2024;
                <br><br>
                Committee t-shirts; $16.00 + 10% tax; Planning on ; 18 mugs - cost $19.82, sell for $20; 36 water bottles - cost $11+, sell for $12; Samantha wants some merchandise for event prizes;
            </dd>

            <dd>f. Speaker - Kathleen: Jean presented preliminary program created by steering committee; Naomi pointed out the speaker selection should be done by the speaker committee not the steering committee; Naomi & Samantha offered to help Kathleen; Naomi pointed out that the kick-off speaker is typically selected by the whole committee and has been an active MBAR committee member - Chris will add to July agenda;</dd>

            <dd>g. Outreach - Conor: No report;</dd>

            <dd>h. Events - Samantha: Insurance secured; Potential Events for MBAR;</dd>

            <dd>i. I.G.R. / G.S.R. - Cole: No report;</dd>

            <dd>j. Marathon Meetings - Mark: No report;</dd>

            <dd>k. Facilities- Sally: No report;</dd>

            <dd>l. Website - Phillip: No report;</dd>

            <dd>m. Raffle - Katherine: Has people lined up to help - Cole: Separate committee members for 50-50 raffle; Motion proposed ticket pricing (raffle & 50/50), passed - 1 Ticket $1, 6 Tickets $5, 12 Tickets $10, 25 Tickets $20;</dd>

            <dt>10. Old Business:</dt>

            <dd>a. Reminder Committee Members should all be registered, within the next month;</dd>

            <dd>b. Non-Profit Status: Committee Members please announce we are needing assistance with this. Chris followed up with Jana to have this be an IGR announcement as well; Motion passed - pay for professional to do non-profit application; Rene & Cindy volunteered to be liaison;</dd>

            <dt>11. Fundraising Ideas</dt>

            <dd>a. Unity Day Presence: 6/9/2024 - Have table and tent - Need volunteers;</dd>

            <dd>b. Birthday Meeting Presence: May 25th, June 29th, July 27th, and Aug 31st - Need volunteers;</dd>

            <dd>c. Softball Event: 7/6/24 - Dampierre Little League Park, Carmel Valley, TC Coordinating - Need volunteers;</dd>

            <dt>12. New Business: None;</dt>

            <dt>13. Next Steering Committee meeting is Tuesday 06/25/2024 at 6pm via Zoom;</dt>

            <dt>14. Next Committee meeting is Saturday 07/13/2024 at 10am;</dt>

            <dt>15. Meeting adjourned at 11:35am with the Serenity Prayer;</dt>
        </dl>

        <p> Attendees: Arthur, Carolyn, Chris, Cindy, Cole, Gina, Jane, Janet, Jean, Kathleen S., Kathleen F., Katie, Kevin, Mary Grace, May, Naomi, Phil, Renee, Robert, Roger, and Samantha</p>

    </div>
</div>