<div class="accordion-item">
    <h4 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFive" aria-expanded="false" aria-controls="flush-collapseFive">
            <i class="bi bi-book me-2" style="font-size: 1.5rem; color: var(--color-8);" aria-hidden="true"></i><strong>2024</strong>
        </button>
    </h4>
    <div id="flush-collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body d-grid gap-3">

            <div class="accordion accordion-flush" id="accordion2024">

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#november2024" aria-expanded="false" aria-controls="november2024">November 9th</button>
                    </h4>

                    <?php include_once 'meeting-2024-11.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#september2024" aria-expanded="false" aria-controls="september2024">September 28th</button>
                    </h4>

                    <?php include_once 'meeting-2024-09.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#august-17-2024" aria-expanded="false" aria-controls="august2024">August 17th</button>
                    </h4>

                    <?php include_once 'meeting-2024-08-17.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#august-10-2024" aria-expanded="false" aria-controls="august2024">August 10th</button>
                    </h4>

                    <?php include_once 'meeting-2024-08-10.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#august2024" aria-expanded="false" aria-controls="august2024">August 3rd</button>
                    </h4>

                    <?php include_once 'meeting-2024-08-03.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#july2024" aria-expanded="false" aria-controls="july2024">July 13th</button>
                    </h4>

                    <?php include_once 'meeting-2024-07.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#june2024" aria-expanded="false" aria-controls="june2024">June 8th</button>
                    </h4>

                    <?php include_once 'meeting-2024-06.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#may2024" aria-expanded="false" aria-controls="may2024">May 13th</button>
                    </h4>

                    <?php include_once 'meeting-2024-05.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#april2024" aria-expanded="false" aria-controls="april2024">April 13th</button>
                    </h4>

                    <?php include_once 'meeting-2024-04.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#march2024" aria-expanded="false" aria-controls="march2024">March 9th</button>
                    </h4>

                    <?php include_once 'meeting-2024-03.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#february2024" aria-expanded="false" aria-controls="february2024">February 10th</button>
                    </h4>

                    <?php include_once 'meeting-2024-02.inc'; ?>

                </div>

                <div class="accordion-item">
                    <h4 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#january2024" aria-expanded="false" aria-controls="january2024">January 13th</button>
                    </h4>

                    <?php include_once 'meeting-2024-01.inc'; ?>

                </div>

            </div>

        </div>
    </div>
</div>