<div id="january2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center pb-3">
            MBAR 2022 Committee Notes
            <br>Zoom ID 831 4306 2293 Password 2024
            <br>Saturday January 13, 2024, 10am
            <br><a href='/' class="bb-link">montereybayarearoundup.org</a>
        </p>

        <p>1. Chairperson's Call to Order: 10:00am;</p>

        <p>2. Reading of the 12 Traditions: Jean;</p>

        <p>3. New attendees, put your phone numbers and email addresses in the chat: Andy, Jill, Dawn: Al-Anon, and Jane: Al-Anon;</p>

        <p>4. Are there any A.A. or Al-Anon anniversaries since our last meeting? Phillip 17 years;</p>

        <p>5. Approve/Amend Minutes from the last meeting? Approved;</p>

        <p>6. Chairperson's Report: Chris T. - Happy New Year - I am very excited to see what we are able to achieve as a planning committee with the hard work, dedication, communication, ideas, and execution with aid from the Higher Power of this group as we continue to plan and secure the means to have a well-rounded 2024 MBAR Conference. We are now in 2024, the year of MBAR. We have reports from our committee chairs to speak upon and have our Fundraising Event in a few weeks. Please ensure we are allowing for prompt and concise feedback in order to close the meeting ideally within a one hr. time frame to allow for a good balance between service and life obligations. Your attendance and participation is appreciated and I am more than grateful for the efforts of all. We are needing the following chairs filled: Outreach and Events.</p>


        <p>7. Treasurer's Report: Carolyn/Jean T: Conference Center Deposit - $5k paid; Mailbox renewed; Business License renewed; Current balance $18,400; Paid deposit at Bethlehem Lutheran Church; One registration received;</p>

        <p>8. Seventh Tradition: You can make a 7th Tradition contribution - PayPal at mbartreasurer@gmail.com or by sending a check to - MBAR, PO Box 1462, Monterey, CA 93942; Or Venmo: @MBARoundup24 (<strong>Note:</strong> Venmo and check go 100% to Treasury, PayPal collects a fee.)</p>

        <p>9. Committee Chairs/Steering Committee Reports</p>

        <p class="ti-1">a. Media - Gina: Bingo flyer distributed on Facebook and printed copies were distributed; Developed flyer for 2024 committee meetings; Misc other postings on Facebook;</p>

        <p class="ti-1">b. Registration - Naomi: Nothing in PO Box; Tested online registration process;</p>

        <p class="ti-1">c. Spanish - Robert: No report;</p>

        <p class="ti-1">c. Al-Anon - Jane: No report;</p>

        <p class="ti-1">d. T-Shirt - Kevin: Extensive discussion about T-shirts, Travel Mugs, and Ball Caps; Table discussion until next meeting - Chris and Phillip develop an on-line poll;</p>

        <p class="ti-1">e. IGR/GSR - Cole: Announcing MBAR at committee meetings; No report;</p>

        <p class="ti-1">f. Facilities - Sally: Received 24 responses to the survey; Need to be aware of sales tax requirements if we sell merchandise at the conference center;</p>

        <p class="ti-1">g. Website - Phillip: New website is up and running; Arranging to get ownership of domain names for MBAR; New pages for Al-Anon and Spanish fellowship; Phasing out Google Doc registration to online registration on the website; Website registration permits data export for registration etc.</p>

        <p class="ti-1">h. Raffle - Katherine: Still need prizes for Bingo; No report</p>

        <p>10. Old Business: Fundraising Ideas:</p>
        <p class="ti-1">a. January "B-I-N-G-O": Moose Lodge Friday 1/26/24 6 to 9pm; 50/50 Raffle and donated raffle prizes; Speaker: Elena B; Bingo Game Master; Volunteers: Food (3) Entry (3) Raffle (2) 7th tradition (2 to 3); Set up and cleanup; Start setup at 4:30;</p>

        <p class="ti-2">Volunteers: Conor - Food Set Up/Clean Up; Carolyn - Set Up/Prizes; Kathleen - Set Up/Clean Up/Food; Sean - Food/Coffee; Cindy - Entry; Arthur - Entry; Cole - 7th Tradition/Clean Up; Samantha - Clean Up/Prizes; Karen - Raffle; Rene - 7th Tradition/Raffle; Janet - Food/7th Tradition; Robert - Entry/Clean Up; Katherine - Raffle/Prizes; Jean and Gina volunteer; Susan volunteer for registration table; Cindy coordinate with Chris to transfer "Square" payment devices;</p>


        <p class="ti-1">b. St Patty Day Sun 3/17 - not discussed;</p>
        <p class="ti-2">Site - Moose Lodge or Phil's Pool House; Phil see if house is available; Time 4pm to 7pm; Speaker; Food - Chris reach out to potential cooks; Raffle;</p>

        <p>11. New Business: None;</p>

        <p>12. Next Steering Committee meeting is Tues 12/26/23 at 6pm via zoom;</p>

        <p>13. Next Committee meeting is Saturday 1/13/2024 10am;</p>

        <p>14. Meeting adjourned at 11:10am with the Serenity Prayer;</p>

        <p> Attendees: Amber, Andy, Anne, Chris, Cindy, Cole, Dawn, Gina, Jane, Janet, Jean, Jill, Katherine, Kathleen, Kevin, Kim, Mary Grace, Naomi, Penny, Phillip, Renee, Roger, Sally, and Susan;</p>

    </div>
</div>