<div id="march2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            MBAR 2024 Committee Notes
            <br>Zoom ID 831 4306 2293 Password 2024
            <br>Saturday March 9, 2024 at 10am
            <br><a href='/' class="bb-link">montereybayarearoundup.org</a>
        </p>

        <dl>
            <dt>1. Chairperson's Call to Order: 10am;</dt>

            <dt>2. Reading of the 12 Traditions: Phil C.;</dt>

            <dt>3. New attendees, put your phone numbers and email addresses in the chat: Diane C., Kat G.(Susan S.);</dt>

            <dt>4. Are there any A.A. or Al-Anon anniversaries since our last meeting? None;</dt>

            <dt>5. Approve/Amend Minutes from the last meeting: Approved;</dt>

            <dt>6. Chairperson's Report - Chris T.: Thank you all so much for your attendance service and support. You being here means so much, and I want to ensure you that the committee chairs have been hard at work and working to ensure we have translated forms and website to Spanish for accessibility, smooth online registration, ability to streamline registration info to the registration chair as well as orchestrating representation at AA events to capture early registration.
                <br><br>
                It is important that we square away T-shirt style vote this meeting as to be able to have early registrations have a chance to pick a shirt if they so choose so our registration chair can give an idea of needed T-shirts so we do not end up with an excessive surplus.
                <br><br>
                After today's meeting and our St. Patrick's Day event, we can give more dedicated focus on shaping the Conference and have discussions on how best to serve our Fellowship.
                <br><br>
                I have been able to come in contact with our Al-Anon Chair and their Al-Anon/AA Speaker Dinner Meeting was great to be a part of. They really have MBAR at the forefront of their fellowship conversations, and I cannot wait to be able to make the same connections with our Spanish Speaking community, and the Young People's fellowship we have growing in our area.
                <br><br>
                We are needing the following chairs filled: Events;
            </dt>

            <dt>7. Treasurer's Report - Jean T: See attached budget spreadsheet; Current balance $22,391 includes registrations, bingo, etc.; Includes 20 registrations; Initial Prudent Reserve $15,464; Fund raisers total $10,776;</dt>

            <dt>8. Seventh Tradition: You can make a 7th Tradition contribution - PayPal at mbartreasurer@gmail.com or by sending a check to - MBAR, PO Box 1462, Monterey, CA 93942; Or Venmo: @MBARoundup24 (<em>Note:</em> Venmo and check go 100% to Treasury, PayPal collects a fee.)</dt>

            <dt>9. Committee Chairs/Steering Committee Reports</dt>

            <dd>a. Media - Gina: Rene translating several documents to Spanish;</dd>

            <dd>b. Registration - Naomi: 13 total registrations received; Eight of the 20 paid registrations reported by treasurer; Five free registrations - logo contest and raffle prizes; Working on online registration process; Al-Anon volunteered to assist; Chris encouraged all committee members to register;</dd>

            <dd>c. Spanish - Robert: Reviewing Spanish translation of registration form, etc.;</dd>

            <dd>d. Al-Anon - Jane: All three speakers lined up; Start meetings next week; Committees assembled;</dd>

            <dd>e. T-Shirt - Kevin: Mock-ups prepared by Mica; Need to firm-up T-shirt cost; Need direction on travel mugs, water bottles, ball caps, etc.;</dd>

            <dd>f. Speaker - Kathleen: No report;</dd>

            <dd>g. Outreach - Conor: Announcing St Patrick's day; Reached out to Central offices Monterey, San Francisco, Los Angeles; Plan to attend Salinas Meetings - requested feedback on meetings that are well attended; Christina reminded committee members that we all have some responsibility for outreach;</dd>

            <dd>h. I.G.R. / G.S.R. - Cole: Announcing MBAR at committee meetings;</dd>

            <dd>i. Facilities- Sally: No report - holding pattern for now;</dd>

            <dd>j. Website - Phillip: New website accessibility (ADA) compliance nearly complete; Working on setting up registration process - Money to treasurer; Registration form to registration chair; Get Google form from Rene; Updating payment process; Spanish page setup; Address domain, web hosting, etc. renewal fees; Working on Al-Anon page; Rene coordinate Spanish translation; </dd>

            <dd>k. Raffle - Katherine: $715 from Bingo 50/50; Chris (co-chair) needs volunteers to help with raffle at St. Patrick's Day; Add committee for St Patrick's day; May volunteered to help with raffle;</dd>

            <dt>10. Old Business:</dt>
            <dt>Fundraising</dt>

            <dd>a. St. Patty Day Sun 3/17: See Attached Flier in Invite; Phil C. Pool House; Event Time: 4 to 7pm; Setup: 1pm; Speaker: Avail L; Food: Matt R. and Helpers; Raffle: 50/50 and Prizes; Katherine needs help - Ticket Sales, Prize drawing; Use MBAR Vases for tickets; Rene decorations; Plates, napkins, and cutlery covered; Volunteers - Diane, Sydney, May, Conor and several people in chat;</dd>

            <dt>T-shirt poll about the style and color of the MBAR t-shirts</dt>

            <dd>a. T-shirts for attendees: Short sleeve; navy blue with white and gold logo - ten people - approved; Short sleeve, navy blue with white logo - nine people; Committee T-shirts, jersey, white and blue - approved.</dd>

            <dt>11. New Business:</dt>
            <dt>Coffee Provided at MBAR 2024: </dt>
            <dd>a. Monterey Conference Center coffee service - One Gallon of coffee or tea service (16 cups at 8oz.) equals $80; With Tax and Gratuity - $108.75; 100 people - AM coffee: 5 to 6 gallons regular coffee and 2 gallons tea; PM coffee: four gallons (coffee and tea); Total: approx. 12 gallons for the day; (This is estimating that almost everyone would at least have one cup, and little less than half of the people would have two cups for the entire day.); Coffee at 50 gallons per day would be $5,437.50 per day; 500 people would be 60 gallons per day; Total: $6,525.00 per day; For two days, approx. $10,000 for coffee; When we reach that amount, we remove the coffee; That would be approx. 92 gallons for the two days; <strong>Unanimous agreement to reject $10K coffee proposal.</strong></dd>

            <dd>b. Extensive discussion regarding the Marriott Hospitality Suite: Budgeted at $2K - Phil gets a discount - need to book in advance; Kathleen offered to stock with food items & coffee; Motion to approve Marriott Hospitality Suite with coffee as budgeted - approved; Work out details at the next meeting and determine if budget needs to be adjusted;</dd>

            <dt>12. Next Steering Committee meeting is Tuesday 3/26/2024 at 6pm via Zoom;</dt>

            <dt>13. Next Committee meeting is Saturday 4/13/2024 at 10am;</dt>

            <dt>14. Meeting adjourned at 11:15am with the Serenity Prayer;</dt>
        </dl>

        <p> Attendees: Andy, Chris, Cindy, Conor, Dawn, Diane, Jane, Janet, Jean, Kathleen, Katherine Ann, Kathleen S., Kevin, Mary Grace, Mary H., Naomi, Phil, Phillip, Renee, Sally H., Susan S., and Roger;</p>

    </div>
</div>