<div id="august-10-2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            MBAR 2024 Committee Notes
            <br>Zoom ID 831 4306 2293 Password 2024
            <br>Saturday August 10, 2024 at 10am
            <br><a href='/' class="bb-link">montereybayarearoundup.org</a>
        </p>

        <dl>
            <dt>1. Chairperson's Call to Order: 10am;</dt>

            <dt>2. Reading of the 12 Traditions: Gina;</dt>

            <dt>3. New attendees, put your phone numbers and email addresses in the chat: None;</dt>

            <dt>4. Are there any A.A. or Al-Anon anniversaries since our last meeting? None;</dt>

            <dt>5. Approve/Amend Minutes from the last meeting: Approved;</dt>

            <dt>6. Chairperson's Report - Chris T.: As a Reminder per the vote conducted by the committee we are now meeting weekly leading up to the
                Conference. This meeting will be occurring weekly and maintain 1 to 1.5 hours long as we have time sensitive
                items to discuss and approve;
                <br><br>
                Committee Approval/ Discussion Items: The following items need consideration, feedback or approval by the committee as they may have costs,
                planning, and your input to finalize;
                <br> - Raffle Bundles Qty and Price of Tickets;
                <br> - Hospitality Room Update and Proposal;
                <br> - Decorations Chair Assistance Needed Please;
                <br> - Countdown Volunteer(two People): Execution of this is following a counting Template as well as being
                in front of everyone as the count down;
                <br> - Meeting Secretaries Readers for Naiomi to add to Schedule: We should have a variety and committee
                participation;
                <br><br>
                Thank you in advance for your participation and support, we are truly approaching some exciting and happy
                times ahead!
            </dt>

            <dt>7. Treasurer's Report - Carolyn H.: See budget spreadsheet - Hospitality suite and ASL will change: 31 online registrations this week, 133 total online; Balance $35,609; Several registrations - payment does not match registration; Unpaid early bird will honor reduced payment upon receipt of payment; Merchandise: Motion Approved - Water Bottle cost $9.99 - charge $10.00; Mugs cost $18.25 (reduced to $14 by supplemental purchase of 72 mugs by Carolyn) - charge $15; AV contract signed;
            </dt>

            <dt>8. Mark Facilities: Setup layout requested from Cody - Mark share layout maps with committee; Committee chairs email Mark any setup requests; Plan for another walk through - Chris and Mark Coordinate; Raffle Committee let Mark know how many prize tables are needed; <strong>Note</strong>: Al-Anon will not hold a raffle or 50/50 only the silent auction;
            </dt>

            <dt>9. Raffle Bundles - Katherine: Motion Approved - bundle raffle tickets & bundle 50/50 tickets: 6 tickets at $5; 12 tickets at $10; 25 tickets at $20; Extensive discussion regarding silent auction - No AA silent Auction; Possible tax issues with Al-Anon silent auction: <strong>Carolyn on the record - strongly <em>objected<em> to the silent auction</strong>; Consider alternate wording 'silent auction gift'; Jane: auction done frequently in past MBARs; Carolyn: check threshold for 1099s;
                <br>Motion - Passed; and re-voted Passed: Allow Al-Anon to proceed with silent auction - Jane (Al-Anon) - set up meeting with Carolyn(A.A. Treasurer) and Thomas(Al-Anon Treasurer) and Harry to look into possible options to comply with tax code requirements;
            </dt>

            <dt>10. Hospitality Room: Hyatt - Room is complimentary and coffee may be complimentary; Pricing not yet confirmed - Should be within budget; Room is a meeting space - ADA toilet rooms nearby; Conference Center to provide cash and carry stations - No cost to MBAR; individuals pay for what they use;
                <br>Motion approved - Hospitality suite for speakers, panel speakers and committee members and significant
                others only;
                <br>Motion approved - Jennifer setup hospitality suite along with cash and carry;
                <br>Motion approved - No signage directing people to hospitality suite; registration packets for speakers, panel speakers and committee members and significant others will have directions in their registration packet; Jennifer add signage at the room;
                <br>Motion approved - No donation jar in hospitality suite;
            </dt>

            <dt>11. Decorations - Need volunteers: Areas to decorate - Main area of Conference Center; Events; No decorations on speaker stage; Volunteers: Jennifer to Chair; Gina; Esther; Purchase candy and flowers;
            </dt>

            <dt>12. Saturday Count Down: Need volunteers - Carolyn; Arthur;
            </dt>

            <dt>13. Meeting Chair Persons: submit list of readers to Naomi;
            </dt>

            <dt>14. Committee Chairs/Steering Committee Reports</dt>

            <dd>a. Raffle - Katherine: Raffle on stage after Saturday meeting; Determine best approach to expedite the process;
                <br>Motion approved - pre-draw tickets and post on prizes;
            </dd>

            <dd>b. Media - Gina: To be announced;
            </dd>

            <dd>d. T-shirts - Kevin: No issues; Mugs & water bottles ordered; Need to staff sales table with volunteers; Jean confirmed that there will be a cash box available;
            </dd>

            <dd>e. Hospitality - Jennifer: Nothing to add;</dd>

            <dd>f. Speakers - Kathleen: Working on gift baskets; Cindy will forward a list of secretaries for speaker meetings with update formats; <br>Approved Motion - purchase recording device to record meetings;</dd>

            <dd>g. Dinner - Aubrey: No update;</dd>

            <dd>h. 50/50 - Cole: At end of Saturday meeting; Need to determine if there are two winners for early bird 50/50;</dd>

            <dd>i. Registration - Naomi (report by Chris): 124 online - 10 incomplete; 207 total - 124 online; 83 paper; 60 bundles; 67 dinners; 56 breakfast; 55 ice cream; 81 t-shirts; 10 out of state;</dd>

            <dd>j. Merchandise - Kevin: No report;
                <br>Motion approved - re-vote approved: Early sale of merchandise - Sell only coffee mugs to committee members before conference; Use as marketing too;</dd>

            <dd>k. Dance and Events - Samantha: Dance is in Steinbeck Room; 56 Breakfast sign-ups; 48 bingo dobbers; Order more if needed; All set for events;</dd>

            <dd>l. Al-Anon - Jane: Set up meeting with Carolyn(A.A. Treasurer), Thomas(Al-Anon Treasurer) and Harry to look into possible options to comply with tax code requirements; Christine: No change to Al-Anon Silent Auction 2024 - Pass on concerns for future silent auctions;</dd>

            <dd>m. Outreach - Conor: Looking for a list of speakers; Continuing to actively promote the conference; Table at Coastal Rally - Mark S. assist;</dd>

            <dt>14. Outreach:</dt>

            <dd>a. Coastal Rally</dd>

            <dt>15. New Business: None;</dt>


            <dt>16. Next Committee meeting is Saturday 08/17/2024 at 10am; Subsequent meetings will be every week till the conference date;</dt>

            <dt>17. Meeting adjourned at 12:15pm with the Serenity Prayer;</dt>
        </dl>

        <p> Attendees: Arthur, Aubrey, Carolyn, Chris, Cindy, Cole, Conor, Esther, Gina, Jane, Janet, Jean, Katherine, Kathleen, Kevin, Mark F., Mark S., Mary Grace, May, Phil C., Renee, Roger, and Samantha;</p>

    </div>
</div>