    <!-- ADA Accessibility ES-->
    <aside aria-label="Accesibilidad e inclusión de la ADA">
        <div class="container shadow-wrap">
            <div class="row justify-content-center mb-5">
                <div class="col-xl-10 col-lg-10 col-md-12 py-4">
                    <div class="p-3 text-bg-light hero-text-border">
                        <section aria-label="Event unity">
                            <h4 class="card-title mb-3 text-center text-uppercase">Accesibilidad ADA</h4>
                            <p>Nuestro equipo está comprometido a garantizar el éxito de MBAR para todos. Hable sobre cualquier área que no esté cubierta a continuación con los miembros de nuestro comité o los voluntarios. Estas políticas, reglas y regulaciones generales están sujetas a cambios.
                            </p>
                            <p><a href="https://www.montereyconferencecenter.com/facility/ada-accessibility/" class="bb-link" target="_blank" rel="noopener noreferrer nofollow"><strong>Política de cumplimiento de la ADA del Centro de conferencias de Monterey</strong><span class="sr-only">(Abre una nueva ventana)</span></a> - El Centro de conferencias de Monterey (MCC) cumple con la ADA. De acuerdo con la ADA, somos responsables de las adaptaciones asociadas con el acceso permanente a las instalaciones, como, entre otras, rampas para sillas de ruedas, estándares de ascensores, estándares de ancho de puertas y accesibilidad a los baños.
                            </p>
                            <p>Es responsabilidad de MBAR adaptarse a los requisitos de accesibilidad no permanente e incorporar dispositivos de asistencia visual, intérpretes y accesibilidad temporal a los asientos, si es necesario.
                            </p>
                            <p>Los dispositivos de asistencia auditiva están disponibles a través de nuestro proveedor audiovisual interno preferido.
                            </p>
                            <p><strong><span class="text-uppercase">Accesibilidad ADA</span>: MBAR 2024 proporcionará dos intérpretes de ASL en estos días:</strong>
                            </p>

                            <ul>
                                <li>Viernes: 1,5 horas</li>
                                <li>Sábado: de 9:45am a 3:30pm y de 7:45pm a 8:45pm</li>
                                <li>Domingo: de 10:45am a 6:15pm</li>
                            </ul>

                            <p><strong><span class="text-uppercase">Tenga en cuenta:</span> la accesibilidad ADA está sujeta a cambios con los nuevos horarios, horarios de reserva y ubicaciones.</strong>
                            </p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </aside>