<?php
session_start();  //start or resume an existing session
include_once 'header-top.inc';
echo "<title>Doble Ganador del 2024 Micha C. - Transcripción</title>";
echo '<link rel="canonical" href= "https://montereybayarearoundup.org/es/con-2024-micha.php" >';
include_once 'header-bottom.inc';
?>

<main id="main-content">
    <!-- Hero Part -->
    <div class="container shadow-wrap">
        <div class="row justify-content-center py-6 mb-5 bg-body-tertiary bg-img-audio-trans" title="Retro microphone on a blue background banner">
            <div class="col-xl-7 col-lg-7 col-md-12 py-5">
                <div class="p-3 text-center text-bg-light hero-text-border" title="Audio Speaker Transcript">
                    <h2 class="display-6 fw-bold px-3 px-md-0">Transcripción de Audio: sin editar y sin editar</h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Part One -->
    <article aria-label="Transcript-14">
        <div class="container shadow-wrap">
            <div class="row justify-content-center mb-5">
                <div class="col-xl-10 col-lg-10 col-md-12 py-4">
                    <div class="p-3 text-bg-light hero-text-border">
                        <section aria-label="transcript">
                            <h3 class="text-center p-4">A continuación se muestra una transcripción en bruto en inglés de la grabación de audio de<br>Micha C. en 2024.<span class="sr-only">(Haga clic para regresar)</span>
                            </h3>
                            <p>I'm an alcoholic, I'm a member of Al-Anon and more recently a member of ACOA so I guess that makes me a triple winner. How special am I? The majority of my Al-Anon was done down in Riverside, California before I moved up here in 2020 and I spent seven years in Al-Anon pretty actively working steps and working steps with other men. And when I moved up here during the pandemic I never really fully got integrated back in Al-Anon. I was still attending the meetings virtually down there for quite a while and when I discovered ACOA it kind of started resonating with me.</p>

                            <p>So I will definitely probably speak to some of that. I know this is an Al-Anon AA event but my story kind of contains a little bit of the three programs. And so I was born into, well first of all my sobriety date is April 12th, or so April 16th, 2012. My initial sobriety date when I was introduced to recovery was in 2005 of May and I had quite a few sobriety dates since that date. 2012 was the one that stuck thankfully and in 2013 I started attending Al-Anon meetings and around, yeah around 2013 I started attending Al-Anon meetings and one of the commitments I made to myself in that after that last relapse and attending the meetings of AA and Al-Anon was to dig in deeper on the spiritual side of the 12 steps.</p>

                            <p>I started attending a retreat up in the Apple Valley area at a Catholic retreat center but it was where AA people were holding 12-step people were holding retreats like writing it out and it was a really beautiful setting and I got to meet a priest, a monk up there by the name of Fr. Francis who just passed away this year and he was a member of 12-step program himself and so he was really versed in the 12 steps and he, and I'm like an atheist kind of punk rock kind of like very rebellious, very contrarian kind of person, finally talking to a monk at a Catholic retreat center about the 12 steps and about God and it was one of those life changing events that started me on a path that started me going inward more than not looking outward, that's what I'll say about it and I attended retreats there every year and then eventually with another gentleman who was an Al-Anon and AA member up in Pismo Beach area, started Grover Beach, started a retreat with him and some other members of AA and Al-Anon down there which that retreat now happens every November to his day and so that was like that working with people getting into the literature.</p>

                            <p>my Al-Anon sponsor was an AA member as well, her name was Gino M, she had like 40 million years in AA and a bunch of years in Al-Anon and she had me, she had became from the very same cloth, we both were raised with alcoholic families, I didn't have an alcoholic spouse, I grew up in alcoholism, I grew up in alcoholism and addiction, I have hardly any memories of a kid up until five of not being around adults who weren't wasted all the time, I lived in treehouses in Hawaii, I lived in trailer parks in Canada and I lived in all these different places with my mother and then my dad was a very stable alcoholic, you know military alcoholic and but was also very emotionally detached and disconnected and so I feel like the effects of those environments really set up kind of not just my own disease of drinking to soothe all my discomfort but a person who's also extremely socially dysfunctional at times and I know that kind of crosses over into both diseases, I'm sure when I say that of both diseases can relate and for me it's like I like, it's like this, it's like in order to work on my disease of alcoholism I have to attend meetings with alcoholics, I do, I am cut from the same cloth, I have many of those traits and at the same token they trigger the fuck out of me and so like I have to work with that and it's like I have, I've had the hardest time in sobriety then.</p>

                            <p>I have pre sobriety, pre sobriety was pretty rough and pretty reckless and pretty destructive but I really I could subdue that away, I thought I was proud of that but I had it, I had a solution and it didn't seem the matter what people were doing when I was inebriated all the time. When I got sober the discomfort, the social discomfort, the being in rooms with like lots of loudness and kind of people having a good time but like to me that translates sometimes to chaos you know I'm easily overly stimulated and very sensitive to what people say and take things personally, I want to control everything and so that as a result of that like as long as everything would stay put that part in the big book that talks about controlling the actors, to me it's like my favorite part of the big book because it describes my version of the disease and I don't try to want to say that, I don't say that to isolate myself from others like my version of the disease but I feel like we all have our journey, there's a lot of similarities, there's a lot of things that are all similar and yet there's also my journey and how I have my own conception of a higher power that makes sense to me.</p>

                            <p>I also have my own conception of how I grew up, my own family and my own experiences that created this experience that is very translatable in words and then also very unique to me at the same time and that's another thing that I've learned in recovery so I can hold opposing ideas like that, I like to black and white things, oh it's not like this so I obviously am like this where I've learned I can hold this idea here and this idea here and maybe sit in the middle with it and learn how to be okay and so what ACA, ACOA is teaching me is learning how to be my true authentic self which I like they use these kinds of words a lot of ACOA it's very I don't know very clinical sometimes, I authentic true self, my inner child, what does that all mean to me, it's like learning how to be connected to the person that I was born to be, the person that was born into this world and before the effects of alcoholism in my life was pretty pure and even though I was probably not even verbal at that time there was a purity to me and I don't know if the goal is to get back to that obviously that is kind of weird like Benjamin Button kind of thing you know but but I mean I'm trying to get back to that kind of purity inside of me where I'm not as affected by the world around me anymore and there's a lot of things I think I look at this world that I think affect me, it's not just even my relationship with people, it's the existential stuff that's the world that gets me down.</p>

                            <p>I can find myself in the in the at the end of my drinking I can find myself to my garage for quite a long time the only thing that I did that was productive during that time was was steel cable from the cable company and I watched a lot of TV and I was pretty much just checked out I rolled out of bed went straight out there before I even got a drink of water and I stayed out there for hours and then maybe I'd come in and clean up take care of myself and then go right back out there again and so like that was the best I could do with how I knew how to live and I didn't know how to live with people, I still don't know how to live with people and somehow miraculously I'm able to hold a job at a pretty decent company I'm able to make enough money to have my own house with the help of you know partnership I'm not doing it all the way myself but meaning but be part of having to live in this world, have my own house, hold down a job, function in that job, actually be looked at with some regard in that job, have friends who actually call me and ask me to do stuff with them and that's all I ever wanted was just to kind of fit in and have some peace in my life.</p>

                            <p>And so I've done when I was doing the steps I've done the steps through A quite a few times and I work with guys in that program and so until I do the steps with people I go through them again when I met with Gino she had me she had me start off with certain books it wasn't like a clean cut way to do I know there might be a clean cut way to do that but she had me do this kind of like well what kind of an alanor are you and I said well my alanor is I grew up with alcoholics I don't have people in my life that are alcoholics except for my family that's still alive I don't live with them I'm more affected about how I grew up so she had me start reading the From the Survival to Recovery book and I went through that book every Saturday and I wrote and she had me she was the one who taught me how to write start writing a few tons of writing we went through the transforming our losses grief and the grief and loss book which grief and loss in recovery like that was really important for me to realize what I had lost as a result of my alcoholic people in my life which for me was my childhood which explained to me like why I when I moved out of my parents is why I just went like crazy wild like I was like I'm free.</p>

                            <p>I finally can live you know I was under a clamp with these people they taught they pretty much told me how to think how to live how to be they raged at me if I didn't they put me down if I didn't it was just like a constant onslaught and to this day I still have to deal with the constant onslaught of one one month they're talking to me and they love me and then for months like no one will talk to me and they're like thanks for some reason someone's mad at me and I don't even know what I do just wake up one day and they're like they're mad at me and that's the world that they live in and I'm learning how to not do that engage in that anymore and even more so learning how to stand in my own power and maintain some semblance of maybe some love and peace toward them in my heart working on learning how to love myself and be comfortable in my own skin so that I don't have to be affected by other people's untreated alcoholism and untreated codependency issues so that's saying I did grief and loss book survival to the recovery and the little blueprint for four-step book and just a ton of writing and I walked other guys to that same process that seemed to be alcoholics.</p>

                            <p>Double winners alcoholics who were in Al-Anon looking for an answer to the chaos that was in their life in sobriety and so that's been kind of my story with Al-Anon and when I moved up here my sponsor in 14 years told me that it would be a good idea if I stopped doing the virtual sponsorship and started looking for a sponsor up here and he had always given me good direction he'd always given me clean direction and when I'd gotten my anything I had as far as recovery was going was because of him so even though I was reluctant to want to do that it was a huge like it was like a breakup it was sad it was painful I didn't I didn't feel comfortable about that but I still trusted that his judgment was good and did it anyways and I started looking for a sponsor up here I was at the mighty muffins meeting one morning and I've shared about that and shared that I was looking for a new sponsor and that it was just like a huge ordeal for me at the time and afterwards this gentleman came up and talked to me and kind of made some jokes about it and told me that my higher power would lead me to the right person and that person's voice stuck in my head for quite a couple for a couple days and I ended up asking that person to be my sponsor.</p>

                            <p>Lo and behold that person has a strong background like mine very similar background as me still has family that's alive that he still struggles with in regards to like the dysfunction that exists and trying to navigate that dysfunction in a way that cherishes myself but still lets them be who they are meeting them where they're at and but not also getting sucked up into their chaos that's a really tricky spot to be you know like I'm a very polarized person like I don't want to if you got to be either I'm with you or I'm against you like you're either in my life or I'm cutting you out and so they'd like be okay with people who are not kind and not so considerate at times and not try to run to them and try to fix things and try to change them and try to chase their love anymore to not drink over their behavior or other people's behavior to instead try to try to find this is I emphasize trying to find a place in my heart I have not found I'm not always there some days I have really good days sometimes I have really good months weeks maybe even a year or so but there's still a part of it that resorts back and I have to work on that.</p>

                            <p>It's trying to find a place that can be okay with people just being who they are and even the world alone as it is using that acceptance kind of analogy as kind of a guide and learning how to stand up advocate be proud of who I am and not self-loathe because that's my first go to somehow they did me wrong somehow they I did something wrong somehow I'm a piece of shit somehow you know no matter what even if I do the right thing I don't even know if I did the right thing and so continuing to take that to my steps this person had the same makeup as me we worked the steps of AA in a way that was very tailored to ACOA and alan on type type thinking and we've been doing that every week for the last two years and we tried to take that format and even to a meeting format to where we had active step working with groups of people and it was interesting that some people showed up and you know and and it didn't really hold as a meeting though but we continued to meet we continued to meet and I still continue to meet and me and me and him have recently decided to attend ACOA together and we're working with a sponsor and ACA together.</p>

                            <p>Side by side through their literature and the the verbiage keeps the the language that I'm receiving from the 12 step programs about how to work the steps on me and find the solutions is just ever widening I think the biggest part of it's not having I think even when I came into AA and when I first came into alan on it was hearing people's messages hearing the message of a problem that I didn't have even in words to to hear people finally say words to my problems and go wow so if there's words to this that means other people experience it if there's a language that describes what I have it means that I'm not alone and that's continuing to grow as I continue to work my steps and ACAOA is this where I'm at today breaking that door even open wider and giving me a language that's even deeper to be closer to myself into what I what I see is my higher power so today I don't necessarily always have the urge to drink to check out anymore I'm so grateful that AAAA has lifted that obsession and because of that propensity to drink again I continue to stay very diligent in my AA program as much as I don't attend alan on as much as like it's more of a logistics time thing the ACAOA program which combines kind of the two together has really been an amazing gift from my higher power.</p>

                            <p>To continue me continue me working on that part of my personality that likes to utilize people places and things as a reason either check out a life or to control them so that I get what I want and 20 minutes doesn't even give enough detail to really get into the details of all that but it's just you know the message is my experience has been that I can a person can go through the trials and tribulations of dysfunctional families and drinking my hope is that the programs the 12 steps in all their forms have been great gifts to go deeper and learn more about who I am and I continue to show up for that and as a courtesy to myself and to continue to give that away to others so that I can continue to grow because God knows I'm not perfect today that's for sure I feel like whatever I've learned today is just a scratch at the surface and that keeps me coming back so thank you for asking me to share Kathleen and thank you all for being here.</p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <?php include_once 'footer.inc' ?>
    </body>

    </html>