<?php
session_start();  //start or resume an existing session
include_once 'header-top.inc';
echo "<title>2024 A.A. Mark S. - Transcripción</title>";
echo '<link rel="canonical" href= "https://montereybayarearoundup.org/es/con-2024-mark.php" >';
include_once 'header-bottom.inc';
?>

<main id="main-content">
    <!-- Hero Part -->
    <div class="container shadow-wrap">
        <div class="row justify-content-center py-6 mb-5 bg-body-tertiary bg-img-audio-trans" title="Retro microphone on a blue background banner">
            <div class="col-xl-7 col-lg-7 col-md-12 py-5">
                <div class="p-3 text-center text-bg-light hero-text-border" title="Audio Speaker Transcript">
                    <h2 class="display-6 fw-bold px-3 px-md-0">Transcripción de Audio: sin editar y sin editar</h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Part One -->
    <article aria-label="Transcript-14">
        <div class="container shadow-wrap">
            <div class="row justify-content-center mb-5">
                <div class="col-xl-10 col-lg-10 col-md-12 py-4">
                    <div class="p-3 text-bg-light hero-text-border">
                        <section aria-label="transcript">
                            <h3 class="text-center p-4">A continuación se muestra una transcripción en bruto en inglés de la grabación de audio de<br>Mark S. en 2024.<span class="sr-only">(Haga clic para regresar)</span>
                            </h3>
                            <p>And now I would like to introduce our speaker. He's our kickoff speaker for today, Mark S from Salinas, California. Good morning everybody. My name is Mark and I'm going to call it.
                            </p>
                            <p>That's how it works little, uh, what she read and how she got tuned up, you know, and I can feel it in the vibe that she was given. And she's fired up about all calls anonymous and the things that we got going on. And I can tell you that somewhere along this, uh, this chair, this what I'm going to share right now, something's going to happen to me where I'm going to get, uh, I'm going to something's going to kick in and I'm going to feel this, uh, you know, and I can relate that to. Just power grading myself is an action and that the way I feel about all calls anonymous and.
                            </p>
                            <p>Um, Embar. Did I say my mark and I'm not called? I'm not. Anyway, uh, and I'm glad to be here.
                            </p>
                            <p>The committee that has to put this together. Uh, it's a, it's a lot of work and it's a lot of zoom time and it's a lot of it, everything. And, uh, I'm also the marathon chair across the room and in each one of these things is where we're in, we're in charge of a little part of this big hole and it's, it's amazing how. How a bunch of people that don't mix get together and we end.
                            </p>
                            <p>Things get done, you know, and it's amazing. Now, and, and there's some X, there's some chairs open, but there's, this is just an amount of people that we need right now. You know, it's a perfect amount of people and I want to thank you guys for showing up, Al and on AA, the newcomers, you know, I've met a couple newcomers and, uh, um, Chanel that she's chairing down here. I mean, not she's not chairing.
                            </p>
                            <p>She's signing down here. I've met her through my, this path and it's just a wonderful time to be an all calls anonymous and, uh, you know, I'm great. I'm going to take a moment. Uh, I have this higher power that he doesn't come where he's not needed and doesn't stay where he's not wanted, you know, and I'm going to invite God into this right now and, uh, let him know that, um, I need him more than anything, you know.
                            </p>
                            <p>Father God, I invite you to this in bar, not just for this hour, but for the whole weekend. Um, I need you to protect. I would, I'm asking you to protect and, uh, and watch out for all our fellows that come in these doors and, um, and these names, I pray. Thank you guys.
                            </p>
                            <p>Um, you know, I said I'm an alcoholic and, uh, you know, I am an alcoholic and I drink. I have to describe how I drank, you know, and just to make sure that I deserve this seat and the things that I do in here. And, uh, I am an alcoholic and, uh, you know, and I drank for a long time and, uh, and it wasn't that crazy bad, but, uh, there was a point to it that, uh, um, living on this, this self will and trying to fill my basic instincts of life that, that things got way out of hand. And, uh, and I had to, uh, I got sober in rehab.
                            </p>
                            <p>You know, it's a place that a Salinas is where I, I was planted and my roots grow in Salinas and that's where I stay at now. And, but I'm from Seaside and Monterey is my area where everything, everything happened. And, uh, I went to school here. I went to Monterey High School and, uh, you know, all my friends that were here and I didn't think for a second.
                            </p>
                            <p>I'd be in Salinas, but that's where, uh, the fellowship that I met was in Salinas. And Monterey has a great fellowship too, being involved in, in all this service stuff and, and meeting people. You know, it's just one, I think it's just one big family and, and we are, it's, it's together, but, but, uh, the Salinas, I felt this Salinas, uh, the second time I went to this rehab and, uh, you know, and, and this fellowship just grew around me and, but I had to get there. And I, I was at a point where I drank for a long time and I forgot a few D.
                            </p>
                            <p>Ys and the consequences of my drinking, uh, finally caught up to me. And, um, it's, it's something that I had to do because I was almost made to do it. Um, but I had a choice, but I was trying to, I, I fought it also, you know, it's this, uh, uh, self-will that I could do this. I have this pride thing that's going on and, and I got sober when I was 48 years old, you know, and I started drinking probably in high school, junior high school a little bit.
                            </p>
                            <p>And, uh, it just, the, the progressive illness that, that, it happens and I hear it all the time, you know, this, it was fun and all this stuff. And I had some, but my consequences were right off the bat, you know, and, and I could not, I did not see it. Um, I did not feel it and I was always correcting my life. You know, I was always fixing things that when, when I would mess up and, and I could take control of this control drinking type deal when I could stop for a little while and wait till the courts cleared up or the, the, you know, I paid the fine or whatever I had to do.
                            </p>
                            <p>Most of my, uh, court issues were, uh, I drive, you know, I like to drive and drink and, uh, and, um, that's where, but that's where it all came down to and driving is a privilege and, um, you know, I'm, I'm, uh, I went against grain on that one and, and, but it all, it all, everything had to happen. The, just the way it did for me to get here to hit that, that bottom and, uh, I'm grateful for that. And it's, it took a, took a long time and, you know, I remember this, this first time, I was, I was little, I wasn't an alcoholic all the time, you know, I, I drank, uh, I was in, in Redding, California and our cousins and our family, we used to go to this clear, clear place and, uh, it's like, Royal Psycho or something. And we would go swimming and stuff.
                            </p>
                            <p>So we was going up the road and they pulled over at this on tap. They call it on tap at the store where you buy stuff and there was a beer truck out there and my cousins were a little bit older. I, I wasn't having them to do with it, but I, well, I did. And then, uh, and I'm a little, I'm a little kid.
                            </p>
                            <p>And so they, they walked up there and they rolled up in the door and took a case or two or whatever it was. And, uh, you know, and I, and I felt that that a little bit of fear or someone was going to happen, but I, it didn't pay that one away. And then we're, we're at this place and I'm on this inner tube. I don't even know how to swim yet.
                            </p>
                            <p>And, uh, I remember having this little can that I think was a course and it was like, I, I felt something, you know, uh, that, wow, look at, you know, look at me now, you know, and I was, and I didn't think nothing out. I wasn't an alcoholic. And I probably didn't drink the whole thing, but at that, that feeling of, oh, yeah, it's kind of good. And I really didn't feel just, you know, I felt a part of everything.
                            </p>
                            <p>I didn't have no problems with people or making friends or, uh, getting involved in things and all that stuff. But it was just like when I, when I started drinking, it was just that little, uh, like you baked potato, you put butter and salt and pepper on it, just that little bit of spice that made everything just right, you know, and, and I felt that and I kind of chased that for a, for a long time. And, uh, high school went through and there was a couple of times that I remember a senior cut day that we went to South Mount Ranch and got a little drunk and that was the fun times and, and graduating from high school and having going to Hawaii and you could be, you know, I was 18, 18, you could drink in Hawaii at that age and, um, it was, I had some good times and, uh, but right along that, uh, I had some good times. And, uh, uh, but right along that time, um, in high school, I got my first UI, you know, and it started, the, the consequences.
                            </p>
                            <p>There wasn't, there wasn't really no consequences. This is probably 78 or some around in there where, you know, um, I remember going, they, they had me do some things. I had to pay 300 bucks or something like that. And then I went to this Monterey High School in their driver's ed class and looked, get smart fast program.
                            </p>
                            <p>It was about a CHP's and you watched a bunch of videos and, and it's some, you know, some reps that happened and the people that were involved in them and they showed all this stuff and they were trying to scare me, uh, get straight fast program. And, and I, I seen it, but it didn't have no, you know, it didn't take very long. And then they said, well, I don't know if it was time to know for me to be out there and that, And I could always, I could always, uh, uh, get sober for a little while, you know, but, but, and I didn't know what alcohol. You know, what was going on and as soon as I got here it made sense, you know, it made sense of what was going on.
                            </p>
                            <p>And I constantly did that and, you know, I was able to, my job, my job, I had a good job. I never went to college, but I started working in high school and I was working at this dealership and, you know, I got involved. The job was, they had, after work, they were going to back and they would buy some beer and they would drink some beers and all that stuff and I got involved in that and a little bit. Everything just progressed itself a little bit and it started to become, you know, an everyday thing and I was, you know, I was part of it.
                            </p>
                            <p>But as I moved along, my job started in affecting my work and they were all, they were in the back with me drinking and so no everybody, they kind of washed out for everybody and they kind of okayed my bowl, you know, and they washed out for me and so there's a part in the big book where it talks about employers and they covered me. I should have been let go or reprimanded a long time before that, but I stayed there. I was there 27 years and my, these DUIs were coming more frequent and my, I think it was my fourth DUI, things started happening to me and the courts were getting a little bit more, I think I did my first, I went to jail the first time and I wasn't liking that and then when I got out, my driver's license was suspended. My driver's license was suspended and, you know, my job, it took an effect on things and so I was able to clean things up and, you know, do what they wanted me to do, the breathalyzer and all that stuff and my job was covered in me, you know, when you get a DUI, they take your driver's license away so they tried to set me up where I could just drive in the car lot and, you know, around not getting on this because I have to test drive cars, that's the deal with where I work.
                            </p>
                            <p>But so this stuff was getting worse and worse and worse and then, you know, at one point, they had to let me go, you know, after 27 years at his job, because their insurance would not cover me and it took them two years from the time I got in the trouble into them covering me so I figured out this two-year thing. So I went to Salinas as another place that I was working for and so I got a job over there and within a little bit of time, their insurance got up with me and so I was jobless and I had this house though, you know, and I took some money out on the house and made it put a deck and it bought me a motorcycle and all this kind of good cool stuff but I wasn't working and I couldn't work. But my alcoholism, it got even worse. I got DUI's five and six and then the jail time was, I'm trying to get out of the trouble that I'm in because it was not just a little bit, it was a lot of trouble and I was scared and this is the first time where we're all called, I was trying to stop but I could not, I was obsessed with alcohol by this time and it got to a point where I crossed that line.
                            </p>
                            <p>I knew I was the alcoholic the long time ago but I admitted that I was the alcoholic and I knew I needed some help and this was 2006 and I came into, I went to that place I told you that rehab that it's a men's residential in Salinas and I went there and I had these two DUI, I had one and then it was a motorcycle accident underneath the tunnel here and I wrecked and I crashed this brand new motorcycle that I had and I'm trying to fix things up.
                            </p>
                            <p>I had a hematoma on the side of my face, I had some staples and I shattered my elbow and my hip muscle was disconnected and my partner in this business kind of locked me up in this room at his house and I woke up in the hospital with handcuffs on this bed and I'm looking at it and my no driver's license and they took that away and these people were looking at me like and I'm swollen up and I'm in a cast and you know and I'm feeling this thing, it's starting to you know and I don't know what to do so they take me, I don't go home, they take me to his house and put me in the back bedroom and time to recover a little bit.
                            </p>
                            <p>Probably within four days I'm feeling a little better and nobody's in the house and you know I had this obsession thing going on and the detox part of it, once you're in the hospital for that day and you got pain medicine and all this stuff but after the pain medicine wears out and I was in this guy's back bedroom.
                            </p>
                            <p>I started getting this irritable and discontent feeling and this alcohol thing was I was feeling it, I needed the alcohol so I snuck out the back door and went around the Corpom bottle and I got something to fix me up and within a day or so I convinced him that I was okay and I was going back to my house and this is a month time for a DUI and I read I'm at my house and this memorial day weekend and 2007 I think it was so I said everything, I'm going to go to the lake. </p>

                            <p>And you know I get in my car in the ice chest and I'm driving to San Antonio Lake and I'm in line and I buy all the stuff that I need and I have this ice chest and a bottle of Jack Daniels was my one I drank and I bumped I mean lying to pay for the thing and I bumped into this this jet ski and the guy got out of his car and I was just like two cars away from getting in there the line was a mile back and I just got in I was getting ready to pay the money and I reached out and grabbed my phone and I bumped into his jet ski and he got out and I got out and I'm feeling it a little bit you know and so I went to shake his hand and he put me in a thumb hole and he put a mojo and put my hand behind it and he said he was an off-duty correctional officer something like that and I kind of I did resist and then the cops the cops were already there and the guys on the horses and this is a big thing in San Antonio Lake on Memorial Day weekend it's a lot of people and a lot of and and and they all they the guy on the horse will walk I mean rode in and the people just all they did walk from the cop cars to over to and and I resisted and I didn't want to do the Phil sobriety or I didn't want to I was you know and so they put me in the cop car and they told me they were in take me to King City and and to do this blood.
                            </p>
                            <p>I told them I wanted a blood test they were gonna take me to King City and I got there and then I told them I didn't want to I didn't want it that either so I was hoping that this would all code were off so I wouldn't get the blood content that I did but I was I was soft that's kind of that's the thinking that's that happened to me anyway I end up in jail and you know they I got bailed out I had I had a lawyer for this fifth and this six DUI and I'm trying to to I'm in a deep shit right now you know and I'm feeling this I'm feeling this my you know and I don't know what to do and my buddy told me about this place in it so I went to this place trying to hide from the trying to hide from the I thought by being in this rehab it would do something for you know sneaky the slide mark that always does things and gets out of things well I don't think I was gonna get out of this one and so I went there trying to be slick you know and and by if if I went and had to go to court you know they might say oh mark you you're doing really good you know but that's not the way it went my the lawyer I and I told my lawyer and I said I told him I had another one he said oh no what do you what mark I just told you not to drink.
                            </p>
                            <p>So this is five and six within a month you know and so I'm I'm there and and and I do this I end up going to substrate they tell me that within a month I did the first part of this this rehab that I was in and things were going good I was going to do these meetings that they had there and I was meeting some some the fellowship of alcohol synonymous this Sunday eye opener is you know it's my the meeting that I I go to every Sunday you know it's my my home group and it's where I met these people these some of the old timers there and and I was feeling this this fellowship thing that they had on and it was kind of like I met a fella there that you know we shook hands and I told him my name was marking said my name is Bill and I and then the next week I come back and and I walk in and I see him and he walks up to me and says hey my name is Bill and I mark how are you my name is Bill and I know I bill and it was kind of this this beginning of this you know I seen something in the fellowship the part of the fellowship where where it was the first maybe there's something going to happen I stayed there 30 days my lawyer calls me up said Marco you have a turning date and this was July this was no I wasn't July it was this was 2006 and I was in there so from I had I got 300 days for the fifth one and 275 days for the 60 UI so that almost at 575 days of that I had to go to county jail and so so that it was that's a long time for me and and by by by time I went there this is probably the fourth time that I was there and so I did these I did just 300 days they let me out they let me out of jail and and I'm saying okay you know that's kind of a thank you and they let you out at three o'clock in the morning and I'm still untreated you know.</p>

                            <p>I went through that 30 days but that's I was just going to what they wanted me to do and I had a place to sleep in a place to do my laundry and you know nothing really took or nothing really happened because I didn't do nothing I didn't do nothing I just was staying there I was trying to hide from the but I couldn't hide no more that cat was out of the bag you know and I was I was dealing with this and so I did 300 days I could be 300 days you know that was the first time so I did it and I got and how I got I worked in the kitchen I did you know I got involved in the kitchen and stuff and the 300 days were up and the day let me out three o'clock in the morning and I'm walking across the street by time they debook you and all that it's you know it's the sun's coming up and there's windshields donuts and I said I'm gonna get some donuts because I have some money on a couple bucks on my books and and I'm gonna go over there and get a donut right next to it is a liquor store and they were opening also and you know that the sense that maybe I should have had and this this willpower that I should have had when I'm when combating alcohol and I have this disease and this obsession that this thing that you know I no matter what I'm gonna drink you know and I passed up the good donut and I and I got and I got a bet you know a half pint of Jack Daniels and by time I got to the bus store and bus stop in Selena I had to walk away to get to the bus stop and by time I got home you know I was already I was already and that's that's what I deal with you know.
                            </p>
                            <p>And I can't not not drink you know I cannot not drink and and and I'm home and I cannot not drink and it's so I'm trying to you know I when I did some push-ups and this and that and I'm feeling pretty good but but I also am an alcoholic and and I find a way it is when I was in jail you know this is that the second let me tell you about this and then that the I was it was probably a week into being home I called up the DMV and asked them you know I need an ID because I don't have an ID and she looked my name up she said Mark there's something else going on you need to talk to your lawyer and so I called the Tom and and I had a warrant for my arrest you know for that second for that 60 UI and so he went he went to he went to court he was going to court for me and I had to turn back in because I had I had a that that sixth DUI I didn't go to court while I was in jail so I had a warrant for my arrest so I turned myself back in and did 275 more days and that that's kind of you know so so the in between the 2006 and my sobriety date of July July 10th of oh eight you know I spent a lot of that time in jail so you know it was it was something that I had to I had to do and while I was in jail I see my in a in a three-week old paper I see my my house being foreclosed you know and and I was 11 years into a 15-year mortgage and and to see that to see something like that happen it's like oh no what else you know but that's that that's you know there's I don't know why it happened but there's a thing called justice and I believe in it and there's a path that I have to take to get here and something has to make me willing to to to give myself to this program you know.
                            </p>
                            <p>To give myself to program and just see what happens and so after I did the 275 I came home and I was in the same position untreated alcohol you know and and there's no and within two weeks I'm at this point where I'm laying on my living room floor and I'm shaking I'm in a sleeping bag I'm selling fixtures life fixtures for for some money and you know and the guys from the real estate are coming they want keys they're offering me keys for cash and I can't I don't have nowhere to go I can't stay sober and I'm laying there on the floor and and I'm what am I going to do what am I going to do the house had already been this was in oh seven or oh six and seven there was a lot of houses being foreclosed a lot of houses were foreclosed and mine was one of them and so they didn't even bother me so I squatted in my own house for probably two months and at the end of that two month I was I was laying on the on the floor on this in a sleeping bag and there was my there was my refrigerator was leaking the washer wasn't working I had a hose hooked up for my next door neighbor to my house with their water on and my water on so I would have water in this house and I was just squatting you know and I was waiting I don't know what I was waiting for and then this and I'm and I'm crying and I have to have alcohol you know I have to have that at this point my body was sick my mind was sick and and the alcohol was the cure and the problem all in war and on the floor I remember these these prayers that I that I prayed then while I was in the deepest darkest part of of my life I think that's when this guy that I prayed to just a little while ago you know he hears that and the sincere desperation and you know there were something to these prayers that I meant it with my mouth and I meant I mean I said it with my mouth and I meant it with my heart and within probably four days I was able to have a clear thought and I called up this place and when I called them up they remembered me from two years ago and they said Mark let me let me check on it.
                            </p>
                            <p>They called me back two days later Thursday and and they said Mark we have a bed if you can be here today we have a bed for you and so I shut the door on this house I grabbed whatever whatever a pair of a pair of pants and some socks and stuff and I left I left everything that I belonged in that house and I said all right it's the point of the this surrender port where I had to get to someplace and just you know alcohol beat me I threw the flag up the you know I couldn't go on tomorrow and that was July 9th July 10th when I went in there I drank the last my last half pine or pine lotto for whatever and I needed help up these steps to get to this place I was shaking, rattling and rock rolling and you know I this was the first day of my it was a terrible time but the best time of my something new was going to get ready to change and I was going to be a part of that and I was going to be not a part of that and I was going to be a part of this and and I believe in the program and from that day that day on something had something happened to me where this you know I it was like it wasn't the steps you know three that I said that there's given to us in the book in chapter five it was just a honest point you know god I made a you know I made a whole lot of mistakes and I'm hurting real bad this was on the floor when I was crying and I I need some help and it was kind of like that was the thing I knew I was alcoholic I mean I said alcoholic but I really didn't know what it consisted of but I was in there and and I was I came to believe this god that I I met my grandmother introduced this god to me when I was a little kid and it's the same god and and when I'm an alcohol synonymous you know I have to turn to god this god of my own understanding and it was easy for me I didn't have a problem there but but I but I if I had to turn to him you know I guess my back might have been away from him and that I was just trying to live on my own will and my own way of thinking and trying to just do things my way and you know it was was a bad place to be and so I think that god heard my prayers when in them last days and so I I went to such street and that was my day day one.
                            </p>
                            <p>And they took me to the hospital and to they have a detox place there and so I was I went with with a blanket on a rubber bed sheet and and I stayed there for probably five days six days seven days and until I was able to drink some Kool-Aid and have some peanut butter and jelly sandwiches and you know and the guys there they were taking care of me the guys that had just just like AA that there's guys that had a little bit more time than I did and they were they were bringing me Kool-Aid and peanut butter and jelly sandwich till I got up and was able to participate in the facility that the the what they did there and and they they they made us go to meetings you know and so I re went to that the Sunday eye opener and I seen the same people were sitting in the same places and they were talking about the same thing and this recovery and I heard some of these old timers they were talking about you know their their stories of how they they were you know down and out and couldn't drink and they were battling the same thing and I heard the similarities and that's what I picked up on is the similarities of of of this disease that I have and and there's a you know there's a common solution and and I kind of said okay let me get involved in this and I didn't make no commitments or nothing you know but but I felt this this whatever was was going when I walked up there I knew that I was all in this thing I was going to give it a fair shot you know I just say I was going to go give it a year or nothing I was going to give it this a fair shot and you know and I've been here ever since and it's this this family that there's a solution they talk about this you know that they they go off in the beginning of this fellowship but what we have right now and and we need each other we I need you and I hope you need me you know and together you know we have a better chance on on on just staying sober.
                            </p>
                            <p>And you stay in the middle of the the herd and you you do the things that we're doing it right here and and then the number of the things my sponsor is John was John Anderson and his wife Rosie together you know um this the sponsorship thing that is that I didn't have nobody you know I had some spats some people here and there but nobody in my life that met you know with had some foundation and I um I asked I had somebody else asked John to be my sponsor and you know it was just this guy that he would come to this this rehab that I was at and he would be there when I got when I got up in the morning to go eat breakfast he was outside drinking coffee and smoking cigarettes you know and I said well who's this guy I remember him the first time I came and and boom he was there again and I said who's this guy and so I asked Ruben the cook I said go ask this guy if he'll be my sponsor I need to you know it says get a sponsor work to staff and all that stuff on the and as I said okay this is the first part of it and so I asked him and he said yeah he said no problem and uh he started taking me meetings I met Rosie and Rosie was involved in in slainess and and gradually nothing happened overnight nothing that you know it doesn't happen overnight but I finally got hooked on some of these people that were in in all-calk synonymous and they were doing things and they talked about getting into service and John didn't have to tell me I seen what you guys were doing and and I was all in I was in and I started doing these things and and it was kind of you know the coffee commitment is in the greeters are are you know uh so important you know when you're at the door and you're scared and you're scared and you don't even know if you're driving around and you don't want to kind of am I going to go in and yet am I going to go in yet and but these greeters are there they they're too to uh you know just greet you.
                            </p>
                            <p>And comfort you that's that's my job is to to you know the people that feel uncomfortable uncomfortable is to comfort them and just enough just enough so they can maybe get to go in and you know begin this process and you know I have I feel all of it and I started getting to service and but John was it wasn't a big step guy you know and that's that was one thing that was you know and so what what happened was I these this 12-step program came from San Jose and they started wanting slainess and I got involved in that and Marty I was assigned Marty Marty to be my temporary sponsor and I asked John I said John is it okay if I if I go through this step study and just see what it's about and and he said sure why not and so I went there and I got hooked up in these guys and this was probably 12 years ago it came from from San Jose and I worked the steps and I I've I did a I did a four-step I've talked to Marty about you know these things down my four step and I was resentful I was so resentful so fearful you know and some of the harms that I did to other people you know I I wonder why God could get in I wonder why I wasn't getting you know no worries because these advertisements and fears were blocking me from this the spirit of the universe and I was kind of like I just learned a few things and I'm kind of challenged you know to learn things and learn how the book goes but gradually things things started shaping up and you know and I you know I waited that hour.
                            </p>
                            <p>I waited that hour to you know to make sure that I did everything right and when I was talking to that here's the important thing about the you know doing that fifth step and and he mentioned is there anything else Mark when we when we've got done with our with the resentment part of that mark is there anything else and I said no I covered it pretty well and we got through the fears that mark is there anything else and we we did my sexual harms and and my my harms to others and is there anything else and I told him about this once one thing you know but I kind of sugarcoated it and which which this thing has haunted me for since I was going to ready when I was a seven or eight years old seven or eight or six or I don't know what when it was but these are the this is the thing that could have got me drunk if I wouldn't have an amp you're just shameful you're a man and these things ain't supposed to happen to you but I'm telling you they do you know so there's a part of this where where the importance of getting it all out getting it all out and you're gonna try to take it to the grave thing you know that that is I might drink if I don't get this out and so I did this fist step and I covered it up with sugar and spice and all this stuff and I'm walking across and and he says okay now I want you to take an hour and go over this and make sure that you're you know you know what your your your cement your structure is is good and and I walked out of the room and boom this thought came back again and I know that I didn't let this man know what the thing that was bothering me the most in my life for the longest time and and I don't know if that that made me an alcoholic you know but I know I drink and um and if that was the cause of it deep down inside this this I shoved it so far down that I it wasn't gonna see the light of day I was gonna die with this stuff and that and that's the thing it wasn't dead it was still there and when something I seen something or went somewhere it all it stood his head out there you know and it or like oh shit.
                            </p>
                            <p>Am I a bad person my you know what's going on here and you know I and I don't know if that's the thing that made me drink but it was probably somewhere in there this unconscious mark these thoughts and so I had to get this out so too I go to this men's retreat and sound while Batista and that was coming up a week after this this this this fifth step that I thought about it and and I was getting ready to give this to God but I couldn't give it to God because you know I'm holding this stuff back and I go there and this guy Brian he's the he's the emcee of this and he's a he's an alcoholic it's it's you know it's his three day thing in San Juan Batista and it's a it's at St. Francis retreat and it's a wonderful thing and he got up he was doing we had we had this we have a theme that goes on all weekend but he it was like around lunchtime or something he says okay I have the this slot open from 12 o'clock to 2 o'clock and every 20 minutes I have you know if somebody would like to come in he's an ordained minister so I said well I heard about that in a big book I'd go tell him some stuff and and so that's what I did I put my name down on this this piece of paper and I went in there at 1230 or whatever it was and and I laid this down and I told him what I did you know I did this this this step and and I had an hour and this came up you know and and I need to I need to clear this up you know and so I I told him you know some of the specifics about what went down how it went down and and where it was how old I was and everything he told me that before that he said if I if there's something that he was telling everybody if there's something I haven't heard I'll give you 10 bucks or 10 to 20 bucks or whatever it was and so when I went in there and laid this all down to him it was kind of like he didn't even bat an eye it was just like the stories that I hear about other people you know it's like something I wasn't singled out I'm not the only one that this happens to you know that that's the point that's made.
                            </p>
                            <p>It's like I'm not the only one that bad things you know happened to and and and I tried to look at when I was going through this I was trying to look at my are we times how was going here what my part what my part was you know and I don't know my part was and I talked to John about this everything my part was I didn't say nothing to nobody when this happened to me you know I held on to it and because I didn't want to tell my mom my grandmother my own John my my family that this this thing happened it was family you know and I didn't want to say nothing to my so I carried this stuff without telling nobody and that's that was my part of it and I I could not you know I'm looking at this and you know I did you know work the since then and in the first time you do them you kind of you know it kind of was kind of tough you know and I didn't know exactly what they wanted and how they wanted it and all this stuff so I so I just did the best I could but that I knew that I I had that and now and that was out in open and it hasn't bothered me not one bit and maybe that's the thing why I'm sober right now is because I admitted and I let it all on the table there's no there is no secrets that I have that another person hasn't heard you know and if that's the case then then you know having a relationship with God God knows me you know I admitted the stuff and so you know that that was the main thing if six and seven is where I don't know nobody outside AA does you know a moral inventory and take an hour to look over it and then you know ask God to remove these things I don't know it's kind of like it's amazing anyway I did that and I I made a list of people that I harmed you know and you know I started making amends and there was one of men's financial amends that I couldn't I it was restitution for for some stuff that I did and I couldn't pay fifty dollars a month I couldn't pay fifty dollars so I went to this guy Renee he's the guy at the France you know.
                            </p>
                            <p>He was the one that's collecting my money and stuff and I and I was I started to be worried about looking in my mirror or behind me who's who's looking for me or whatever and so I went I went to him I say I can't pay this I know I would try and I know it's only 50 bucks I had a job at Target you know making minimum wage and I'm writing you know as all this stuff that I'd come up with and and he's and then I asked him well can I go back to jail because I could do you know whatever standing on my head and and so he told me the process to do it so I started the process I went I filled out this paper I asked a judge I said hey judge this is my situation I have you know $1,800 I owe I can't pay none of it can I go to jail and in about probably two weeks he's I got a paper back from the courts and he said yeah and so what they did was took a hundred days I mean a hundred dollars per day for it and so that that would be 18 days and I just spent 500 days or whatever it was and so that that was nothing and I ended up for good time and all that I did you know and and all the what would the idea behind this is you just kind of there's nothing that has been uncovered and and you find these people that you have harmed and you've heard and you try to make you make an immense not I'm sorry and you know I know what I did to him so if I if I don't go back and do that again you know because I had it written down on paper written down on paper is so important and you know I can go through that list and you know make these amends and and now I have a sponsor that's that's here and he's across.
                            </p>
                            <p>I met the marathon meetings across the hall and it's all day you know every hour on the hour and that's where I'm going to be for the rest of the day and for the you know till tomorrow evening at six and you know my story is I don't have enough time you know to to go into a whole lot of it but if you guys were if you guys want to know me get to know me my name is Mark and I'm right across the hallway and my time I think I overshotted just a little bit and I don't know a meeting is a meeting and time is time and I want to thank everybody for coming here and listening to me this is the first time and I've been up it's something like this and it's it's it's it's it's no it's it's a privilege and you know how how long it's been about a month or so since I knew that I was going to do this and you know I thought about it some but but but but at a point at a point it goes the thoughts goes away and and I know if you got this face it's positive thinking not this optimistic me that I used to be it's a positive world and living in a positive world creates actions and that's how things get done and and I'm proud to call you guys my family and you know that's what I have and if you want to know me I'll be across the hall thank you my name is Mark.
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <?php include_once 'footer.inc' ?>
    </body>

    </html>