<?php
session_start();  //start or resume an existing session
include_once 'header-top.inc';
echo "<title>2024 A.A. Krystal M. - Transcripción</title>";
echo '<link rel="canonical" href= "https://montereybayarearoundup.org/es/con-2024-krystal.php" >';
include_once 'header-bottom.inc';
?>

<main id="main-content">
    <!-- Hero Part -->
    <div class="container shadow-wrap">
        <div class="row justify-content-center py-6 mb-5 bg-body-tertiary bg-img-audio-trans" title="Retro microphone on a blue background banner">
            <div class="col-xl-7 col-lg-7 col-md-12 py-5">
                <div class="p-3 text-center text-bg-light hero-text-border" title="Audio Speaker Transcript">
                    <h2 class="display-6 fw-bold px-3 px-md-0">Transcripción de Audio: sin editar y sin editar</h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Part One -->
    <article aria-label="Transcript-14">
        <div class="container shadow-wrap">
            <div class="row justify-content-center mb-5">
                <div class="col-xl-10 col-lg-10 col-md-12 py-4">
                    <div class="p-3 text-bg-light hero-text-border">
                        <section aria-label="transcript">
                            <h3 class="text-center p-4">A continuación se muestra una transcripción en bruto en inglés de la grabación de audio de<br>Krystal M. en 2024.<span class="sr-only">(Haga clic para regresar)</span>
                            </h3>
                            <p>Hi, Kristoff and alcoholic. Hello. Hello. Thank you. I'm our committee and everybody who spent this happen over the last, I don't know, definitely a couple decades. So much appreciation. I know how much work goes into these things. And so just a big thank you. I have a sobriety date. It's September 15th, 2014.</p>

                            <p>I said today I have 3,638 days. And I remember what it was like to have 30 days. And I remember what it was like to have 70. And I remember what it was like to have 20. I never wondered what it was like when I got here. And I hope to be you also. I called on to that because that was that moment of clarity for me. So how I got here. Fun. Oh, I have a sponsor and I have some sponsors.</p>

                            <p>I'll talk about them a little bit. But back to me. No, I'm sorry. Please laugh with me. Because I, before I got here, took myself way too seriously. I don't know if anybody else could relate. But I definitely did. And I really like to feel a part of. And I'm nervous. This is great.</p>

                            <p>But I'm just another drunk. I'm just a little bit. I've gathered a couple of 24 hours together. And I'm going to share my experience. My dad brought H and I into my mom's rehab. Followed her around for a couple years. And then I came. So I'm going to say, I'm not going to say any punny jokes. But I did have the honor and privilege of knowing where to go when it was time. And I love that look like for me is that my mom is my mom's side of my family.</p>

                            <p>There's a couple of things that you should know about me. My mom decided that she could drink normally. And I lived with her. So I was given alcohol by my family at the ages of 10, 11, and 12, because it was socially acceptable. I was never told I was going to have spirituality on her session of the mind. I was instructed that if I wanted to drink, I just had to get other things done. Very black and white. I wasn't allowed to talk about feelings. What happens in the South stays in this house? I was to be seen and not heard.</p>

                            <p>And what happened for me is that alcohol was fun and then it was like a survival to me. I needed it to cope with the adults in my life who were not trying to protect me. A lot of physical violence happened in my life. As that progressed, I became the violet one. So at the age of 16, I'm just going to fast forward. At the age of 16, I ended up going through something really horrific. And my dad, oh, I'm going to skip. I never get to tell this story. And I think it's just the best. So I told it yesterday.</p>

                            <p>So it is always been in and out of my life. My dad passed away with 34 years in this program. So he had all of you behind him when he didn't have access to me. And the women in this room said, hey, just send her Christmas cards. Send her birthday cards. I found those cards. And then I confronted my mom. And my mom, when I was 13, basically only had a found to find him at A meetings. So we tracked him down. I paged him when I was 13 because I stood up during the announcement section and somebody just so happened to know where my dad was.</p>

                            <p>So I tell you that story because I've always ended up back here. And started at 13 at 16. I identified for the first time. I sat in your guys' meetings. And I needed a drink to go to bed when I moved in with my father. And what he did for me is he gave me a big book and a 12 and 12 and a basic text and a how a person, why? And he asked me if I wanted to go to meetings every single day. And when I said no, I never got to strife. When I said yes, he would just take me with him. I came to your guys' meetings.</p>

                            <p>You guys patted me on my head. You told me everything was going to be all right. I was 16. Told me to keep coming back. You just listened to my crazy. And he never told me. I never got told at 16 the stuff that I've heard other people say. I was never told to take the cotton out of my ears and put it in my mouth. I drank more than you. Or I've spilled more than you drank.</p>

                            <p>I just kept being told to come back. And I was hugged a lot. That's kind of on the fence nowadays with things of the world. But for me, it was really good for a kid that didn't get hugged a lot. And so from. . . And then I sat in your guys' meetings and this is what I heard. Like you guys got sponsors and you did steps and a higher power. And like, you went to meetings all the time and were like of service.</p>

                            <p>You know, I heard that's what you guys did. But I had lost the hymn to her, the house, the dog. You know? I could not find the similarities. You know, I don't think I was ready. And so I'm in a fast-hort from 16 to 26. I became a very qualified sponsor. That's what I did. I did all the research. I tried all the forms of alcohol.</p>

                            <p>I had like a bucket list. I was in and out of the rooms. I was never told that I needed this, but it was available to me when I was ready. I am grateful for that. Because I did not want to be like you guys. I felt entitled at 16 and threw out the next 10 years. I did not want to end up here. I just did not. And I mean, I'm a part of the DUI club. I have assault charges.</p>

                            <p>There are people that don't ever want to talk to me, see me. I have destroyed lives. I'm a liar, cheat, and a thief. I'm a type of person that would steal your stuff and help you look for it. I am that. I hang out my quality of people that I used to hang out with. I matched them. To the point where at 26 both my parents came to me and I don't know if there's any other parents in the room that might have a child that sounds like me. The best thing that my parents did was cut me off. The tough love saved my life because you should know for 10 years they were my code defendants.</p>

                            <p>I come from a broken hand and I played those strings. And what happened is my dad had all of you and he said, your stuff can stay. You've got to go. My mom let me live in a boarded up trailer inside her house and she finally was like, you can't live here anymore with tears in her eyes because that was my drinking body. You know? I can imagine. I can imagine. I have a 14 year old goddaughter today and she tried to pull anything that I pulled. Oh, go. I struggle because she is just like, I know, within the last three weeks she's pulled some stuff and I get to show up and see if this work is working.</p>

                            <p>You know? But yeah, at 26 I found myself in a moment of clarity and I got the gift of desperation and alcohol stopped working. I was sitting on a couch. Only two people still spoke to me and the person I was living with no longer left to be so cool. And I had this thought and that was September 10th of 2014 that I was going to die or I was going to help because what happens in these meetings, no matter if you sit in them for a month, three months, six months, all those seeds that we plant here, right? The sponsor, the step, the higher power, the service, the meetings, right? Those are all planted. That's what we do here. Now, eventually, hopefully somebody comes along or an experience comes along and waters that and it starts to sprout and you get to stay with us. And that's what happened for me.</p>

                            <p>I got my gift of desperation, alcohol stopped working and I was left my only left choice, which was to come to AA. Wasn't actually to come to AA, it was to go live in a sober living environment in my hometown of Hayward. And so I went there and I paced for like 20 minutes. I don't know if anybody else has thought about doing this thing and like second guest, right? Because I had plenty of examples of this working. Like, that's the silly part. I had plenty of examples. I just did not want to do what you guys did here. I literally thought my life was over at 26. So crazy.</p>

                            <p>So crazy. But I chose and I moved into an SLD with 18 women in one bathroom. That's right. That's right. I had two reservations when I got here that if my dad died, I was going to drink the way that I wanted to drink. And I had two major fears. First was young people's because I just didn't think they had anything to offer me, right? Because I was so mature, so grown. And then women, because I did not trust myself at all. So I was like, not somebody you could trust in your partner or your purse.</p>

                            <p>Like, I just was awful. So I didn't understand why women wanted to be friendly. And in capacity, y'all are so pretty and so nice. I was a shell of a human, right? And I, you know, I hung out in our sister program for a little while. And I got hit by a car and broke my back into spots and ended up in a hospital room. That sucked. My mother came to check on me because she hasn't changed her phone number in 30 years. And she came in for the first time I saw my mom in a different light, which is huge. The cloud had lifted.</p>

                            <p>I had probably about a month's silver and she came in and she said, are you okay? Can I pay your phone bill? And there's nothing big about that statement. The fact that I saw my mom as the best mom that she knew how to be. My mom was always financially provided for me and my brothers. She may not be emotionally available or physically available or mentally available. But financially, she has done so good by us. And I'm so grateful for that. It hasn't proved, by the way, it's been nine years. It's vastly improved.</p>

                            <p>And so I ended up in a hospital room with a broken back. I went back to that SLE and I had this key moment and I called that sponsor, the other program, and I said, hey, I think I'm going to go drink. And she said, I think you should go and check out RA and figure out that is a problem you have. And I was like, okay. And I went to a sponsorship meeting the next day from a childhood friend and this lady who talked about drinking and taking her clothes off. I was like, I want you to sponsor me because that sounds real familiar. I relate. That's what people kept telling me. Like, you should relate to somebody who's your sponsor. And that lady met with me once a week and she is fantastic.</p>

                            <p>I really love you. And she taught me the big book. And she showed me, but I got scared at the four step and I'm going to let you know, the first 14 months, I did the one, two, three shuffle with like three different sponsors. So like me and my relationship to a higher power, to the God, to the divine, to my creator, like the stars were good. I'm never without. I'm not without because I did 14 months of practice. Now, tell you, I don't recommend it because I was starting to do service and like, what happens, I needed a relief. And so the four step is where we start to, don't get me wrong, the third step, very big action. Right? That is a action step.</p>

                            <p>That's what we start. The pen to paper and four is, this thing just seemed like the biggest mountain. And I had a guy at my home group who basically came in and was like, come, I'm going to, you're going to listen to these tapes with me and my wife. And we're going to just like have family dinner and I'm going to show you how to write a four step. So I listened to Joe and Charlie tapes for two weeks. I learned how to write a four step. And next thing you know, I was dropping a fifth step with him and his wife. And they kind of co-sponsored me because they were the parents that I needed and that kind of dynamic. And if you have a problem with this, you do not have to tell me after this meeting. Please don't.</p>

                            <p>I got nine years. It's okay. Okay? Okay. Okay. Okay. But I also had some things on my first fifth step that unfortunately some women in the program told me that wasn't my experience. And that was hard. But I luckily had this man who said, okay. Yeah.</p>

                            <p>We can't, that's not that bad. It was bad. I wasn't that bad to him. And to have my shoulder strapped and to feel seen, not alone, and to feel free, that I'm not the only person that me myself created. It changed my life. To be, to not, I judge myself so deeply. And I am so hard on myself for the things that I have done. I was an awful person, and I am not that person today, but to be able to share that with somebody without judgment, it's obviously been that thing that's always saved my life for the longest. I can tell this man anything, and he just kind of laughs. So I'm grateful.</p>

                            <p>I have then thus told other people about this experience. But I will tell you over the next, we did like a rapid fire. I dropped up fifth step, and I was like, get me to my immense, we're gonna do some six and seven stuff. Eight, wrote my list. Nine was on the prowl. I was trying, you know? And this relationship with my father was really important to me, you know? And I'd set up an immense, like, date with him, you know? And by the way, you should know, throughout this process, I got involved with young people's. I went to a camp town.</p>

                            <p>I didn't know anybody. I cried in front of them. They said, here you get a walkie-talkie, and a vest, and a parking lot, park cars. I felt like a maximum service because I love cars, and I love to be in charge of things. That's what I did. And so then all of a sudden, I joined this young people's group called Abi-ka, and I had immersed myself in young people. I had also immersed myself in this women's meeting because I had a sponsor saying, you can only go to women's meetings for a month until you get over the sphere. And I'm grateful that was my home group for six years was this women's meeting, and they were, love them, still some of the best women, they saved my life. And so I got connected with women, and I'm doing the young people's thing, and I'm off to do my amends, and you would think I'd do it all this cool service, right, and I'm doing it, and I celebrate 18 months, and my dad dies the next day. Yeah.</p>

                            <p>And luckily on the fourth step, I wrote about my fear, right? And I write about actual fear. I don't know about anybody else, but I'm like, fear of success, fear of failure, but like fear of death, like especially because of that reservation, you know? And my sponsor luckily had a, we came up with a game plan. Actually, he talked me through the game plan, and luckily that stuck in my head, and so I got this phone call, and I got to scream because he said I could scream, and then I called him. And then our plan was that I was just gonna take suggestions from other people in the program on what I should do and not question it, because our program is suggestion based. Like, you don't have to take all of them, but like, you kind of gotta, you know, get out of your own way. It's worked in my opinion. My best thinking got me here, so like, I'm gonna let you guys guide me, you know? And and I got to walk through that process.</p>

                            <p>I didn't get to make that immense to my dad in life, but I did get to make it to his body two days later. I got the unique experience of that, and I got to deal with my step-mom, who was an active addiction, and I got to have all the correct paperwork, and then that young people's group came and helped me put on that celebration of life for him, and I got to stand up there in front of 80 people of no-blood relation because my dad passed away with 34 years in this program. So I have had my spiritual experiences that have kept me here, I've been rooted in big moments of pain, and having the perspective change and the awareness that y'all are the ones that show up. So I'm in constant, constant repayment, but I want you to know that the reason that y'all just show up is because closed maps don't get fed. I don't get to sit in meetings or outside of the meetings, or like, I don't get to sit around here and get anything from you guys unless I open my mouth. I am not a mind reader, I wish I was because some of you guys be struggling quietly, and we want to help. We want to show up. Tush. But y'all be spreel selfish. Maybe we work on that, especially all of you guys that laughed because you're the ones who are hiding.</p>

                            <p>But yeah, so I got to walk through that experience, and then these young people's, right? So they showed up, they did this thing, and I was like, wow, I didn't have friends like this when I was drinking in any capacity. So they were like, hey girl, we need you to come to this Akihara conference. It's in Orange County, and I was like, my dad just died. I don't want to go. And they were like, nah, you got to go. So I go, and we get awarded the conference, this e-spit conference, okay? This Akihara conference. And I had this lady who's known me for some time, and she said, I think you should be color-based. And I was like, mm, okay, sure.</p>

                            <p>I really want to merge, but I'll be COB, I'll be COBents. And then our bench chair dropped, so guys with other events. That was me. And next, I'm announced to me, Alcoholics Anonymous swooped me in. They said, oh, we got you now. So for the next year, as I was processing my father's debt, I was organizing you kittens to host the event, and then trying to get you kittens to the event. Um, because if you ever tried to herd kittens, that's what it's like without politics. And so I got to do that. I was, um, stressed and overwhelmed. And then I was like, so quiet on the inside.</p>

                            <p>I was so numb. And I wish I could say that like I finished those events, and then I like, no, I knocked it out. I knocked it out. I wanted my sponsor for the next two months, because I didn't want to do any more stuff work. I wanted to go and do crystals program. And then I was like organizing these like alcoholics, and I was like, oh, this is going to get really bad. I'm going to physically harm someone. So I showed up at his house, and you know what this man had the audacity to tell me that our meetings don't just help me out. Ah. He was like, what is it?

                            <p>What are you going to realize that you are loved? It's still a hard concept. It's still hard to love them. Like you, you do the work and many help others. And then I think, and it just might be me, but it just really has been so handy. But I am worthy of your love. I am overpaid in this program. Very much. So I joined this faculty balcony, and then a year later I got to the Cali Corps on Friday night in front of 2000 of my peers, and I knew exactly that was where my dad wanted me to be. And so since then I've been involved in young people's and alcohol, it's anonymous.</p>

                            <p>I'm here to tell you, I've done rounds of step work because I want to be better than I was yesterday. I've done everything wrong. I backed it out in all the wrong ways. I just happened during. I don't do a consistent 10 or 11. Sometimes I avoid six and seven, okay? But I never forget about 12. I just don't. Because sponsorship has been the best gift for me. I started really sponsoring prior to COVID.</p>

                            <p>I had like three sponsorsies, and I've done a lot of other things in alcoholics, anonymous, like I've moved and I've switched jobs and stuff like that, and like step work is helping get through that. Sponsorship is where I figured out my real character defects and how important I am, and how much walking through hard things can be useful to people later. Okay, we're good. And so I'm just, I'm just checking. But sponsorship is, my sponsor is the first person that I learned how to trust, obviously, what I told you guys about rape. And I realized that I get to be the first person somebody trusts, and that is an honor and privilege. On page 95, in the big book, it says that we offer them friendship and fellowship. When I learned that like I needed to, like anything that's gonna drop a fist step with me, probably should end up my friend, because those were some big secrets. And when I tried to start treating this more of like a lifestyle, then a textbook or, you know, job, I felt more comfortable in it. You know, it's just one alcohol that's helping another, and like there needs to be some kind of comfortability.</p>

                            <p>That's kind of how I like to do my sponsorship. Like I would be like to tell you that my sponsor is to turn into like family or friends. And even if they move on, like I love you enough to hurt your feelings, but I also love you enough to let you go, you know? If you can no longer take my suggestions, please move on to the next person. You'll probably help save them for their next chapter, you know? And I get to sponsor people, and they save me through COVID. I sponsor some of my friends. It's weird and wild and so beautiful, because they can't hide. I already know all their stuff. I was there.</p>

                            <p>I also know the other person signed, so what's up? You know? And most recently I got to do this really big thing. I got to, I want to touch on my last service opportunity and then, you know, figure it out. We'll go dance later, yeah? But most recently I had the opportunity of bidding for the International Conference of Young People. And then I got to host last year in Seattle, Cisco. I was the chairperson. Woo! Woo!

                            <p>Woo! Yeah! Yeah! Yeah! I was the chair of the bid, and then I got to be the chair of the conference because I picked out a how. And that's fun. And so that was two years of chairing. And I got to learn some really big things about me. Like, I love business meetings, but I really enjoy background work. I don't want to be in charge anymore.</p>

                            <p>And it is capacity. This is also nerve-wracking, you know? But I will tell you that, like, I met some really amazing people. I'm moving to Boston in two weeks. I have a family across the West Coast, and now I'm going to span to the East Coast. And I got to look at all of my character defects through that service opportunity. I was not the best chair. The conference happened. I got to correct some of that behavior. And like, people still talk to me about that conference a year later.</p>

                            <p>And they don't even know that I was in that chair. Because we don't do these conferences for ourselves. Yeah? We do them for fun and for free. And we help that you meet some friends along the way. And I help those friends build into the tribe you need for your money for their days. So, yeah. You know, I talked about the steps. Didn't really talk about the traditions, but that's okay. You're responsible for that.</p>

                            <p>We've laughed a little bit, you know? And you've gotten to know me. And I really appreciate this opportunity. And I hope that, you know, closed mask don't get fed, but it should be something you leave this with. Okay? There is always a spot for you in service in whatever program you're in. Okay? Because I love you, I have an ounce. Absolutely. Very grateful for you.</p>

                            <p>And like, if you don't want to call your sponsor with the good, the bad, the ugly, get a new sponsor. It's okay. It's okay. Because the one thing we get to be selfish about is her program. It's around. Okay? Find the freedom that you are craving. And I hope that you also get to stay and help others. So if you haven't treated yourself to a runny steps, please do. I love horseback.</p>

                            <p>Thank you.</p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <?php include_once 'footer.inc' ?>
    </body>

    </html>