<!-- Part Registration -->
<article aria-label="información de registro y enlace">
    <div class="container shadow-wrap">
        <div class="row justify-content-center mb-5">
            <div class="col-xl-8 col-lg-8 col-md-12 py-4">
                <div class="p-3 text-center text-bg-light hero-text-border" title="¡La inscripción ya está abierta!">
                    <h3 class="fw-bold text-primary px-3 px-md-0"><span class="text-dark px-3 px-md-0">¡Prepárate para MBAR este fin de semana del Día del Trabajo!</span>
                    </h3>
                    <p class="h3 text-dark">Reunión Virtual de Lanzamiento por Zoom</p>
                    <p class="dark-text">30 de Agosto a las 8:00pm PDT
                        <br>
                        Orador: Oliver D. de Delaware
                        <br>
                        ID de la reunión: <strong>831 4306 2293</strong>
                        <br>
                        Código de acceso: <strong>2024</strong>
                        <br>
                        ¡Esta reunión está abierta a todos y te animamos a que te unas!
                    </p>
                    <p class="h3 text-dark">Reuniones Presenciales</p>
                    <p class="dark-text">31 de Agosto y 1 de Septiembre en el Centro de Conferencias de Monterey
                        <br>
                        Tenga en cuenta que es necesario registrarse para el evento presencial. ¡Asegúrese de registrarse con anticipación!
                    </p>
                    <a href="register-now.php" class="btn btn-primary mb-2">Regístrese Ahora</a>
                    <p class="dark-text mb-6">Esperamos contar con su participación en ambas sesiones. ¡Hagamos que este MBAR sea un gran éxito!</p>
                </div>
            </div>
        </div>
    </div>
</article>

<a href="#toTop" class="btn btn-primary back-to-top" id="back-to-top-link" title="Volver Arriba" aria-label="Volver Arriba"><i class="bi bi-arrow-up" aria-hidden="true"></i></a>

</main>


<div class='container top-footer'>
    <aside aria-label="declaración de responsabilidad">
        <div class=" row justify-content-md-center">
            <div class='col-sm-4 banner'>
                <img src="../images/mbar_logo.png" class="img-fluid rounded-top" alt="Logotipo de Monterey Bay Area Round Up 2024 con una cola de ballena con pantalones y el lema: Mantenlo Simple.">
            </div>
            <div class='col-sm-8 col-md-6 p-4'>
                <h4>Nuestra Declaración de Responsabilidad:</h4>
                <p class="h4">Yo soy responsable.<br>
                    Cuando alguien, en cualquier lugar, pide ayuda, quiero que la mano de AA esté siempre ahí.<br>
                    Y de eso soy responsable.
                </p>
            </div>
        </div>
    </aside>

    <aside aria-label="grupo privado de facebook">
        <div class="row justify-content-md-center">
            <div class="col-sm-12 col-md-10 shadow text-center">
                <hr>
                <h4 class="text-center"><strong>Unirse <a href="https://www.facebook.com/groups/MBAR2021/" target="_blank" rel="noopener noreferrer nofollow">
                            <img src="../images/facebook_logo.png" width="40" alt="Logotipo de Facebook para grupos privados de A.A. miembros."><span class="sr-only">(Abre una nueva ventana)</span></a> Grupo Privado</strong></h4>
                <hr>
            </div>
        </div>
    </aside>
</div>

<footer>
    <div class='container'>
        <div class="row justify-content-md-center">
            <div class="col-sm-12" id="footer-image" role=img aria-label="Un camino a través de colinas, cubiertas de flores, con una puesta de sol como telón de fondo.">
                <p>Copyright © <?php echo date('Y'); ?> Reunirs del Área de la Bahía de Monterey. Reservados todos los derechos.
                </p>
            </div>
            <nav class="navbar navbar-expand-sm bg-dark border-bottom border-body" data-bs-theme="dark" aria-label="menú de pie de página">
                <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link nav-link-size" href="accessibility.php">Accesibilidad del Sitio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-size" href="privacy-policy.php">Política de Privacidad</a>
                    </li>
                    <li class="nav-item" style="border-right: none;">
                        <a class="nav-link nav-link-size" href="sitemap.php">Mapa del Sitio</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</footer>

<!-- Bootstrap JavaScript Libraries -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

<script src="../js/backToTop.js"></script>