<!-- Part Registration -->
<article aria-label="información de registro y enlace">
    <div class="container shadow-wrap">
        <div class="row justify-content-center mb-5">
            <div class="col-xl-8 col-lg-8 col-md-12 py-4">
                <div class="p-3 text-center text-bg-light hero-text-border" title="¡La preinscripción está abierta!">
                    <h3 class="fw-bold mb-3"><span class="text-dark px-3 px-md-0">Únete a nosotros en MBAR 2024</span>
                    </h3>
                    <p class="mb-6 h4 text-dark">Fin de Semana del Día del Trabajo, 31 de Agosto y 1 de Septiembre</p>
                    <a href="register-now.php" class="btn btn-primary me-2">Regístrate Ahora</a>
                </div>
            </div>
        </div>
    </div>
</article>

<a href="#toTop" class= "btn btn-primary back-to-top" id= "back-to-top-link"><i class="bi bi-arrow-up" aria-hidden="true"></i> Volver Arriba</a>

</main>


<div class='container top-footer'>
    <aside role="complementary" aria-label="declaración de responsabilidad">
        <div class=" row justify-content-md-center">
            <div class='col-sm-4 banner'>
                <img src="../images/mbar_logo.png" class="img-fluid rounded-top" alt="Logotipo de Monterey Bay Area Roundup 2024 con una cola de ballena con pantalones y el lema: Mantenlo Simple.">
            </div>
            <div class='col-sm-8 col-md-6 p-4'>
                <h4>Nuestra Declaración de Responsabilidad:</h4>
                <p class="h4">Yo soy responsable.<br>
                    Cuando alguien, en cualquier lugar, pide ayuda, quiero que la mano de AA esté siempre ahí.<br>
                    Y de eso soy responsable.
                </p>
            </div>
        </div>
    </aside>

    <aside role="complementary" aria-label="grupo privado de facebook">
        <div class="row justify-content-md-center">
            <div class="col-sm-12 col-md-10 shadow text-center">
                <hr>
                <h4 class="text-center"><strong>Unirse <a href="https://www.facebook.com/groups/MBAR2021/" target="_blank">
                            <img src="../images/facebook_logo.png" width="40" alt="Logotipo de Facebook para grupos privados de A.A. miembros."><span class="sr-only">(Abre una nueva ventana)<span></a> Grupo Privado</strong></h4>
                <hr>
            </div>
        </div>
    </aside>
</div>

<footer role="contentinfo">
    <div class='container'>
        <div class="row justify-content-md-center">
            <div class="col-sm-12" id="footer-image" alt="Un camino a través de colinas, cubiertas de flores, con una puesta de sol como telón de fondo.">
                <p>Copyright © <?php echo date('Y'); ?> Reunirs del Área de la Bahía de Monterey. Reservados todos los derechos.
                </p>
            </div>
            <nav class="navbar navbar-expand-sm bg-dark border-bottom border-body" data-bs-theme="dark" role="navigation" aria-label="menú de pie de página">
                <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link nav-link-size" href="accessibility.php">Accesibilidad del Sitio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-size" href="privacy-policy.php">Política de Privacidad</a>
                    </li>
                    <li class="nav-item" style="border-right: none;">
                        <a class="nav-link nav-link-size" href="sitemap.php">Mapa del Sitio</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</footer>

<!-- Bootstrap JavaScript Libraries -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

<script src= "../js/backToTop.js"></script>