
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">

    <!-- Bootstrap CSS v5.3.2 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">

    <link rel="stylesheet" type="text/css" href='../css/styles.css'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <!-- reCAPTCHA widget -->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>


    <!-- https://datatables.net/ -->
    <link href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet">

</head>

<body id="toTop">
    <a href="#main-content" class="btn btn-primary btn-skip" aria-label="Ir al Contenido Principal">Ir al Contenido Principal</a>
    <header class='container'>
        <div class="row justify-content-md-center pt-5 pb-3">
            <div class='col-sm-4 banner'>
                <h1 class="text-uppercase">Monterey Bay Area Roundup</h1>
                <p>P.O. Box 1462<br>Monterey, CA 93942</p>
                <p>Ver a las personas recuperarse, verlas ayudar a los demás, ver cómo se desvanece la soledad, ver crecer un compañerismo a tu alrededor, tener una gran cantidad de amigos: <span class= "font-italic">esta es una experiencia que no debes perderte</span>.<span class='sr-only'>(Este es texto plano)  - esta es una experiencia que no debes perderte.</span></p>
            </div>
            <div class='col-sm-auto banner'>
                <img src="../images/mbar_logo.png" class="img-fluid shadow-wrap" alt="Logotipo de Monterey Bay Area Roundup 2024 con una cola de ballena con pantalones y el lema: Mantenlo Simple" title="Logotipo de Monterey Bay Area Roundup 2024 con una cola de ballena con pantalones y el lema: Mantenlo Simple">

            </div>
        </div>
    </header>