<div id="march2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            Notas del Comité MBAR 2024
            <br>ID de Zoom 831 4306 2293 Contraseña 2024
            <br>Sábado 9 de Marzo de 2024 a las 10h
            <br><a href='/es/' class="bb-link">montereybayarearoundup.org/es/</a>
        </p>

        <dl>
            <dt>1. Llamada al orden del presidente: 10 a.m.;</dt>

            <dt>2. Lectura de las 12 Tradiciones: Phil C.;</dt>

            <dt>3. Nuevos asistentes, pongan sus números de teléfono y direcciones de correo electrónico en el chat: Diane C., Kat G.(Susan S.);</dt>

            <dt>4. ¿Hay algún miembro de A.A. ¿O los aniversarios de Al-Anon desde nuestra última reunión? Ninguno;</dt>

            <dt>5. Aprobar/Modificar Acta de la última reunión: Aprobada;</dt>

            <dt>6. Informe del presidente - Chris T.: Muchas gracias a todos por su asistencia, servicio y apoyo. Su presencia aquí significa mucho y quiero asegurarles que los presidentes de los comités han trabajado arduamente para garantizar que hayamos traducido los formularios y el sitio web al español para facilitar la accesibilidad, facilitar la inscripción en línea, agilizar la información de inscripción para el presidente de inscripción y organizar la representación en los eventos de AA para captar la inscripción anticipada.
                <br><br>
                Es importante que arreglemos la votación sobre el estilo de las camisetas en esta reunión para que los que se inscriban temprano tengan la oportunidad de elegir una camiseta si así lo desean, de modo que nuestro presidente de inscripción pueda dar una idea de las camisetas necesarias para que no terminemos con un excedente excesivo.
                <br><br>
                Después de la reunión de hoy y nuestro evento del Día de San Patricio, podemos centrarnos más en dar forma a la Conferencia y tener discusiones sobre la mejor manera de servir a nuestra Comunidad.
                <br><br>
                He podido ponerme en contacto con nuestro presidente de Al-Anon y fue fantástico participar en su cena de oradores de Al-Anon/AA. Realmente tienen a MBAR al frente de sus conversaciones de fraternidad, y no veo la hora de poder hacer las mismas conexiones con nuestra comunidad de habla hispana y la fraternidad de jóvenes que está creciendo en nuestra área.
                <br><br>
                Necesitamos cubrir los siguientes puestos: Eventos;
            </dt>

            <dt>7. Informe del Tesorero - Jean T: Ver hoja de cálculo del presupuesto adjunta; Saldo actual $22,391 incluye inscripciones, bingo, etc.; Incluye 20 registros; Reserva Prudente Inicial $15,464; La recaudación de fondos totaliza $10,776;</dt>

            <dt>8. Séptima Tradición: Puede hacer una contribución a la Séptima Tradición - PayPal en mbartreasurer@gmail.com o enviando un cheque a - MBAR, PO Box 1462, Monterey, CA 93942; O Venmo: @MBARoundup24 (<em>Nota:</em> Venmo y el cheque van 100% al Tesoro, PayPal cobra una tarifa).</dt>

            <dt>9. Presidentes de comités/informes del comité directivo</dt>

            <dd>a. Medios - Gina: René traduciendo varios documentos al español;</dd>

            <dd>b. Registro - Naomi: 13 registros totales recibidos; Ocho de las 20 inscripciones pagadas reportadas por tesorero; Cinco inscripciones gratuitas - concurso de logotipos y premios de rifa; Trabajando en el proceso de registro en línea; Al-Anon se ofreció a ayudar; Chris animó a todos los miembros del comité a registrarse;</dd>

            <dd>c. Español - Robert: Revisando la traducción al español del formulario de inscripción, etc.;</dd>

            <dd>d. Al-Anon - Jane: Los tres oradores se alinearon; Iniciar reuniones la próxima semana; Comités reunidos;</dd>

            <dd>e. Camiseta - Kevin: Maquetas preparadas por Mica; Necesidad de reforzar el costo de las camisetas; Necesita orientación sobre tazas de viaje, botellas de agua, gorras, etc.;</dd>

            <dd>f. Orador - Kathleen: Sin informe;</dd>

            <dd>g. Divulgación - Conor: Anuncio del día de San Patricio; Se comunicó con las oficinas centrales de Monterey, San Francisco, Los Ángeles; Planee asistir a las reuniones de Salinas: solicitó comentarios sobre las reuniones que cuentan con una buena asistencia; Christina recordó a los miembros del comité que todos tenemos alguna responsabilidad en materia de divulgación;</dd>

            <dd>h. I.G.R. / G.S.R. - Cole: Anuncio de MBAR en las reuniones del comité;</dd>

            <dd>i. Instalaciones: Sally: No hay informe; patrón de espera por ahora;</dd>

            <dd>j. Sitio web - Phillip: El cumplimiento de la accesibilidad del nuevo sitio web (ADA) está casi completo; Trabajando en la configuración del proceso de registro - Dinero al tesorero; Formulario de inscripción al presidente de inscripción; Obtenga el formulario de Google de René; Actualización del proceso de pago; Configuración de página en español; Tarifas de renovación de dominio de dirección, alojamiento web, etc.; Trabajando en la página de Al-Anon; René coordina la traducción al español; </dd>

            <dd>k. Rifa - Katherine: $715 de Bingo 50/50; Chris (copresidente) necesita voluntarios para ayudar con la rifa del Día de San Patricio; Agregar comité para el día de San Patricio; May se ofreció a ayudar con la rifa;</dd>

            <dt>10. Asuntos antiguos:</dt>
            <dt>Recaudación de fondos</dt>

            <dd>a. Día de San Patricio, domingo 17 de marzo: consulte el folleto adjunto en la invitación; Casa de la piscina Phil C.; Hora del evento: 4 a 7 pm; Configuración: 13:00 horas; Orador: Avail L; Comida: Matt R. y Helpers; Rifa: 50/50 y Premios; Katherine necesita ayuda: venta de entradas, sorteo de premios; Utilice jarrones MBAR para comprar boletos; decoraciones René; Platos, servilletas y cubiertos cubiertos; Voluntarios: Diane, Sydney, May, Conor y varias personas en el chat;</dd>

            <dt>Encuesta de camisetas sobre el estilo y color de las camisetas MBAR</dt>

            <dd>a. Camisetas para los asistentes: Manga corta; azul marino con logo blanco y dorado - diez personas - aprobado; Manga corta, azul marino con logo blanco - nueve personas; Camisetas del comité, jersey, blanco y azul - aprobadas.</dd>

            <dt>11. Nuevo negocio:</dt>
            <dt>Café proporcionado en MBAR 2024: </dt>

            <dd>a. Servicio de café en el Monterey Conference Center: un galón de café o té (16 tazas de 8 onzas) equivale a $80; Con Impuestos y Propina - $108.75; 100 personas - Café por la mañana: 5 a 6 galones de café normal y 2 galones de té; Café PM: cuatro galones (café y té); Total: aprox. 12 galones por día; (Se estima que casi todo el mundo tomaría al menos una taza, y poco menos de la mitad de las personas tomaría dos tazas durante todo el día); El café a 50 galones por día costaría $5,437.50 por día; 500 personas serían 60 galones por día; Total: $6,525.00 por día; Durante dos días, aprox. 10.000 dólares para café; Cuando lleguemos a esa cantidad, retiramos el café; Sería aprox. 92 galones para los dos días; <strong>Acuerdo unánime para rechazar la propuesta de café por valor de 10.000 dólares.</strong></dd>

            <dd>b. Amplia discusión sobre la Marriott Hospitality Suite: Presupuesto de $2K - Phil obtiene un descuento - es necesario reservar con anticipación; Kathleen se ofreció a abastecerse de alimentos y café; Moción para aprobar la suite Marriott Hospitality con café según lo presupuestado - aprobada; Resuelva los detalles en la próxima reunión y determine si es necesario ajustar el presupuesto;</dd>

            <dt>12. La próxima reunión del Comité Directivo es el martes 26/03/2024 a las 6pm a través de Zoom;</dt>

            <dt>13. La próxima reunión del Comité es el sábado 13/04/2024 a las 10 a.m.;</dt>

            <dt>14. La reunión finalizó a las 11:15 am con la Oración de la Serenidad;</dt>
        </dl>

        <p> Asistentes: Andy, Chris, Cindy, Conor, Dawn, Diane, Jane, Janet, Jean, Kathleen, Katherine Ann, Kathleen S., Kevin, Mary Grace, Mary H., Naomi, Phil, Phillip, Renee, Sally H., Susan S. y Roger;</p>

    </div>
</div>