<div class="accordion-item">
    <h4 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
            <i class="bi bi-book me-2" style="font-size: 1.5rem; color: var(--color-8);" aria-hidden="true"></i><strong>2020</strong>
        </button>
    </h4>
    <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body d-grid gap-3">

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2020/12-12-20.pdf">Abre un PDF: 12/12/2020</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2020/11-14-20.pdf">Abre un PDF: 11/14/2020</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2020/10-10-20.pdf">Abre un PDF: 10/10/2020</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2020/9-12-20.pdf">Abre un PDF: 09/12/2020</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2020/8-8-20.pdf">Abre un PDF: 08/08/2020</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2020/7-11-20.pdf">Abre un PDF: 07/11/2020</a>
        </div>
    </div>
</div>