<div id="august2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            Notas del Comité MBAR 2024
            <br>ID de Zoom 831 4306 2293 Contraseña 2024
            <br>Sábado 10 de Agosto de 2024 a las 10am
            <br><a href='/' class="bb-link">montereybayarearoundup.org/es/</a>
        </p>

        <dl>
            <dt>1. Llamado al orden del Presidente: 10 a. m.;</dt>

            <dt>2. Lectura de las 12 Tradiciones: Gina;</dt>

            <dt>3. Nuevos asistentes, coloquen sus números de teléfono y direcciones de correo electrónico en el chat: Ninguno;</dt>

            <dt>4. ¿Hay algún aniversario de A.A. o Al-Anon desde nuestra última reunión? Ninguno;</dt>

            <dt>5. Aprobar/Enmendar las actas de la última reunión: Aprobadas;</dt>

            <dt>6. Informe del Presidente - Chris T.: Como recordatorio, de acuerdo con la votación realizada por el comité, ahora nos reunimos semanalmente antes de la
                Conferencia. Esta reunión se realizará semanalmente y durará de 1 a 1,5 horas, ya que tenemos temas urgentes para discutir y aprobar;
                <br><br>
                Puntos de discusión/aprobación del comité: los siguientes puntos necesitan consideración, retroalimentación o aprobación por parte del comité, ya que pueden tener costos, planificación y su aporte para finalizar;
                <br> - Cantidad de paquetes de rifa y precio de boletos;
                <br> - Actualización y propuesta de la sala de hospitalidad;
                <br> - Se necesita ayuda del presidente de decoraciones;
                <br> - Voluntario de cuenta regresiva (dos personas): la ejecución de esto sigue una plantilla de conteo y también está
                frente a todos mientras se realiza la cuenta regresiva;
                <br> - Lectores de secretarios de reuniones para que Naiomi los agregue al cronograma: Deberíamos tener una variedad y participación del comité;
                <br><br>
                ¡Gracias de antemano por su participación y apoyo, realmente nos estamos acercando a tiempos emocionantes y felices por delante!
            </dt>

            <dt>7. Informe del Tesorero - Carolyn H.: Ver la hoja de cálculo del presupuesto - La suite de hospitalidad y el ASL cambiarán: 31 registros en línea esta semana, 133 en línea en total; Saldo $35,609; Varias inscripciones - el pago no coincide con la inscripción; El pago anticipado no pagado se respetará al recibir el pago reducido; Mercancía: Moción aprobada - El costo de la botella de agua es de $9.99 - cargo de $10.00; El costo de las tazas es de $18.25 (reducido a $14 con la compra adicional de 72 tazas por parte de Carolyn) - cargo de $15; Contrato de AV firmado;


            <dt>8. Instalaciones de Mark: Se solicitó el diseño de la instalación a Cody - Mark comparte los mapas de diseño con el comité; Los presidentes del comité envían un correo electrónico a Mark con cualquier solicitud de instalación; Planificar otro recorrido - Chris y Mark se coordinan; El comité de rifas le informa a Mark cuántas mesas de premios se necesitan; <strong>Nota</strong>: Al-Anon no realizará una rifa o 50/50, solo la subasta silenciosa;

            <dt>9. Paquetes de Rifa - Katherine: Moción aprobada - boletos de rifa de paquete y boletos de paquete 50/50: 6 boletos a $5; 12 boletos a $10; 25 boletos a $20; Discusión extensa sobre la subasta silenciosa - No habrá subasta silenciosa de AA; Posibles problemas impositivos con la subasta silenciosa de Al-Anon: <strong>Carolyn en el registro - se opuso <em>firmemente</em> a la subasta silenciosa</strong>; Considere una redacción alternativa "regalo de subasta silenciosa"; Jane: la subasta se realizó con frecuencia en MBAR anteriores; Carolyn: verifique el umbral para los formularios 1099;
                <br>Moción - Aprobada; y se volvió a votar Aprobada: Permitir que Al-Anon proceda con la subasta silenciosa - Jane (Al-Anon) - programe una reunión con Carolyn (tesorera de A.A.) y Thomas (tesorero de Al-Anon) y Harry para analizar las posibles opciones para cumplir con los requisitos del código impositivo;
            </dt>

            <dt>10. Sala de Recepción: Hyatt - La habitación es de cortesía y el café puede ser de cortesía; el precio aún no está confirmado; debe estar dentro del presupuesto; la habitación es un espacio de reunión; hay baños ADA cerca; Centro de conferencias proporcionará estaciones de efectivo y para llevar - Sin costo para MBAR; las personas pagan por lo que usan;
                <br>Moción aprobada - Suite de hospitalidad para oradores, panelistas y miembros del comité y otras personas importantes solamente;
                <br>Moción aprobada - Jennifer instalará la suite de hospitalidad junto con efectivo y para llevar;
                <br>Moción aprobada - No habrá letreros que dirijan a las personas a la suite de hospitalidad; los paquetes de inscripción para oradores, panelistas y miembros del comité y otras personas importantes tendrán instrucciones en su paquete de inscripción; Jennifer agregará letreros en la sala;
                <br>Moción aprobada - No habrá frasco de donaciones en la suite de hospitalidad;
            </dt>

            <dt>11. Decoraciones - Se necesitan voluntarios: Áreas para decorar - Área principal del Centro de conferencias; Eventos; No hay decoraciones en el escenario de los oradores; Voluntarios: Jennifer presidirá; Gina; Esther; comprará dulces y flores;
            </dt>

            <dt>12. Cuenta Regresiva del Sábado: Se necesitan voluntarios - Carolyn; Arthur;
            </dt>

            <dt>13. Presidentes de la Reunión: Envíen la lista de lectores a Naomi;
            </dt>

            <dt>14. Informes de los Presidentes de los Comités y del Comité Directivo</dt>

            <dd>a. Sorteo - Katherine: Sorteo en el escenario después de la reunión del sábado; determinar el mejor enfoque para acelerar el proceso;
                <br>Moción aprobada: boletos para el sorteo previo y Publicación sobre premios;

            <dd>b. Medios - Gina: se anunciará;

            <dd>d. Camisetas - Kevin: no hay problemas; se ordenaron tazas y botellas de agua; se necesita dotar de voluntarios a la mesa de ventas; Jean confirmó que habrá una caja de efectivo disponible;

            <dd>e. Hospitalidad - Jennifer: no hay nada que agregar;</dd>

            <dd>f. Oradores - Kathleen: se está trabajando en las canastas de regalo; Cindy enviará una lista de secretarias para las reuniones de oradores con formatos actualizados; <br>Moción aprobada: comprar un dispositivo de grabación para grabar las reuniones;</dd>

            <dd>g. Cena - Aubrey: no hay actualizaciones;</dd>

            <dd>h. 50/50 - Cole: al final de la reunión del sábado; se debe determinar si hay dos ganadores para la inscripción anticipada 50/50;</dd>

            <dd>i. Registro - Naomi (informe de Chris): 124 en línea - 10 incompletos; 207 en total - 124 en línea; 83 en papel; 60 paquetes; 67 cenas; 56 desayunos; 55 helados; 81 camisetas; 10 fuera del estado;</dd>

            <dd>j. Mercancía - Kevin: No hay informe;
                <br>Moción aprobada - nueva votación aprobada: Venta anticipada de mercancía - Vender solo tazas de café a los miembros del comité antes de la conferencia; Usar también como marketing;
            </dd>

            <dd>k. Baile y Eventos - Samantha: El baile está en la sala Steinbeck; 56 inscripciones para el desayuno; 48 bingos; Pedir más si es necesario; Todo listo para los eventos;</dd>

            <dd>l. Al-Anon - Jane: Organizar una reunión con Carolyn (tesorera de A.A.), Thomas (tesorero de Al-Anon) y Harry para analizar las posibles opciones para cumplir con los requisitos del código fiscal; Christine: No hay cambios en la Subasta Silenciosa de Al-Anon 2024 - Transmitir inquietudes sobre futuras subastas silenciosas;</dd>

            <dd>m. Difusión - Conor: Buscando una lista de oradores; Continuar promoviendo activamente la conferencia; Mesa en Coastal Rally - Mark S. ayuda;</dd>

            <dt>14. Difusión:</dt>

            <dd>a. Coastal Rally</dd>

            <dt>15. Nuevos Asuntos: Ninguno;</dt>

            <dt>16. La próxima reunión del Comité es el Sábado 17/08/2024 a las 10am; Las reuniones posteriores serán todas las semanas hasta la fecha de la conferencia;</dt>

            <dt>17. La reunión se levantó a las 12:15pm con la Oración de la Serenidad.</dt>
        </dl>

        <p> Asistentes: Arthur, Aubrey, Carolyn, Chris, Cindy, Cole, Conor, Esther, Gina, Jane, Janet, Jean, Katherine, Kathleen, Kevin, Mark F., Mark S., Mary Grace, May, Phil C., Renee, Roger y Samantha.</p>
    </div>
</div>