<div id="july2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            Notas del Comité MBAR 2024
            <br>ID de Zoom 831 4306 2293 Contraseña 2024
            <br>Sábado 13 de Julio de 2024 a las 10h
            <br><a href='/es/' class="bb-link">montereybayarearoundup.org/es/</a>
        </p>

        <dl>
            <dt>1. Llamado al orden del presidente: 10am;</dt>

            <dt>2. Lectura de las 12 Tradiciones: Cole;</dt>

            <dt>3. Nuevos asistentes, coloquen sus números de teléfono y direcciones de correo electrónico en el chat: Jennifer;</dt>

            <dt>4. ¿Hay algún aniversario de A.A. o Al-Anon desde nuestra última reunión? Samantha 7 años;</dt>

            <dt>5. Aprobar/enmendar las actas de la última reunión: Aprobadas con modificaciones;

            <dt>6. Informe del presidente: Chris T.: ¡Gracias a todos por su continuo apoyo y asistencia a nuestra reunión de planificación! Estoy deseando conocer los informes del comité y el resumen de lo que el subcomité pudo conseguir para los oradores. Esta agenda de reuniones será muy importante desde el principio, ya que tenemos varios puntos que requieren la atención y el apoyo de todo el comité en los próximos meses, ya que MBAR 2024 se acerca rápidamente. <br><br>
                Como se discutió y votó en el Comité, esta reunión durará 1,5 horas y, como nos embarcamos en varias tareas, los presidentes de los comités deberán reunirse y garantizar que tengamos el apoyo del comité para garantizar que estas tareas se puedan ejecutar de la mejor manera posible.
                <br><br>
                Tenga en cuenta los temas que el comité ya votó y el trabajo de los subcomités para cumplir con nuestro tiempo asignado y permitir que todos los presidentes de los comités presenten sus informes que puedan indicar dónde debemos dirigir nuestro enfoque y atención.
                <br><br>
                Todos los presidentes de los comités, en el espíritu de rotación, busquen a su predecesor y acompáñennos a nuestras reuniones para que tenga algo de experiencia en MBAR. Los puestos de presidente de MBAR deben rotarse y ser ocupados por miembros para aumentar su capacidad de practicar y defender las tradiciones y aumentar su experiencia espiritual al trabajar y jugar con miembros nuevos y antiguos.
                <br><br>
                Necesitamos cubrir los siguientes puestos: Hospitalidad;
            </dt>

            <dt>7. Informe del tesorero - Carolyn H.: Ver la hoja de cálculo del presupuesto adjunta; Saldo bancario $28,914; Discusión sobre el contrato de AV (ver la cita adjunta) - Incluye escucha asistida: 25 auriculares; ASL: Rene se ofreció como voluntario para investigar a los proveedores de ASL; Subtítulos: RDM declaró que se requiere ASL si se solicita por telecomunicaciones con el Departamento de Justicia; los españoles harán su propia traducción - no se necesita nada de AV; Moción aprobada Presupuesto de canasta de regalo $231 - para los oradores de AA, Al-Anon y los hispanos tienen su propio presupuesto; Moción aprobada - aumento del presupuesto de eventos: agregar canastas de contribución en los lugares de los eventos; Moción diferida - Costo/contrato de ACV; Moción aprobada - Revisar el presupuesto de literatura a un presupuesto de $0: Carolyn hace un seguimiento con May - obtener literatura de la Oficina Central en préstamo como se hizo en años anteriores;
            </dt>

            <dt>8. Los siguientes elementos necesitan consideración y aprobación por parte del comité, ya que tienen costos en caso de que excedan los valores de las partidas presupuestarias:
                <br><br>Moción aplazada: se ordenaron 26 camisetas de la conferencia hasta el momento en las inscripciones; Kevin investigó los precios para una cantidad reducida;
                <br><br>Moción aprobada: se ordenaron 27 camisetas del comité;
                <br><br>Moción aprobada: $400 de espacio para asegurar fondos en MBAR: Opción 1: sala Steinbeck 3 y Opción 2: Carolyn ya pagó y aseguró la sala para los invitados;
                <br><br>Moción aplazada: traductor de ASL: para CADA traductor en cada reunión se requieren 2 traductores para los descansos y almuerzos; el año pasado se utilizaron traductores en la Gran Reunión del sábado y en las reuniones de panel; ¿Tenemos alguna solicitud de ASL en este momento?
                <br><br>Moción aplazada: costo de AV como nota: el año pasado, un miembro con experiencia en AV estuvo dispuesto a encender y apagar los micrófonos que no tenían que tener instalados por el personal de Encore en cada reunión; Esto fue aprobado mediante una conversación previa con Encore;
                <br><br>Aumento de los fondos a los que tendrán acceso los presidentes de los comités en función de los comentarios y la información de los presidentes de los comités;
                <br><br>Moción aprobada: aprobación del banner (ver imagen adjunta): banner de color aprobado;
            </dt>

            <dt>9. Séptima Tradición: Puede hacer una contribución a la Séptima Tradición: PayPal a mbartreasurer@gmail.com o enviando un cheque a: MBAR, PO Box 1462, Monterey, CA 93942; o Venmo: @MBARoundup24 (<em>Nota:</em> Venmo y el cheque van 100 % a la Tesorería, PayPal cobra una tarifa).</dt>

            <dt>10. Informes de los presidentes de los comités/comités directivos</dt>

            <dd>a. Medios: Gina, Sean: se agregó un volante a Facebook;</dd>

            <dd>b. Inscripción: Naomi: se recibieron 101 inscripciones completas en total; se recibieron 101 inscripciones completas en total; 20 incompletas no pagadas; 74 de A.A. / 14 de Al-Anon / 12 dobles / 1 otro; no hay inscripciones en español; 57 "paquetes"; 23 camisetas; 2 de Helping Hand; Naomi actualiza Venmo sobre el formulario de inscripción; Programa: en proceso; se necesitan aportes de los comités para los insertos; se necesitan los nombres de los secretarios y lectores de las reuniones; Jane proporciona información para Al-Ateen; todas las inscripciones de oradores son gratuitas;</dd>

            <dd>c. Español: Robert: se reúne regularmente: los domingos y el último miércoles del mes; tiene 10 inscripciones; crea un banner en español; se vota para seleccionar oradores el 17 de julio de 2024; Trabajando en el programa - Naomi se incluirá en el programa principal de la conferencia;</dd>

            <dd>d. Al-Anon - Jane: Oradores seleccionados en coordinación con Kathleen;</dd>

            <dd>e. Camiseta - Kevin: Realización de pedidos de camisetas del Comité - $16.00 más 10% de impuestos; Realización de pedidos - 18 tazas: cuestan $19.82; se venden por $20; 36 botellas de agua - cuestan $11+ - se venden por $12; Obtenga precios revisados ​​para 120 camisetas del comité

            <dd>f. Oradora - Kathleen: Se reservaron habitaciones para los oradores en Marriott; Kathleen proporcionó la lista actual de oradores - hubo cierta confusión con respecto a la lista de oradores; el Comité seleccionó a Mark S. como el orador de inicio del viernes</dd>

            <dd>g. Difusión - Conor: 6 inscripciones de la reunión de AA / Al-Anon del viernes; Visitó 4 oficinas centrales; Llamó a 10 oficinas centrales; Ir a San Jose Saturday Night Live; Jean se ofreció a ayudar con las llamadas de divulgación; Naomi ayudó con el envío masivo de correos a las oficinas centrales; Chris sugirió ir a las populares reuniones de Salinas; señaló problemas con el registro en línea: es difícil conciliar los costos;</dd>

            <dd>h. Eventos: Samantha: seguro asegurado; eventos potenciales para MBAR: se incluyó un cronograma prototipo;</dd>

            <dd>i. I.G.R. / G.S.R.: Cole: sin informe;</dd>

            <dd>j. Reuniones de maratón: Mark: 11 reuniones de sábado y 3 de domingo; es posible que sea necesario agregar más reuniones según el programa actualizado; Naomi proporciona una copia del programa;</dd>

            <dd>k. Instalaciones: Sally: sin informe;</dd>

            <dd>l. Sitio web: Phillip: sin informe;</dd>

            <dd>m. Rifa: Katherine: sin informe;</dd>

            <dd>n. Helado: Rick: sin informe;</dd>

            <dd>o. Desayuno - Joanie: Confirmado comidas gratuitas para los oradores; Se necesita el recuento final 2 semanas antes de la conferencia; Aquellos que no se inscribieron pueden pagar en el lugar;</dd>

            <dt>11. Asuntos pendientes:</dt>

            <dd>a. Recordatorio Los miembros del comité deben estar todos registrados, dentro del próximo mes;</dd>

            <dd>b. Reuniones del comité: ¿Las tenemos semanalmente o quincenalmente antes de la conferencia?</dd>

            <dd>c. Estado sin fines de lucro: Renee - Cindy y yo tuvimos una conferencia telefónica con un abogado; tenemos mucha información para que la discuta el comité, y esto se presentará en la reunión de cierre del comité el 14/09/24 a las 10 a.m.;</dd>

            <dt>12. Ideas para recaudar fondos</dt>

            <dd>a. Presencia en la reunión de cumpleaños: 27 de julio y 31 de agosto - se necesitan voluntarios;</dd>

            <dd>b. Viaje en autobús del grupo Pacific;</dd>

            <dt>13. Asuntos nuevos: ninguno;</dt>

            <dd>a. Barbacoa del comité: si desea asistir, necesitaremos su presencia en la reunión del comité de julio; se necesita espacio para el evento y el comité deberá aprobar previamente el pago; Mark y Matt coordinan el lugar; </dd>

            <dt>14. La próxima reunión del comité directivo es el martes 23/07/2024 a las 6:00pm a través de Zoom;</dt>

            <dt>15. La próxima reunión del comité es el sábado 03/08/2024 a las 10:00am; las reuniones posteriores serán todas las semanas hasta la fecha de la conferencia;</dt>

            <dt>16. La reunión se levantó al mediodía con la Oración de la Serenidad.</dt>
        </dl>

        <p> Asistentes: Carolyn, Chris, Cole, Conor, Dawn, Esther, Jane, Janet, Jean, Jennifer, Joanie, Katherine, Kathleen, Katie, Kevin, Mark, Naomi, Phillip, Renee, Robert, Roger, Samantha y Sean</p>

    </div>
</div>