<div class="accordion-item">
    <h4 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
            <i class="bi bi-book me-2" style="font-size: 1.5rem; color: var(--color-8);" aria-hidden="true"></i><strong>2021</strong>
        </button>
    </h4>
    <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body d-grid gap-3">

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/12-11-21.pdf">Abre un PDF: 12/11/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/11-13-21.pdf">Abre un PDF: 11/13/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/10-9-21.pdf">Abre un PDF: 10/09/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/9-11-21.pdf">Abre un PDF: 09/11/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/8-14-21.pdf">Abre un PDF: 08/14/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/7-10-21.pdf">Abre un PDF: 07/10/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/6-12-21.pdf">Abre un PDF: 06/12/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/5-8-21.pdf">Abre un PDF: 05/08/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/4-10-21.pdf">Abre un PDF: 04/10/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/3-13-21.pdf">Abre un PDF: 03/13/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/2-13-21.pdf">Abre un PDF: 02/13/2021</a>

            <a class="btn btn-outline-primary btn-sm" href="../pdf/2021/1-9-21.pdf">Abre un PDF: 01/09/2021</a>
        </div>
    </div>
</div>