<div id="april2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            Notas del Comité MBAR 2024
            <br>ID de Zoom 831 4306 2293 Contraseña 2024
            <br>Sábado 13 de Abril de 2024 a las 10h
            <br><a href='/' class="bb-link">montereybayarearoundup.org/es/</a>
        </p>

        <dl>
            <dt>1. Llamada al orden del presidente: 10 a.m.;</dt>

            <dt>2. Lectura de las 12 Tradiciones: Samantha;</dt>

            <dt>3. Nuevos asistentes, pongan sus números de teléfono y direcciones de correo electrónico en el chat: Hilda, Kathleen(SF);</dt>

            <dt>4. ¿Hay algún miembro de A.A. ¿O los aniversarios de Al-Anon desde nuestra última reunión? Ninguno;</dt>

            <dt>5. Aprobar/Modificar Acta de la última reunión: Aprobada;</dt>

            <dt>6. Informe del presidente - Chris T.: Gracias a todos por asistir a nuestra reunión de comité programada regularmente. Soy muy consciente de que tenemos responsabilidades; yo también tengo muchas, estas reuniones se han planificado con anticipación para respaldar la planificación y programación de su asistencia requerida, especialmente si ocupa un puesto de presidente de comité.
                <br><br>
                Los próximos meses son reuniones que tendrán como objetivo contar con su atención y apoyo en la planificación, comunicación, orquestación y organización de la conferencia MBAR 2024. Para garantizar que tengamos una reunión productiva, respete las decisiones que ya hemos tomado y votado para mantener el enfoque en los elementos que aún necesitan planificación.
                <br><br>
                Gracias a todos por su apoyo en el evento del Día de San Patricio, el evento tuvo una buena asistencia y la comunidad fue cálida y acogedora, tuvimos un cumpleaños de 1 año que se pudo celebrar, un visitante de Canadá y algunas de las personas más importantes que asistieron, los recién llegados. <br><br>
                Comité, asegúrense de que todos estén haciendo anuncios de preinscripción de MBAR de manera activa, ya que las inscripciones se pueden realizar en línea o imprimiendo un formulario de inscripción directamente desde el sitio web montereybayarearoundup.org.
                <br><br>
                Todos los presidentes de comités en Spirit of Rotation, busquen a su predecesor y acompáñennos a nuestras reuniones para que tenga algo de experiencia en MBAR.
                <br><br>
                Necesitamos cubrir los siguientes cargos: Eventos: Samantha nominada y aprobada;
            </dt>

            <dt>7. Informe del Tesorero - Jean T: Ver hoja de cálculo del presupuesto adjunta; Saldo actual $26,320 incluye inscripciones, bingo, días de San Patricio, etc. - Incluye 39 inscripciones; Formulario 199N presentado: estatal y federal; El papeleo de la organización sin fines de lucro no está completo: la CPA tiene un presupuesto para completar esto; Presentar un informe federal sin fines de lucro: tarifa de $275;</dt>

            <dt>8. Séptima Tradición: Puede hacer una contribución a la Séptima Tradición - PayPal en mbartreasurer@gmail.com o enviando un cheque a - MBAR, PO Box 1462, Monterey, CA 93942; O Venmo: @MBARoundup24 (<em>Nota:</em> Venmo y el cheque van 100% al Tesoro, PayPal cobra una tarifa).</dt>

            <dt>9. Presidentes de comités/informes del comité directivo</dt>

            <dd>a. Medios - Gina, Sean: Facebook actualizado - grupos de jóvenes;</dd>

            <dd>b. Inscripciones - Naomi: 39 inscripciones totales recibidas - 27 en línea, 12 en papel, 24 AA, 9 Al-Anon y 6 dobles ganadores, 4 inscripciones gratuitas - concurso de logotipos y premios de rifa, 4 gratis para oradores de Al-Anon, honorarios recaudados de $2,670; Continuar trabajando en el proceso de registro en línea; Al-Anon se ofreció a ayudar; Actualización del formulario de inscripción para incluir camisetas. Naomi notificará a los inscritos; Chris animó a todos los miembros del comité a registrarse;</dd>

            <dd>c. Español - Robert: Revisar la traducción al español del formulario de inscripción, etc.; Reunión del grupo de español Último domingo de cada mes más otras fechas; Necesita formularios de registro impresos: Renee le enviará el pdf a Robert;</dd>

            <dd>d. Al-Anon - Jane: Los tres oradores se alinearon; Iniciar reuniones la próxima semana; Comités reunidos;</dd>

            <dd>e. Camiseta - Kevin: Costo de la camiseta - Pequeña a XL - $26, Xxl - $31; Cortar los pedidos anticipados 30 días antes del evento; Envíe un correo electrónico a Christina para realizar un pedido de camisetas del comité; Actualización del formulario de inscripción para incluir camisetas. Naomi notificará a los inscritos; Phillip actualiza el formulario de registro en línea; Necesita orientación sobre tazas de viaje, botellas de agua, gorras, etc.;</dd>

            <dd>f. Oradora - Kathleen: Enumeró varios candidatos posibles; ella verá quién está disponible; Carolyn: hay un presupuesto de $3k para viajes y alojamiento de hablantes de español fuera de la ciudad, hay un presupuesto separado para viajes y alojamiento de hablantes de español fuera de la ciudad; Es necesario precisar un horario, tentativamente: inicio del viernes: miembro del Comité MBAR local, viernes por la tarde: AA / Al-Anon, posiblemente sábado por la tarde: panel de veteranos, sábado por la tarde: Al-Anon, sábado por la noche, domingo por la mañana: Al-Anon , domingo por la mañana: AA;</dd>

            <dd>g. Alcance - Conor: No presente; Vuelva a enviar el formulario de registro revisado a las oficinas centrales en Monterey, San Francisco, Los Ángeles;</dd>

            <dd>h. I.G.R. / G.S.R. - Cole: Sin informe;</dd>

            <dd>i. Reuniones maratónicas - Mark: Coordinando con Al-Anon;</dd>

            <dd>j. Instalaciones- Sally: Sin informe;</dd>

            <dd>k. Sitio web - Phillip: El cumplimiento de la accesibilidad del nuevo sitio web (ADA) está casi completo; El proceso de registro funciona sin problemas: dinero para el tesorero, formulario de registro para el presidente de registro; Proceso de pago actualizado, Robert revisa la página en español; Dominio de dirección, alojamiento web, etc. renovado; Trabajando en la página de Al-Anon; Agregar camisetas y tazas de café; Necesita una lista de comités actualizada y un calendario de conferencias para publicar;</dd>

            <dd>l. Rifa - Katherine: $978 del día de San Patricio más 50/50; May y otros se ofrecieron como voluntarios para ayudar con la rifa; Concéntrese en alinear los premios de la rifa de la conferencia;</dd>

            <dt>10. Asuntos antiguos:</dt>

            <dd>a. Todos los miembros del Comité de Recordatorio deben estar registrados dentro del próximo mes;</dd>

            <dd>b. Estado sin fines de lucro: miembros del comité, por favor anuncien que necesitamos ayuda con esto;</dd>

            <dt>Ideas para recaudar fondos</dt>

            <dd>a. Los miembros de la Comunidad han preguntado sobre dos eventos de Bingo y Softbol: Tengo un miembro que estaría dispuesto a ser el coordinador de softbol el sábado después del 4 de julio, como el año pasado. Los siguientes presidentes de comités deberían estar disponibles: Propuesto y aprobado para el 6 de julio de 2024;</dd>

            <dd>b. Presencia en el Día de la Unidad: se necesitan voluntarios</dd>

            <dd>c. Presencia en la reunión de cumpleaños: Carolyn y Katherine;</dd>

            <dd>d. Reunión de AA y Al-Anon: 17 de mayo: cena a las 5 p. m., orador a las 6 p. m.;</dd>

            <dt>11. Nuevo negocio:</dt>

            <dd>a. Seguro de eventos: MBAR no está cubierto por MBAIAA; este seguro está dedicado a las reuniones periódicas que se llevan a cabo con la confraternidad y los espacios que ocupan. La compañía que utilizan es Philadelphia Insurance Company, agente Trocelyn Allen en Hub International Insurance, 951-779-8643. Si los miembros conocen otros proveedores, envíen información a Christina;</dd>

            <dt>12. La próxima reunión del Comité Directivo será el martes 30/04/2024 a las 6 p. m. a través de Zoom;</dt>

            <dt>13. La próxima reunión del Comité es el sábado 11/05/2024 a las 10 a.m.;</dt>

            <dt>14. La reunión finalizó a las 11:15 am con la Oración de la Serenidad;</dt>
        </dl>

        <p> Asistentes: Brady, Carolyn, Chris, Cindy, Cole, Diane, Hilda, Jane, Janet, Jean, Joanie, Katherine Ann, Kathleen, Mary Grace, Naomi, Phillip, Renee, Robert, Samantha, Sean, y Roger< /p>

    </div>
</div>