<div id="june2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            Notas del Comité MBAR 2024
            <br>ID de Zoom 831 4306 2293 Contraseña 2024
            <br>Sábado 11 de Junio de 2024 a las 10h
            <br><a href='/' class="bb-link">montereybayarearoundup.org/es/</a>
        </p>

        <dl>
            <dt>1. Llamado al orden del presidente: 10am;</dt>

            <dt>2. Lectura de las 12 Tradiciones: Jean;</dt>

            <dt>3. Nuevos asistentes, coloquen sus números de teléfono y direcciones de correo electrónico en el chat: Ninguno;</dt>

            <dt>4. ¿Hay algún aniversario de A.A. o Al-Anon desde nuestra última reunión? Katherine 14 años, Carolyn 25 años, Mary Grace 45 años, Cole 37 años y Robert 16 años;</dt>

            <dt>5. Aprobación/enmienda de las actas de la última reunión: Aprobadas con revisiones;</dt>

            <dt>6. Informe del presidente: Chris T.: ¡Gracias a todos por su continuo apoyo y asistencia a nuestra reunión de planificación! Estoy esperando con ansias los informes del comité y el resumen de lo que el subcomité pudo conseguir para las camisetas, así como algunos temas que requieren atención y apoyo de todo el comité en los próximos meses, ya que MBAR 2024 se acerca rápidamente.
                <br><br>
                Como se discutió y votó en la última reunión, esta reunión durará 1,5 horas y, como nos embarcamos en varias tareas en cuestión, los presidentes de los comités deberán reunirse y asegurarse de que tengamos el apoyo del comité para garantizar que estas tareas se puedan ejecutar de la mejor manera posible.
                <br><br>
                Tenga en cuenta los temas que el comité ya votó y el trabajo de los subcomités para cumplir con nuestro tiempo asignado y permitir que todos los presidentes de los comités presenten sus informes que pueden describir dónde debemos dirigir nuestro enfoque y atención.
                <br><br>
                Todos los presidentes de comités en el espíritu de rotación, busquen a su predecesor y acompáñennos a nuestras reuniones para que tengan algo de experiencia en MBAR. Los puestos de presidente de MBAR deben ser rotados y ocupados por miembros para aumentar su capacidad de practicar y defender las Tradiciones y aumentar su Experiencia Espiritual al trabajar y jugar con miembros nuevos y antiguos.
                <br><br>
                Necesitamos cubrir los siguientes puestos: Presidente de Instalaciones; Servicio de Transporte - Per Cindy A; MBAR 2022 Trevor F.; Presidente del Servicio de Transporte MBAR 2019 (y ayudó en 2022) Chuck N.; Consulte la Lista de Presidentes de Comités adjunta
            </dt>

            <dt>7. Informe del Tesorero - Carolyn H.: Consulte la hoja de cálculo del presupuesto adjunta; 65 inscripciones recibidas; Seguro pagado; 15 camisetas de la Conferencia; 20 camisetas del Comité; Saldo bancario $27,726; Registrado - Faltan pagos que dicen que pagarían con PayPal: Molly M., Kerry M., Chris L., Tom L., Sherri M., Brenda S. y Earl W.
            </dt>

            <dt>8. Séptima Tradición: Puede hacer una contribución a la Séptima Tradición: PayPal a mbartreasurer@gmail.com o enviando un cheque a: MBAR, PO Box 1462, Monterey, CA 93942; o Venmo: @MBARoundup24 (<em>Nota:</em> Venmo y el cheque van 100 % a la Tesorería, PayPal cobra una tarifa).</dt>

            <dt>8. Séptima Tradición: Puede hacer una contribución a la Séptima Tradición a través de PayPal en mbartreasurer@gmail.com o enviando un cheque a MBAR, PO Box 1462, Monterey, CA 93942; o Venmo: @MBARoundup24 (<em>Nota:</em> Venmo y el cheque van 100 % al Tesoro, PayPal cobra una tarifa).</dt>

            <dt>9. Presidentes de comités/Informes del comité directivo</dt>

            <dd>a. Medios de comunicación: Gina, Sean: Disculpa por no enviar un recordatorio por mensaje de texto para la reunión; lo hará el mes próximo;</dd>

            <dd>b. Inscripción: Naomi: 71 inscripciones totales recibidas: 41 en línea, 21 en papel, 9 no pagas, 40 AA / 12 Al-Anon / 12 otros, ninguna inscripción en español, 62 'Paquetes'; Logística para las camisetas: Naomi emite un boleto, Kevin reparte las camisetas; Cindy proporciona un informe el mes que viene; recuento de las preinscripciones recibidas en años anteriores; Arthur señala algunos problemas con el formulario de inscripción en línea; Jean se comunica con Phillip; Chris, Renee y Jean trabajan en el programa; envían su trabajo a Naomi;</dd>

            <dd>c. Español: Robert: se reúnen regularmente, los domingos y el último miércoles del mes; mañana se vota a los oradores;</dd>

            <dd>d. Al-Anon: Jane: se seleccionan los oradores en coordinación con Kathleen; se completan las reuniones maratónicas; Jane envía por correo electrónico la lista del comité y la agenda para el programa;</dd>

            <dd>e. Camiseta: Kevin: factura compartida por 240 camisetas; la base para fijar el precio de las camisetas a $15; discusión extensa sobre la logística de la compra de camisetas; se debe realizar el pedido por adelantado antes del 30 de julio de 2024; <br><br>
                Mociones propuestas y aprobadas: fijar el precio final de las camisetas de todos los asistentes en 15 USD; no comprar ninguna camiseta de los asistentes hasta que el comité en pleno apruebe la compra; utilizar los ingresos de la recaudación de fondos para los costos relacionados con los elementos presupuestados cuando sea necesario; crear un punto en la agenda para analizar el excedente de la recaudación de fondos y cómo utilizarlo; los presidentes de los comités presentan el presupuesto revisado antes del 1 de julio de 2024 solicitando cualquier cambio en la financiación antes del 1 de julio de 2024;
                <br><br>
                Camisetas del comité; 16,00 USD + 10 % de impuestos; se está planificando; 18 tazas: cuestan 19,82 USD, se venden por 20 USD; 36 botellas de agua: cuestan 11 USD o más, se venden por 12 USD; Samantha quiere algunos productos para los premios del evento;
            </dd>

            <dd>f. Oradora: Kathleen: Jean presentó el programa preliminar creado por el comité directivo; Naomi señaló que la selección de los oradores debería estar a cargo del comité de oradores, no del comité directivo; Naomi y Samantha se ofrecieron a ayudar a Kathleen; Naomi señaló que el orador de inicio generalmente es seleccionado por todo el comité y ha sido un miembro activo del comité MBAR; Chris agregará información a la agenda de julio;</dd>

            <dd>g. Difusión - Conor: Sin informe;</dd>

            <dd>h. Eventos - Samantha: Seguro asegurado; Eventos potenciales para MBAR;</dd>

            <dd>i. I.G.R. / G.S.R. - Cole: Sin informe;</dd>

            <dd>j. Reuniones de maratón - Mark: Sin informe;</dd>

            <dd>k. Instalaciones - Sally: Sin informe;</dd>

            <dd>l. Sitio web - Phillip: Sin informe;</dd>

            <dd>m. Rifa - Katherine: ¿Hay personas en fila para ayudar? - Cole: Miembros del comité separados para la rifa 50-50; Moción propuesta de precio de las entradas (rifa y 50/50), aprobada: 1 entrada $1, 6 entradas $5, 12 entradas $10, 25 entradas $20;</dd>

            <dt>10. Asuntos pendientes:</dt>

            <dd>a. Recordatorio: todos los miembros del comité deben estar registrados dentro del próximo mes;</dd>

            <dd>b. Estado sin fines de lucro: los miembros del comité deben anunciar que necesitamos ayuda con esto. Chris se comunicó con Jana para que esto también sea un anuncio de IGR; Moción aprobada: pagar a un profesional para que complete la solicitud sin fines de lucro; Rene y Cindy se ofrecieron como voluntarios para ser el enlace;</dd>

            <dt>11. Ideas para recaudar fondos</dt>

            <dd>a. Presencia en el Día de la Unidad: 6/9/2024: hay una mesa y una carpa; se necesitan voluntarios;</dd>

            <dd>b. Presencia en la reunión de cumpleaños: 25 de mayo, 29 de junio, 27 de julio y 31 de agosto: se necesitan voluntarios;</dd>

            <dd>c. Evento de softbol: 6/7/24: Dampierre Little League Park, Carmel Valley, TC. Coordinación: se necesitan voluntarios;</dd>

            <dt>12. Nuevos asuntos: ninguno;</dt>

            <dt>13. La próxima reunión del Comité Directivo es el martes 25/06/2024 a las 6:00pm a través de Zoom;</dt>

            <dt>14. La próxima reunión del Comité es el sábado 13/07/2024 a las 10:00am;</dt>

            <dt>15. La reunión se levantó a las 11:35am con la Oración de la Serenidad.</dt>
        </dl>

        <p> Asistentes: Arthur, Carolyn, Chris, Cindy, Cole, Gina, Jane, Janet, Jean, Kathleen S., Kathleen F., Katie, Kevin, Mary Grace, May, Naomi, Phil, Renee, Robert, Roger y Samantha</p>
    </div>
</div>