<div id="january2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            Notas del Comité MBAR 2024
            <br>ID de Zoom 831 4306 2293 Contraseña 2024
            <br>Sábado 13 de Enero de 2024 a las 10h
            <br><a href='/' class="bb-link">montereybayarearoundup.org</a>
        </p>

        <dl>
            <dt>1. Llamada al orden del presidente: 10 a.m.;</dt>

            <dt>2. Lectura de las 12 Tradiciones: Jean;</dt>

            <dt>3. Nuevos asistentes, ingresen sus números de teléfono y direcciones de correo electrónico en el chat: Andy, Jill, Dawn: Al-Anon y Jane: Al-Anon;</dt>

            <dt>4. ¿Hay algún miembro de A.A. ¿O los aniversarios de Al-Anon desde nuestra última reunión? Ninguno;</dt>

            <dt>5. Aprobar/Modificar Acta de la última reunión: Aprobada;</dt>

            <dt>6. Informe del Presidente - Chris T.: Feliz Año Nuevo. Estoy muy emocionado de ver lo que podemos lograr como comité de planificación con el arduo trabajo, la dedicación, la comunicación, las ideas y la ejecución con la ayuda del Poder Superior de este grupo como Continuamos planificando y asegurando los medios para tener una Conferencia MBAR 2024 completa. Ya estamos en 2024, el año de MBAR. Tenemos informes de los presidentes de nuestros comités para hablar y realizar nuestro evento de recaudación de fondos en unas pocas semanas. Asegúrese de permitir comentarios rápidos y concisos para poder cerrar la reunión, idealmente, en una hora. marco de tiempo que permita un buen equilibrio entre el servicio y las obligaciones de la vida. Se agradece su asistencia y participación y estoy más que agradecido por los esfuerzos de todos. Necesitamos cubrir las siguientes sillas: Divulgación y Eventos.</dt>

            <dt>7. Informe del Tesorero - Carolyn, Jean T: Depósito del Centro de Conferencias - $5 mil pagados; Buzón renovado; Licencia comercial renovada; Saldo actual $18,400; Depósito pagado en la Iglesia Luterana de Belén; Un registro recibido;</dt>

            <dt>8. Séptima Tradición: Puede hacer una contribución a la Séptima Tradición - PayPal en mbartreasurer@gmail.com o enviando un cheque a - MBAR, PO Box 1462, Monterey, CA 93942; O Venmo: @MBARoundup24 (<em>Nota:</em> Venmo y el cheque van 100% al Tesoro, PayPal cobra una tarifa).</dt>

            <dt>9. Presidentes de comités / Informes del comité directivo</dt>

            <dd>a. Medios - Gina: Se distribuyó folleto de bingo en Facebook y se distribuyeron copias impresas; Folleto desarrollado para las reuniones del comité de 2024; Otras publicaciones varias en Facebook;</dd>

            <dd>b. Registro - Naomi: Nada en el apartado postal; Proceso de registro en línea probado;</dd>

            <dd>c. Español - Robert: Sin informe;</dd>

            <dd>d. Al-Anon - Jane: Sin informe;</dd>

            <dd>e. Camiseta - Kevin: Amplia discusión sobre camisetas, tazas de viaje y gorras; Discusión en la mesa hasta la próxima reunión: Chris y Phillip desarrollan una encuesta en línea;</dd>

            <dd>f. IGR/GSR - Cole: Anunciar MBAR en las reuniones del comité; Sin informe;</dd>

            <dd>g. Instalaciones - Sally: Recibió 24 respuestas a la encuesta; Necesitamos tener en cuenta los requisitos del impuesto sobre las ventas si vendemos mercancías en el centro de conferencias;</dd>

            <dd>h. Sitio web - Phillip: El nuevo sitio web está en funcionamiento; Hacer arreglos para obtener la propiedad de los nombres de dominio de MBAR; Nuevas páginas para Al-Anon y el compañerismo en español; Eliminación gradual del registro de Google Doc al registro en línea en el sitio web; El registro del sitio web permite la exportación de datos para el registro, etc.</dd>

            <dd>i. Rifa - Katherine: Aún faltan premios para Bingo; Sin informe;</dd>

            <dt>10. Asuntos antiguos:</dt>
            <dt>Ideas para recaudar fondos</dt>

            <dd>a. "B-I-N-G-O" de enero: Moose Lodge, viernes 26/01/24, de 6 a 9 p. m.; Rifa 50/50 y premios de rifa donados; Ponente: Elena B; Maestro del juego de bingo; Voluntarios: Comida (3), Entrada (3), Rifa (2) y 7ma tradición (2 a 3); Montaje y limpieza; Comience la configuración a las 4:30 p. m.; Voluntarios: Conor - Preparación/limpieza de alimentos; Carolyn - Configuración/Premios; Kathleen - Preparar/Limpieza/Comida; Sean - Comida/Café; Cindy - Entrada; Arturo - Entrada; Cole - Séptima Tradición/Limpieza; Samantha - Limpieza/Premios; Karen - Rifa; René - 7ma Tradición/Rifa; Janet - Comida/Séptima Tradición; Robert - Entrada/Limpieza; Katherine - Rifa/Premios; Jean y Gina son voluntarios; Susan voluntaria para la mesa de registro; Cindy coordina con Chris la transferencia de dispositivos de pago "Square";</dd>

            <dd>b. Día de San Patricio, domingo 17/03 - no discutido; Sitio: Moose Lodge o Phil's Pool House - Phil verifique si la casa está disponible; Hora: 16:00 a 19:00 horas; Vocero; Comida: Chris se acerca a posibles cocineros; Sorteo;</dd>

            <dt>11. Nuevo negocio: Ninguno;</dt>

            <dt>12. La próxima reunión del Comité Directivo es el martes 26/12/23 a las 6 p. m. a través de Zoom;</dt>

            <dt>13. La próxima reunión del Comité es el sábado 13/01/2024 a las 10 a.m.;</dt>

            <dt>14. La reunión finalizó a las 11:10 am con la Oración de la Serenidad;</dt>
        </dl>

        <p> Asistentes: Amber, Andy, Anne, Chris, Cindy, Cole, Dawn, Gina, Jane, Janet, Jean, Jill, Katherine, Kathleen, Kevin, Kim, Mary Grace, Naomi, Penny, Phillip, Renee, Roger, Sally y Susan;</p>

    </div>
</div>