<div id="february2024" class="accordion-collapse collapse " data-bs-parent="#accordion2024">
    <div class="accordion-body">
        <p class="text-center">
            Notas del Comité MBAR 2024
            <br>ID de Zoom 831 4306 2293 Contraseña 2024
            <br>Sábado 10 de Febrero de 2024 a las 10h
            <br><a href='/' class="bb-link">montereybayarearoundup.org/es/</a>
        </p>

        <dl>
            <dt>1. Llamada al orden del presidente: 10 a.m.;</dt>

            <dt>2. Lectura de las 12 Tradiciones: Jean;</dt>

            <dt>3. Nuevos asistentes, pongan sus números de teléfono y direcciones de correo electrónico en el chat: Joanie: Al-Anon;</dt>

            <dt>4. ¿Hay algún miembro de A.A. ¿O los aniversarios de Al-Anon desde nuestra última reunión? Ninguno;</dt>

            <dt>5. Aprobar/Modificar Acta de la última reunión: Aprobada;</dt>

            <dt>6. Informe del presidente - Chris T.: Muchas gracias a todos por su asistencia, servicio y apoyo al evento de Bingo de enero, fue un <span class="text-uppercase">gran</span> éxito e impresionó a muchos de nuestra Comunidad que asistieron a su primer evento de sobriedad. Fue muy <span class="text-uppercase">divertido</span> y no podría estar más agradecido a todos aquellos con quienes trabajo y estoy al servicio de ellos.
                <br><br>
                Tenemos que decidir qué camisetas usar en esta reunión. Phillip ha creado una encuesta de Zoom que usaremos para ayudarnos en esta importante decisión.
                <br><br>También tenemos en cuenta que haya café disponible en la conferencia y hemos proporcionado un cálculo aproximado del costo en caso de que decidamos ofrecerlo como comité.
                <br><br>
                Nuestra conferencia se realizará en poco menos de siete meses, por lo que se agradece mucho el enfoque y la atención a estos temas en esta reunión.
                <br><br>
                Necesitamos cubrir los siguientes puestos: Eventos, Difusión: Conor y Rick, y Reuniones de maratón: posiblemente Mark.
            </dt>

            <dt>7. Informe del Tesorero - Carolyn, Jean T: Saldo actual $22,154.25 incluye registros, bingo, etc.; Carolyn/Phillip habló sobre la renovación del dominio; </dt>

            <dt>8. Séptima Tradición: Puede hacer una contribución a la Séptima Tradición - PayPal en mbartreasurer@gmail.com o enviando un cheque a - MBAR, PO Box 1462, Monterey, CA 93942; O Venmo: @MBARoundup24 (<em>Nota:</em> Venmo y el cheque van 100% al Tesoro, PayPal cobra una tarifa).</dt>

            <dt>9. Presidentes de comités/informes del comité directivo</dt>

            <dd>a. Medios - Gina: Se distribuyeron folletos de San Patricio y Bingo en Facebook y se distribuyeron copias impresas;</dd>

            <dd>b. Registro - Naomi: Diez registros recibidos; Trabajando en el proceso de registro en línea;</dd>

            <dd>c. Español - Robert: Nos reunimos el último miércoles del mes (comida compartida); Necesita traducción al español del formulario de inscripción - René para realizar la traducción; 28 Grupos Españoles; Trabajando con oradores de Texas y México;</dd>

            <dd>d. Al-Anon - Dawn: Iniciar reuniones el próximo mes; Comités reunidos;</dd>

            <dd>e. Camiseta - Kevin: consulte la encuesta a continuación; Las camisetas recomendadas por el comité serán de un color diferente; Considere tazas de viaje, botellas de agua, gorras, etc.;</dd>

            <dd>f. I.G.R. / G.S.R. - Cole: Anuncio de MBAR en las reuniones del comité;</dd>

            <dd>g. Instalaciones - Sally: Sin informe;</dd>

            <dd>h. Sitio web - Phillip: El nuevo sitio web es accesible (ADA); Trabajando en el registro: dinero para el tesorero y formulario de registro para el presidente de registro; Resolver el proceso para marcar las inscripciones como pagadas: coordinar con Carolyn y Naomi; Renovación del dominio de dirección; Robert revisa la página en español en el sitio web; René coordina la traducción al español; Necesita copias digitales de la traducción al español;</dd>

            <dd>i. Rifa - Katherine: Chris necesita voluntarios para ayudar con la rifa del Día de San Patricio; Agregar comité para el día de San Patricio - Recaudar dinero para las comidas: Joanie y Chris;</dd>

            <dt>10. Asuntos antiguos:</dt>
            <dt>Ideas para recaudar fondos</dt>

            <dd>a. Resumen de "B-I-N-G-O" de enero: Moose Lodge, viernes 26/01/24, de 6 a 9 p. m.; Rifa 50/50 y premios de rifa donados; Ponente: Elena B; Maestro del juego de bingo; Photo Boot fue un éxito; Voluntarios: Voluntarios: Alimentación (3) Entrada (3) Rifa (2) 7ma tradición (2 a 3); Alimentos - aportados - recibos guardados; Ingreso total $3,199.25 - Carolyn proporciona detalles en marzo; Tomar disposiciones para aceptar contribuciones 50/50 de Venmo;</dd>

            <dd>b. Día de San Patricio, domingo 17/03 - no discutido; Sitio: Moose Lodge o Phil's Pool House; Phil ve si hay casa disponible; Hora de 16 a 19 horas; Vocero; Comida: Chris se acerca a posibles cocineros; Sorteo;</dd>

            <dt>Encuesta de camisetas sobre el estilo y color de las camisetas MBAR</dt>

            <dd>a. Estilo: manga corta, manga larga, estilo béisbol; Opciones de color: verde azulado, azul real, azul marino, blanco y negro; Resultados finales: Ganador de camisetas General MBAR: manga corta, $15 y azul marino; Camisetas del Comité: Jersey, blanca y azul; Kevin traerá muestras en marzo; Nueva encuesta el próximo mes para finalizar el diseño de la camiseta; Jean trae camisetas de muestra de MBAR anteriores;</dd>

            <dt>11. Nuevo negocio:</dt>
            <dt>Café proporcionado en MBAR 2024: </dt>

            <dd>a. Servicio de café en el Monterey Conference Center: un galón de café o té (16 tazas de 8 onzas) equivale a $80; Con Impuestos y Propina - $108.75; 100 personas - Café por la mañana: 5 a 6 galones de café normal y 2 galones de té; Café PM: cuatro galones (café y té); Total: aprox. 12 galones por día; (Se estima que casi todo el mundo tomaría al menos una taza, y poco menos de la mitad de las personas tomaría dos tazas durante todo el día); El café a 50 galones por día costaría $5,437.50 por día; 500 personas serían 60 galones por día; Total: $6,525.00 por día; Durante dos días, aprox. 10.000 dólares para café; Cuando lleguemos a esa cantidad, retiramos el café; Sería aprox. 92 galones por los dos días;</dd>

            <dt>12. La próxima reunión del Comité Directivo es el martes 27/02/2024 a las 6 p. m. a través de Zoom;</dt>

            <dt>13. La próxima reunión del Comité es el sábado 9/03/2024 a las 10 a.m.;</dt>

            <dt>14. La reunión finalizó a las 11:15 am con la Oración de la Serenidad;</dt>
        </dl>

        <p> Asistentes: Carolyn, Chris, Cole, Dawn, Gina, Jane, Janet, Jean, Joanie, Kathleen, Kevin, Mary Grace, Naomi, Phil, Phillip, Renee, Robert y Roger;</p>

    </div>
</div>